# ==============================================================================
# Merged Lakeflow Source: amplitude
# ==============================================================================
# This file is auto-generated by tools/scripts/merge_python_source.py
# Do not edit manually. Make changes to the source files instead.
# ==============================================================================

from abc import ABC, abstractmethod
from datetime import datetime, timedelta, timezone
from decimal import Decimal
from itertools import chain
from typing import Any, Iterator, Sequence
import io
import json
import time

from pyspark.sql import Row
from pyspark.sql.datasource import (
    DataSource,
    DataSourceReader,
    DataSourceStreamReader,
    InputPartition,
    SimpleDataSourceStreamReader,
)
from pyspark.sql.streaming.datasource import ReadAllAvailable, SupportsTriggerAvailableNow
from pyspark.sql.types import (
    ArrayType,
    BinaryType,
    BooleanType,
    DataType,
    DateType,
    DecimalType,
    DoubleType,
    FloatType,
    IntegerType,
    LongType,
    MapType,
    StringType,
    StructField,
    StructType,
    TimestampType,
    VariantType,
    VariantVal,
)
from requests.auth import HTTPBasicAuth
from requests.exceptions import RequestException
import base64
import gzip
import requests
import zipfile


def register_lakeflow_source(spark):
    """Register the Lakeflow Python source with Spark."""

    ########################################################
    # src/databricks/labs/community_connector/libs/utils.py
    ########################################################

    def _parse_struct(value: Any, field_type: StructType) -> Row:
        """Parse a dictionary into a PySpark Row based on StructType schema."""
        if not isinstance(value, dict):
            raise ValueError(f"Expected a dictionary for StructType, got {type(value)}")
        # Spark Python -> Arrow conversion require missing StructType fields to be assigned None.
        if value == {}:
            raise ValueError(
                "field in StructType cannot be an empty dict. "
                "Please assign None as the default value instead."
            )
        field_dict = {}
        for field in field_type.fields:
            if field.name in value:
                field_dict[field.name] = parse_value(value.get(field.name), field.dataType)
            elif field.nullable:
                field_dict[field.name] = None
            else:
                raise ValueError(f"Field {field.name} is not nullable but not found in the input")
        return Row(**field_dict)


    def _parse_array(value: Any, field_type: ArrayType) -> list:
        """Parse a list into a PySpark array based on ArrayType schema."""
        if not isinstance(value, list):
            if field_type.containsNull:
                return [parse_value(value, field_type.elementType)]
            raise ValueError(f"Expected a list for ArrayType, got {type(value)}")
        return [parse_value(v, field_type.elementType) for v in value]


    def _parse_map(value: Any, field_type: MapType) -> dict:
        """Parse a dictionary into a PySpark map based on MapType schema."""
        if not isinstance(value, dict):
            raise ValueError(f"Expected a dictionary for MapType, got {type(value)}")
        return {
            parse_value(k, field_type.keyType): parse_value(v, field_type.valueType)
            for k, v in value.items()
        }


    def _parse_string(value: Any) -> str:
        """Convert value to string."""
        return str(value)


    def _parse_integer(value: Any) -> int:
        """Convert value to integer."""
        if isinstance(value, str) and value.strip():
            return int(float(value)) if "." in value else int(value)
        if isinstance(value, (int, float)):
            return int(value)
        raise ValueError(f"Cannot convert {value} to integer")


    def _parse_float(value: Any) -> float:
        """Convert value to float."""
        return float(value)


    def _parse_decimal(value: Any) -> Decimal:
        """Convert value to Decimal."""
        return Decimal(value) if isinstance(value, str) and value.strip() else Decimal(str(value))


    def _parse_boolean(value: Any) -> bool:
        """Convert value to boolean."""
        if isinstance(value, str):
            lowered = value.lower()
            if lowered in ("true", "t", "yes", "y", "1"):
                return True
            if lowered in ("false", "f", "no", "n", "0"):
                return False
        return bool(value)


    def _parse_date(value: Any) -> datetime.date:
        """Convert value to date."""
        if isinstance(value, str):
            for fmt in ("%Y-%m-%d", "%m/%d/%Y", "%d-%m-%Y", "%Y/%m/%d"):
                try:
                    return datetime.strptime(value, fmt).date()
                except ValueError:
                    continue
            return datetime.fromisoformat(value).date()
        if isinstance(value, datetime):
            return value.date()
        raise ValueError(f"Cannot convert {value} to date")


    def _parse_timestamp(value: Any) -> datetime:
        """Convert value to timestamp."""
        if isinstance(value, str):
            ts_value = value.replace("Z", "+00:00") if value.endswith("Z") else value
            try:
                return datetime.fromisoformat(ts_value)
            except ValueError:
                for fmt in ("%Y-%m-%d %H:%M:%S", "%Y/%m/%d %H:%M:%S"):
                    try:
                        return datetime.strptime(ts_value, fmt)
                    except ValueError:
                        continue
        elif isinstance(value, (int, float)):
            return datetime.fromtimestamp(value)
        elif isinstance(value, datetime):
            return value
        raise ValueError(f"Cannot convert {value} to timestamp")


    def _decode_string_to_bytes(value: str) -> bytes:
        """Try to decode a string as base64, then hex, then UTF-8."""
        try:
            return base64.b64decode(value)
        except Exception:
            pass
        try:
            return bytes.fromhex(value)
        except Exception:
            pass
        return value.encode("utf-8")


    def _parse_binary(value: Any) -> bytes:
        """Convert value to bytes. Tries base64, then hex, then UTF-8 for strings."""
        if isinstance(value, bytes):
            return value
        if isinstance(value, bytearray):
            return bytes(value)
        if isinstance(value, str):
            return _decode_string_to_bytes(value)
        if isinstance(value, list):
            return bytes(value)
        return str(value).encode("utf-8")


    # Mapping of primitive types to their parser functions
    _PRIMITIVE_PARSERS = {
        StringType: _parse_string,
        IntegerType: _parse_integer,
        LongType: _parse_integer,
        FloatType: _parse_float,
        DoubleType: _parse_float,
        DecimalType: _parse_decimal,
        BooleanType: _parse_boolean,
        DateType: _parse_date,
        TimestampType: _parse_timestamp,
        BinaryType: _parse_binary,
    }


    def parse_value(value: Any, field_type: DataType) -> Any:  # pylint: disable=too-many-return-statements
        """
        Converts a JSON value into a PySpark-compatible data type based on the provided field type.
        """
        if value is None:
            return None

        # Handle complex types
        if isinstance(field_type, StructType):
            return _parse_struct(value, field_type)
        if isinstance(field_type, ArrayType):
            return _parse_array(value, field_type)
        if isinstance(field_type, MapType):
            return _parse_map(value, field_type)

        # Handle VariantType
        if isinstance(field_type, VariantType):
            return VariantVal.parseJson(value) if isinstance(value, str) else value

        # Handle primitive types via type-based lookup
        try:
            field_type_class = type(field_type)
            if field_type_class in _PRIMITIVE_PARSERS:
                return _PRIMITIVE_PARSERS[field_type_class](value)

            # Check for custom UDT handling
            if hasattr(field_type, "fromJson"):
                return field_type.fromJson(value)

            raise TypeError(f"Unsupported field type: {field_type}")
        except (ValueError, TypeError) as e:
            raise ValueError(f"Error converting '{value}' ({type(value)}) to {field_type}: {str(e)}")


    ########################################################
    # src/databricks/labs/community_connector/interface/lakeflow_connect.py
    ########################################################

    class LakeflowConnect(ABC):
        """Base interface that each source connector must implement.

        Subclass this and implement all abstract methods to create a connector that
        integrates with the community connector library and ingestion pipeline.
        """

        def __init__(self, options: dict[str, str]) -> None:
            """
            Initialize the source connector with parameters needed to connect to the source.
            Args:
                options: A dictionary of parameters like authentication tokens, table names,
                    and other configurations.
            """
            self.options = options

        @abstractmethod
        def list_tables(self) -> list[str]:
            """
            List names of all the tables supported by the source connector.
            The list could either be a static list or retrieved from the source via API.
            Returns:
                A list of table names.
            """

        @abstractmethod
        def get_table_schema(
            self, table_name: str, table_options: dict[str, str]
        ) -> StructType:
            """
            Fetch the schema of a table.
            Args:
                table_name: The name of the table to fetch the schema for.
                table_options: A dictionary of options for accessing the table. For example,
                    the source API may require extra parameters needed to fetch the schema.
                    If there are no additional options required, you can ignore this
                    parameter, and no options will be provided during execution.
                    Only add parameters to table_options if they are essential for accessing
                    or retrieving the data (such as specifying table namespaces).
            Returns:
                A StructType object representing the schema of the table.
            """

        @abstractmethod
        def read_table_metadata(
            self, table_name: str, table_options: dict[str, str]
        ) -> dict:
            """
            Fetch the metadata of a table.
            Args:
                table_name: The name of the table to fetch the metadata for.
                table_options: A dictionary of options for accessing the table. For example,
                    the source API may require extra parameters needed to fetch the metadata.
                    If there are no additional options required, you can ignore this
                    parameter, and no options will be provided during execution.
                    Only add parameters to table_options if they are essential for accessing
                    or retrieving the data (such as specifying table namespaces).
            Returns:
                A dictionary containing the metadata of the table. It should include the
                following keys:
                    - primary_keys: List of string names of the primary key columns of
                        the table.
                    - cursor_field: The name of the field to use as a cursor for
                        incremental loading.
                    - ingestion_type: The type of ingestion to use for the table. It
                        should be one of the following values:
                        - "snapshot": For snapshot loading.
                        - "cdc": Capture incremental changes (no delete support).
                        - "cdc_with_deletes": Capture incremental changes with delete
                            support. Requires implementing read_table_deletes().
                        - "append": Incremental append.
            """

        @abstractmethod
        def read_table(
            self, table_name: str, start_offset: dict, table_options: dict[str, str]
        ) -> tuple[Iterator[dict], dict]:
            """
            Read the records of a table and return an iterator of records and an offset.

            The framework calls this method repeatedly to paginate through data.
            start_offset is None only on the very first call of the very first run
            of a connector. On subsequent runs the framework resumes from the last
            checkpointed offset, so start_offset will already be populated. Each
            call returns (records, end_offset). The framework passes end_offset as
            start_offset to the next call. Pagination stops when the returned
            offset equals start_offset (i.e., no more data).

            For tables that cannot be incrementally read, return None as the offset to
            read the entire table in one batch. Non-checkpointable synthetic offsets can
            be used to split the data into multiple batches.

            Args:
                table_name: The name of the table to read.
                start_offset: The offset to start reading from. None only on the
                    first call of the first run; on subsequent runs it carries the
                    checkpointed offset from the previous run.
                table_options: A dictionary of options for accessing the table. For example,
                    the source API may require extra parameters needed to read the table.
                    If there are no additional options required, you can ignore this
                    parameter, and no options will be provided during execution.
                    Only add parameters to table_options if they are essential for accessing
                    or retrieving the data (such as specifying table namespaces).
            Returns:
                A two-element tuple of (records, offset).
                records: An iterator of records as JSON-compatible dicts, or
                    ``pyarrow.RecordBatch`` objects for the Spark direct-Arrow path.
                    Do NOT convert row values according to get_table_schema(); the
                    framework handles row conversion.
                offset: A dict representing the position after this batch.
            """

        def read_table_deletes(
            self, table_name: str, start_offset: dict, table_options: dict[str, str]
        ) -> tuple[Iterator[dict], dict]:
            """
            Read deleted records from a table for CDC delete synchronization.
            This method is called when ingestion_type is "cdc_with_deletes" to fetch
            records that have been deleted from the source system.

            This method follows the same pagination and offset protocol as read_table:
            the framework calls it repeatedly, passing the previous end_offset as
            start_offset, until the returned offset equals start_offset.

            Override this method if any of your tables use ingestion_type
            "cdc_with_deletes". The default implementation raises NotImplementedError.

            The returned records should have at minimum the primary key fields and
            cursor field populated. Other fields can be null.

            Args:
                table_name: The name of the table to read deleted records from.
                start_offset: The offset to start reading from (same format as read_table).
                table_options: A dictionary of options for accessing the table.
            Returns:
                A two-element tuple of (records, offset).
                records: An iterator of deleted records (must include primary keys and cursor).
                offset: A dict (same format as read_table).
            """
            raise NotImplementedError(
                "read_table_deletes() must be implemented when ingestion_type is 'cdc_with_deletes'"
            )


    ########################################################
    # src/databricks/labs/community_connector/interface/supports_partition.py
    ########################################################

    class SupportsPartition(ABC):
        """Mixin for connectors that support partitioned reads across Spark executors.

        Must be used together with LakeflowConnect. Implement this when your
        connector can split work into partitions that Spark distributes to workers,
        instead of reading all data in one partition batch.

        Usage::

            class MyConnector(LakeflowConnect, SupportsPartition):
                ...
        """

        @abstractmethod
        def get_partitions(
            self,
            table_name: str,
            table_options: dict[str, str],
        ) -> Sequence[dict]:
            """Return partition descriptors for reading data.

            Each returned dict is passed to :meth:`read_partition` on an executor.

            Args:
                table_name: The name of the table.
                table_options: A dictionary of options for accessing the table.
            Returns:
                A sequence of partition descriptor dicts. Each dict must be
                JSON-serialisable (primitive types only).
            """

        @abstractmethod
        def read_partition(
            self, table_name: str, partition: dict, table_options: dict[str, str]
        ) -> Iterator[dict]:
            """Read records for a single partition.

            This method runs on Spark executors and must be self-contained.

            Args:
                table_name: The name of the table.
                partition: One of the partition dicts returned by
                    :meth:`get_partitions`.
                table_options: A dictionary of options for accessing the table.
            Returns:
                An iterator of JSON-compatible record dictionaries or PyArrow
                RecordBatch objects for Spark's direct-Arrow reader path.
            """


    class SupportsPartitionedStream(SupportsPartition):
        """Mixin for connectors that support partitioned streaming reads.

        Extends :class:`SupportsPartition` with offset awareness for streaming
        micro-batches. A connector implementing this mixin automatically supports
        both partitioned batch reads (via the inherited interface) and partitioned
        streaming reads.

        Usage::

            class MyConnector(LakeflowConnect, SupportsPartitionedStream):
                ...
        """

        def is_partitioned(self, table_name: str) -> bool:
            """Return whether the given table supports partitioned streaming.

            The default returns True. Override to return False for tables that
            should fall back to simpleStreamReader.

            Args:
                table_name: The name of the table.
                table_options: A dictionary of options for accessing the table.
            """
            return True

        @abstractmethod
        def latest_offset(
            self,
            table_name: str,
            table_options: dict[str, str],
            start_offset: dict | None = None,
        ) -> dict:
            """Return the most recent offset available for the table.

            Called by Spark on every micro-batch to discover new data.

            Micro-batch sizing (by row count, time window, etc.) is entirely the
            connector's responsibility — use table_options (e.g. ``window_days``,
            ``max_records_per_batch``) to control it.  The framework always
            requests "all available" and does not pass an admission-control
            hint here.

            Args:
                table_name: The name of the table.
                table_options: A dictionary of options for accessing the table.
                start_offset: The current committed offset.  ``{}`` on the very
                    first call (from ``initialOffset``), then the last returned
                    end_offset on each subsequent call.
            Returns:
                A dict whose keys and values are primitive types (str, int, bool).
            """

        @abstractmethod
        def get_partitions(
            self,
            table_name: str,
            table_options: dict[str, str],
            start_offset: dict | None = None,
            end_offset: dict | None = None,
        ) -> Sequence[dict]:
            """Return partition descriptors for reading data.

            Each returned dict is passed to :meth:`read_partition` on an executor.

            For batch reads, ``start_offset`` and ``end_offset`` are both None —
            return partitions covering the entire table.

            For streaming micro-batches, they delimit the offset range — return
            partitions covering that range, or an empty sequence when
            ``start_offset == end_offset``.

            Args:
                table_name: The name of the table.
                table_options: A dictionary of options for accessing the table.
                start_offset: The start offset (exclusive), or None for batch.
                end_offset: The end offset (inclusive), or None for batch.
            Returns:
                A sequence of partition descriptor dicts. Each dict must be
                JSON-serialisable (primitive types only).
            """


    ########################################################
    # src/databricks/labs/community_connector/interface/supports_namespaces.py
    ########################################################

    class SupportsNamespaces(ABC):
        """Mixin for connectors whose tables live under hierarchical namespaces.

        A namespace is a path of zero or more string segments (e.g. ``["org",
        "repo"]`` for GitHub, ``["tenant", "project"]`` for Azure DevOps).
        Connectors with a flat catalog do not need this mixin — the framework
        falls back to :meth:`LakeflowConnect.list_tables` and reports each table
        with an empty namespace.

        Output ordering on the ``_community_namespaces`` and ``_community_tables``
        Spark virtual tables is normalized by the framework via ``sorted(...)``,
        so connector implementations of :meth:`list_namespaces` and
        :meth:`list_tables_in_namespace` are free to return their results in
        any order (including from a :class:`set` or generator).

        Must be used together with :class:`LakeflowConnect`.

        Usage::

            class MyConnector(LakeflowConnect, SupportsNamespaces):
                ...
        """

        @abstractmethod
        def list_namespaces(
            self,
            prefix: list[str] | None = None,
        ) -> list[list[str]]:
            """Return the immediate child namespaces under ``prefix``.

            This method returns one level of *namespace* children only — it
            never returns tables. A namespace can hold tables and child
            namespaces independently; callers must always call
            :meth:`list_tables_in_namespace` for every namespace they care
            about, regardless of whether :meth:`list_namespaces` returned
            children for it. An empty return value just means there are no
            further child namespaces under ``prefix``.

            Walk the full tree by recursing on each returned child.

            Args:
                prefix: A namespace path under which to list children. ``None`` or
                    an empty list lists the root-level namespaces.
            Returns:
                A list of full namespace paths (each path includes the prefix).
            """

        @abstractmethod
        def list_tables_in_namespace(
            self,
            namespace: list[str],
        ) -> list[str]:
            """Return the table names that live directly under ``namespace``.

            Callers that want every table across the whole catalog walk the
            namespace tree via :meth:`list_namespaces` and call this method
            once per leaf — there is no "list everything" shortcut.

            Args:
                namespace: The namespace path. An empty list ``[]`` selects
                    root-level tables (those that live outside any namespace).
            Returns:
                A list of table names. The full ``(namespace, table_name)``
                row exposed on ``_community_tables`` is reconstructed by the
                framework from the namespace the caller already supplied, so
                the connector does not need to echo it back.
            """


    ########################################################
    # src/databricks/labs/community_connector/sources/amplitude/amplitude_schemas.py
    ########################################################

    RETRIABLE_STATUS_CODES = {429, 500, 502, 503, 504}
    MAX_RETRIES = 5
    INITIAL_BACKOFF = 1.0  # seconds; doubled after each retry

    # Default request timeout (seconds).  The Export API can be slow, so the
    # events reader overrides this with a larger value.
    DEFAULT_TIMEOUT = 60
    EXPORT_TIMEOUT = 120

    # Base URLs by data-residency region.
    BASE_URLS = {
        "standard": "https://amplitude.com",
        "eu": "https://analytics.eu.amplitude.com",
    }

    # ----- table catalogue --------------------------------------------------

    TABLES = [
        "events",
        "events_list",
        "active_users_counts",
        "average_session_length",
        "session_length_distribution",
        "sessions_per_user",
        "cohorts",
        "annotations",
        "taxonomy_events",
        "taxonomy_user_properties",
    ]

    # A free-form key/value object whose keys vary per event type / project.
    _DYNAMIC_MAP = MapType(StringType(), StringType())


    def _events_schema() -> StructType:
        """Raw event records exported via the Export API (one per gzipped NDJSON line)."""
        return StructType(
            [
                StructField("uuid", StringType(), nullable=False),
                StructField("event_id", LongType(), nullable=True),
                StructField("event_type", StringType(), nullable=True),
                StructField("event_time", TimestampType(), nullable=True),
                StructField("server_received_time", TimestampType(), nullable=True),
                # Incremental cursor — when Amplitude processed the event.
                StructField("server_upload_time", TimestampType(), nullable=True),
                StructField("client_event_time", TimestampType(), nullable=True),
                StructField("client_upload_time", TimestampType(), nullable=True),
                StructField("processed_time", TimestampType(), nullable=True),
                StructField("user_id", StringType(), nullable=True),
                StructField("device_id", StringType(), nullable=True),
                StructField("amplitude_id", LongType(), nullable=True),
                StructField("$insert_id", StringType(), nullable=True),
                StructField("app", LongType(), nullable=True),
                StructField("platform", StringType(), nullable=True),
                StructField("os_name", StringType(), nullable=True),
                StructField("os_version", StringType(), nullable=True),
                StructField("device_family", StringType(), nullable=True),
                StructField("device_type", StringType(), nullable=True),
                StructField("device_carrier", StringType(), nullable=True),
                StructField("country", StringType(), nullable=True),
                StructField("region", StringType(), nullable=True),
                StructField("city", StringType(), nullable=True),
                StructField("dma", StringType(), nullable=True),
                StructField("language", StringType(), nullable=True),
                StructField("ip_address", StringType(), nullable=True),
                StructField("location_lat", DoubleType(), nullable=True),
                StructField("location_lng", DoubleType(), nullable=True),
                StructField("version_name", StringType(), nullable=True),
                StructField("start_version", StringType(), nullable=True),
                StructField("session_id", LongType(), nullable=True),
                StructField("paying", BooleanType(), nullable=True),
                StructField("library", StringType(), nullable=True),
                StructField("event_properties", _DYNAMIC_MAP, nullable=True),
                StructField("user_properties", _DYNAMIC_MAP, nullable=True),
                StructField("group_properties", _DYNAMIC_MAP, nullable=True),
                StructField("groups", _DYNAMIC_MAP, nullable=True),
                StructField("data", _DYNAMIC_MAP, nullable=True),
                StructField("amplitude_attribution_ids", StringType(), nullable=True),
                StructField("sample_rate", StringType(), nullable=True),
            ]
        )


    def _events_list_schema() -> StructType:
        """Catalogue of visible event types with this week's totals."""
        return StructType(
            [
                StructField("value", StringType(), nullable=False),
                StructField("display", StringType(), nullable=True),
                StructField("non_active", BooleanType(), nullable=True),
                StructField("deleted", BooleanType(), nullable=True),
                StructField("hidden", BooleanType(), nullable=True),
                StructField("flow_hidden", BooleanType(), nullable=True),
                StructField("totals", LongType(), nullable=True),
            ]
        )


    def _active_users_counts_schema() -> StructType:
        """Daily active/new user counts, flattened to one row per (date, segment)."""
        return StructType(
            [
                StructField("date", StringType(), nullable=False),
                StructField("count", LongType(), nullable=True),
                StructField("segment", StringType(), nullable=True),
            ]
        )


    def _average_session_length_schema() -> StructType:
        """Daily average session length in seconds, one row per date."""
        return StructType(
            [
                StructField("date", StringType(), nullable=False),
                StructField("length", DoubleType(), nullable=True),
            ]
        )


    def _cohorts_schema() -> StructType:
        """Behavioral cohort definitions."""
        return StructType(
            [
                StructField("id", StringType(), nullable=False),
                StructField("name", StringType(), nullable=True),
                StructField("appId", LongType(), nullable=True),
                StructField("archived", BooleanType(), nullable=True),
                StructField("description", StringType(), nullable=True),
                StructField("finished", BooleanType(), nullable=True),
                StructField("published", BooleanType(), nullable=True),
                StructField("hidden", BooleanType(), nullable=True),
                StructField("size", LongType(), nullable=True),
                StructField("type", StringType(), nullable=True),
                StructField("owners", ArrayType(StringType()), nullable=True),
                StructField("viewers", ArrayType(StringType()), nullable=True),
                StructField("lastMod", LongType(), nullable=True),
                StructField("createdAt", LongType(), nullable=True),
                StructField("lastComputed", LongType(), nullable=True),
                StructField("metadata", ArrayType(StringType()), nullable=True),
                StructField("view_count", LongType(), nullable=True),
                StructField("popularity", LongType(), nullable=True),
                StructField("last_viewed", LongType(), nullable=True),
                StructField("chart_id", StringType(), nullable=True),
                StructField("edit_id", StringType(), nullable=True),
                StructField("is_predictive", BooleanType(), nullable=True),
                StructField("is_official_content", BooleanType(), nullable=True),
                StructField("location_id", StringType(), nullable=True),
                StructField("shortcut_ids", ArrayType(StringType()), nullable=True),
                # Opaque, deeply-nested blob — serialised to a JSON string.
                StructField("definition", StringType(), nullable=True),
            ]
        )


    def _session_length_distribution_schema() -> StructType:
        """Session length distribution — one row per pre-defined length bucket.

        The bucket label is the primary key (e.g. "0s-60s", "60s-300s").
        This is a snapshot over the requested date window; there is no date
        dimension in the response.
        """
        return StructType(
            [
                StructField("bucket", StringType(), nullable=False),
                StructField("count", LongType(), nullable=True),
            ]
        )


    def _sessions_per_user_schema() -> StructType:
        """Average sessions per user per day — one row per date."""
        return StructType(
            [
                StructField("date", StringType(), nullable=False),
                StructField("avg_sessions", DoubleType(), nullable=True),
            ]
        )


    def _taxonomy_events_schema() -> StructType:
        """Event type taxonomy — one row per planned event type.

        Hidden / deleted events are excluded by default (Amplitude API behaviour).
        """
        return StructType(
            [
                StructField("event_type", StringType(), nullable=False),
                StructField("category_name", StringType(), nullable=True),
                StructField("description", StringType(), nullable=True),
                StructField("display_name", StringType(), nullable=True),
                StructField("is_active", BooleanType(), nullable=True),
                StructField("is_hidden_from_dropdowns", BooleanType(), nullable=True),
                StructField("is_hidden_from_persona_results", BooleanType(), nullable=True),
                StructField("is_hidden_from_pathfinder", BooleanType(), nullable=True),
                StructField("is_hidden_from_timeline", BooleanType(), nullable=True),
                StructField("tags", ArrayType(StringType()), nullable=True),
                StructField("owner", StringType(), nullable=True),
            ]
        )


    def _taxonomy_user_properties_schema() -> StructType:
        """User property taxonomy — one row per planned user property.

        Custom properties have a ``gp:`` prefix in ``user_property``.
        Hidden / deleted properties are excluded by default.
        """
        return StructType(
            [
                StructField("user_property", StringType(), nullable=False),
                StructField("description", StringType(), nullable=True),
                StructField("type", StringType(), nullable=True),
                StructField("enum_values", ArrayType(StringType()), nullable=True),
                StructField("regex", StringType(), nullable=True),
                StructField("is_array_type", BooleanType(), nullable=True),
                StructField("is_hidden", BooleanType(), nullable=True),
                StructField("classifications", ArrayType(StringType()), nullable=True),
                StructField("deleted", BooleanType(), nullable=True),
            ]
        )


    def _annotations_schema() -> StructType:
        """Chart annotations (releases, incidents, …)."""
        return StructType(
            [
                StructField("id", LongType(), nullable=False),
                StructField("label", StringType(), nullable=True),
                StructField("start", TimestampType(), nullable=True),
                StructField("end", TimestampType(), nullable=True),
                StructField("details", StringType(), nullable=True),
                StructField("chart_id", StringType(), nullable=True),
                StructField(
                    "category",
                    StructType(
                        [
                            StructField("id", LongType(), nullable=True),
                            StructField("name", StringType(), nullable=True),
                        ]
                    ),
                    nullable=True,
                ),
            ]
        )


    TABLE_SCHEMAS = {
        "events": _events_schema(),
        "events_list": _events_list_schema(),
        "active_users_counts": _active_users_counts_schema(),
        "average_session_length": _average_session_length_schema(),
        "session_length_distribution": _session_length_distribution_schema(),
        "sessions_per_user": _sessions_per_user_schema(),
        "cohorts": _cohorts_schema(),
        "annotations": _annotations_schema(),
        "taxonomy_events": _taxonomy_events_schema(),
        "taxonomy_user_properties": _taxonomy_user_properties_schema(),
    }

    TABLE_METADATA = {
        "events": {
            "primary_keys": ["uuid"],
            "cursor_field": "server_upload_time",
            "ingestion_type": "append",
        },
        "events_list": {
            "primary_keys": ["value"],
            "cursor_field": None,
            "ingestion_type": "snapshot",
        },
        "active_users_counts": {
            # Composite key: segment is always present ("Totals" when g= is not
            # set, or the group-by value when it is).  Using only ["date"] would
            # silently overwrite earlier segments when multiple rows share the
            # same date — a data-loss bug when the g= table option is used.
            "primary_keys": ["date", "segment"],
            "cursor_field": "date",
            "ingestion_type": "cdc",
        },
        "average_session_length": {
            "primary_keys": ["date"],
            "cursor_field": "date",
            "ingestion_type": "cdc",
        },
        "cohorts": {
            "primary_keys": ["id"],
            "cursor_field": None,
            "ingestion_type": "snapshot",
        },
        "session_length_distribution": {
            # Snapshot: one row per pre-defined bucket ("0s-60s", "60s-300s", …).
            # The bucket label is stable across runs; the count reflects the
            # configured window (window_days).
            "primary_keys": ["bucket"],
            "cursor_field": None,
            "ingestion_type": "snapshot",
        },
        "sessions_per_user": {
            "primary_keys": ["date"],
            "cursor_field": "date",
            "ingestion_type": "cdc",
        },
        "annotations": {
            "primary_keys": ["id"],
            "cursor_field": None,
            "ingestion_type": "snapshot",
        },
        "taxonomy_events": {
            "primary_keys": ["event_type"],
            "cursor_field": None,
            "ingestion_type": "snapshot",
        },
        "taxonomy_user_properties": {
            "primary_keys": ["user_property"],
            "cursor_field": None,
            "ingestion_type": "snapshot",
        },
    }


    ########################################################
    # src/databricks/labs/community_connector/sources/amplitude/amplitude.py
    ########################################################

    class AmplitudeLakeflowConnect(LakeflowConnect):
        """LakeflowConnect implementation for Amplitude."""

        def __init__(self, options: dict[str, str]) -> None:
            super().__init__(options)
            self._api_key = options.get("api_key")
            self._secret_key = options.get("secret_key")
            if not self._api_key or not self._secret_key:
                raise ValueError(
                    "Amplitude connector requires 'api_key' and 'secret_key' in options"
                )

            region = options.get("data_region", "standard").lower()
            if region not in BASE_URLS:
                raise ValueError(
                    f"Unsupported data_region {region!r}; expected one of {sorted(BASE_URLS)}"
                )
            self._base_url = BASE_URLS[region]

            # Optional connection-level lower bound for the events backfill.
            self._start_date = options.get("start_date")

            # Freeze the upper bound at init time so incremental reads return a
            # stable cursor across microbatches within one Trigger.AvailableNow
            # trigger, guaranteeing termination.  A later trigger creates a fresh
            # instance with a newer cap and picks up any data that arrived since.
            now_utc = datetime.now(timezone.utc)
            self._init_ts = now_utc.isoformat()
            self._init_date = now_utc.strftime("%Y-%m-%d")

        # ----- HTTP -----------------------------------------------------------

        @property
        def _auth(self) -> HTTPBasicAuth:
            return HTTPBasicAuth(self._api_key, self._secret_key)

        def _request_with_retry(self, path: str, **kwargs) -> requests.Response:
            """GET ``path`` with exponential-backoff retries on transient errors.

            A fresh ``requests`` call is used per request (rather than a cached
            ``Session``) so the connector instance carries no non-picklable state
            when shipped to Spark executors.
            """
            url = f"{self._base_url}{path}"
            kwargs.setdefault("timeout", DEFAULT_TIMEOUT)
            backoff = INITIAL_BACKOFF
            resp = None
            last_exc: RequestException | None = None
            for attempt in range(MAX_RETRIES):
                try:
                    resp = requests.get(url, auth=self._auth, **kwargs)
                except RequestException as exc:
                    last_exc = exc
                else:
                    if resp.status_code not in RETRIABLE_STATUS_CODES:
                        return resp
                if attempt < MAX_RETRIES - 1:
                    # Respect server throttling hints when available.
                    sleep_for = backoff
                    if resp is not None:
                        retry_after = resp.headers.get("Retry-After", "").strip()
                        if retry_after:
                            try:
                                sleep_for = max(sleep_for, float(retry_after))
                            except ValueError:
                                pass
                    time.sleep(sleep_for)
                    backoff *= 2
            if resp is None and last_exc is not None:
                raise RuntimeError(
                    f"Amplitude request failed after {MAX_RETRIES} attempts for {path}: {last_exc}"
                ) from last_exc
            return resp

        # ----- interface ------------------------------------------------------

        def list_tables(self) -> list[str]:
            """Static object list — Amplitude does not expose discovery."""
            return list(TABLES)

        def get_table_schema(
            self, table_name: str, table_options: dict[str, str]
        ) -> StructType:
            self._validate_table(table_name)
            return TABLE_SCHEMAS[table_name]

        def read_table_metadata(
            self, table_name: str, table_options: dict[str, str]
        ) -> dict:
            self._validate_table(table_name)
            return dict(TABLE_METADATA[table_name])

        def read_table(
            self, table_name: str, start_offset: dict, table_options: dict[str, str]
        ) -> tuple[Iterator[dict], dict]:
            self._validate_table(table_name)
            start_offset = start_offset or {}

            if table_name == "events":
                return self._read_events(start_offset, table_options)
            if table_name == "events_list":
                return self._read_events_list()
            if table_name == "active_users_counts":
                return self._read_user_counts(start_offset, table_options)
            if table_name == "average_session_length":
                return self._read_session_length(start_offset, table_options)
            if table_name == "session_length_distribution":
                return self._read_session_length_distribution(table_options)
            if table_name == "sessions_per_user":
                return self._read_sessions_per_user(start_offset, table_options)
            if table_name == "cohorts":
                return self._read_cohorts()
            if table_name == "annotations":
                return self._read_annotations()
            if table_name == "taxonomy_events":
                return self._read_taxonomy_events()
            if table_name == "taxonomy_user_properties":
                return self._read_taxonomy_user_properties()
            raise ValueError(f"Unsupported table: {table_name!r}")

        # ----- helpers --------------------------------------------------------

        def _validate_table(self, table_name: str) -> None:
            if table_name not in TABLES:
                raise ValueError(
                    f"Table '{table_name}' is not supported. Supported tables: {TABLES}"
                )

        @staticmethod
        def _parse_dt(value: str) -> datetime:
            """Parse an ISO-8601 timestamp, tolerating a trailing ``Z``.

            Always returns a timezone-aware UTC datetime so it can be compared
            against the init-time cap.
            """
            text = value.strip()
            if text.endswith("Z"):
                text = text[:-1] + "+00:00"
            dt = datetime.fromisoformat(text)
            if dt.tzinfo is None:
                dt = dt.replace(tzinfo=timezone.utc)
            return dt.astimezone(timezone.utc)

        # ----- events (Export API, append) ------------------------------------

        def _read_events(
            self, start_offset: dict, table_options: dict[str, str]
        ) -> tuple[Iterator[dict], dict]:
            """Sliding hourly-window read over the Export API.

            One window per call: query ``[since, window_end]``, parse every event
            in the response, then advance the cursor past ``window_end``.  Append-only
            tables must never truncate a server response, so the whole window is
            returned; ``window_hours`` bounds the work per call instead of
            ``max_records_per_batch``.

            Availability lookback: Amplitude's Export API only makes an hour's data
            available ~2 hours after the server receives it (per the Export API
            docs).  Reading right up to "now" would query hours whose data has not
            published yet and then advance the cursor past them, silently dropping
            those events.  The readable ceiling is therefore ``init - lookback_hours``
            (default 2).  Override per table via the ``lookback_hours`` option;
            set ``0`` to read up to the init-time snapshot.
            """
            init_dt = self._parse_dt(self._init_ts)
            lookback_hours = self._non_negative_int_option(
                table_options, "lookback_hours", 2
            )
            ceiling_dt = init_dt - timedelta(hours=lookback_hours)
            window_hours = self._positive_int_option(table_options, "window_hours", 24)

            cursor = start_offset.get("cursor")
            if cursor:
                since_dt = self._parse_dt(cursor)
            elif self._start_date:
                since_dt = self._parse_dt(self._start_date)
            else:
                # Default backfill: only the most recent available window.  Set
                # ``start_date`` (connection option) for deeper history.
                since_dt = ceiling_dt - timedelta(hours=window_hours)

            # Caught up to the availability ceiling — signal "no more data".
            if since_dt >= ceiling_dt:
                return iter([]), start_offset

            window_end_dt = min(since_dt + timedelta(hours=window_hours), ceiling_dt)

            params = {
                "start": since_dt.strftime("%Y%m%dT%H"),
                "end": window_end_dt.strftime("%Y%m%dT%H"),
            }
            resp = self._request_with_retry(
                "/api/2/export", params=params, stream=True, timeout=EXPORT_TIMEOUT
            )

            # 404 = no data in the requested window (not an error).
            if resp.status_code == 404:
                records = []
            elif resp.status_code != 200:
                raise RuntimeError(
                    f"Amplitude Export API error: {resp.status_code} {resp.text[:500]}"
                )
            else:
                records = self._parse_export_body(resp.content)

            # The Export API treats ``end`` as *inclusive* at hourly resolution, so
            # the next window must start one hour past ``window_end_dt`` — otherwise
            # the boundary hour is fetched in both windows and, because ``events`` is
            # append-only (no load-time dedup), every record in it is ingested twice.
            end_offset = {"cursor": (window_end_dt + timedelta(hours=1)).isoformat()}
            return iter(records), end_offset

        @staticmethod
        def _parse_export_body(content: bytes) -> list[dict]:
            """Parse the Export API body into a list of event dicts.

            Real API: a ZIP archive of gzipped NDJSON files.  Simulator: a plain
            JSON array (or NDJSON) of event rows.  Both shapes are handled.
            """
            if not content:
                return []

            # Real Export API — ZIP of gzipped NDJSON.
            try:
                with zipfile.ZipFile(io.BytesIO(content)) as zf:
                    records: list[dict] = []
                    for name in zf.namelist():
                        with zf.open(name) as entry:
                            with gzip.open(entry, "rt", encoding="utf-8") as fh:
                                for line in fh:
                                    line = line.strip()
                                    if line:
                                        records.append(json.loads(line))
                    return records
            except zipfile.BadZipFile:
                pass

            # Fallback (simulator / non-zip): JSON array, wrapped array, or NDJSON.
            text = content.decode("utf-8", errors="replace").strip()
            if not text:
                return []
            try:
                data = json.loads(text)
            except json.JSONDecodeError:
                return [json.loads(line) for line in text.splitlines() if line.strip()]

            if isinstance(data, list):
                return data
            if isinstance(data, dict):
                for key in ("events", "data", "records"):
                    value = data.get(key)
                    if isinstance(value, list):
                        return value
            return []

        # ----- events_list (Dashboard REST, snapshot) -------------------------

        def _read_events_list(self) -> tuple[Iterator[dict], dict]:
            resp = self._request_with_retry("/api/2/events/list")
            if resp.status_code != 200:
                raise RuntimeError(
                    f"Amplitude events/list error: {resp.status_code} {resp.text[:500]}"
                )
            records = self._unwrap_list(resp.json(), "data")
            return iter(records), {}

        # ----- active_users_counts / average_session_length (cdc by date) -----

        def _read_user_counts(
            self, start_offset: dict, table_options: dict[str, str]
        ) -> tuple[Iterator[dict], dict]:
            return self._read_dashboard_series(
                "/api/2/users", start_offset, table_options, flatten=self._flatten_user_counts
            )

        def _read_session_length(
            self, start_offset: dict, table_options: dict[str, str]
        ) -> tuple[Iterator[dict], dict]:
            return self._read_dashboard_series(
                "/api/2/sessions/average",
                start_offset,
                table_options,
                flatten=self._flatten_session_length,
            )

        def _read_dashboard_series(
            self, path: str, start_offset: dict, table_options: dict[str, str], flatten
        ) -> tuple[Iterator[dict], dict]:
            """Sliding day-window read for the date-series Dashboard endpoints.

            One window per call.  The cursor is a ``YYYY-MM-DD`` date string; it
            advances to the window end (capped at the init-time date) so the read
            always makes forward progress and terminates.

            Admission control: these endpoints return a bounded date range per
            request (``window_days`` rows maximum).  ``max_records_per_batch`` is
            intentionally not read here — the window size is the natural batch
            bound, and the Amplitude Dashboard API does not support server-side
            record limits.  This is a deliberate divergence from the standard
            Strategy-B contract.
            """
            cursor = start_offset.get("cursor")
            since_date = cursor or self._start_date or self._default_metric_start(table_options)
            # Normalise to YYYY-MM-DD.
            since_date = since_date[:10]

            if since_date >= self._init_date:
                return iter([]), start_offset

            window_days = self._positive_int_option(table_options, "window_days", 30)
            since_dt = datetime.strptime(since_date, "%Y-%m-%d")
            window_end_dt = min(
                since_dt + timedelta(days=window_days),
                datetime.strptime(self._init_date, "%Y-%m-%d"),
            )
            window_end_date = window_end_dt.strftime("%Y-%m-%d")

            params = {
                "start": since_dt.strftime("%Y%m%d"),
                "end": window_end_dt.strftime("%Y%m%d"),
            }
            if path == "/api/2/users":
                params["m"] = table_options.get("m", "active")
                params["i"] = table_options.get("i", "1")
                if "g" in table_options:
                    params["g"] = table_options["g"]

            resp = self._request_with_retry(path, params=params)
            if resp.status_code != 200:
                raise RuntimeError(
                    f"Amplitude dashboard error for {path}: {resp.status_code} {resp.text[:500]}"
                )

            records = flatten(resp.json())
            end_offset = {"cursor": window_end_date}
            return iter(records), end_offset

        def _default_metric_start(self, table_options: dict[str, str]) -> str:
            """Default lower bound for date-series tables: one window back."""
            window_days = self._positive_int_option(table_options, "window_days", 30)
            init_dt = datetime.strptime(self._init_date, "%Y-%m-%d")
            return (init_dt - timedelta(days=window_days)).strftime("%Y-%m-%d")

        @staticmethod
        def _positive_int_option(
            table_options: dict[str, str], key: str, default_value: int
        ) -> int:
            """Parse a positive integer option and fail fast on invalid values."""
            raw_value = table_options.get(key, str(default_value))
            try:
                value = int(raw_value)
            except (TypeError, ValueError) as exc:
                raise ValueError(
                    f"Amplitude option '{key}' must be a positive integer; got {raw_value!r}"
                ) from exc
            if value <= 0:
                raise ValueError(
                    f"Amplitude option '{key}' must be a positive integer; got {raw_value!r}"
                )
            return value

        @staticmethod
        def _non_negative_int_option(
            table_options: dict[str, str], key: str, default_value: int
        ) -> int:
            """Parse a non-negative integer option (``0`` allowed; e.g. lookback)."""
            raw_value = table_options.get(key, str(default_value))
            try:
                value = int(raw_value)
            except (TypeError, ValueError) as exc:
                raise ValueError(
                    f"Amplitude option '{key}' must be a non-negative integer; got {raw_value!r}"
                ) from exc
            if value < 0:
                raise ValueError(
                    f"Amplitude option '{key}' must be a non-negative integer; got {raw_value!r}"
                )
            return value

        @staticmethod
        def _coerce_int(value) -> int | None:
            if value is None:
                return None
            if isinstance(value, bool):
                return int(value)
            if isinstance(value, (int, float)):
                return int(value)
            try:
                return int(str(value).strip())
            except (TypeError, ValueError):
                return None

        @staticmethod
        def _coerce_float(value) -> float | None:
            if value is None:
                return None
            if isinstance(value, bool):
                return float(value)
            if isinstance(value, (int, float)):
                return float(value)
            try:
                return float(str(value).strip())
            except (TypeError, ValueError):
                return None

        @staticmethod
        def _series_payload(body):
            """Return the ``data`` payload, tolerating both API and simulator shapes."""
            if isinstance(body, dict) and "data" in body:
                return body["data"]
            return body

        @classmethod
        def _flatten_user_counts(cls, body) -> list[dict]:
            payload = cls._series_payload(body)
            # Simulator path: already a flat list of {date, count, segment} rows.
            if isinstance(payload, list):
                return payload
            if not isinstance(payload, dict):
                return []

            series = payload.get("series") or []
            x_values = payload.get("xValues") or []
            meta = payload.get("seriesMeta") or []

            rows: list[dict] = []
            for s_idx, segment_series in enumerate(series):
                segment = cls._segment_label(meta, s_idx)
                for d_idx, date in enumerate(x_values):
                    if d_idx < len(segment_series):
                        rows.append(
                            {
                                "date": date,
                                "count": cls._coerce_int(segment_series[d_idx]),
                                "segment": segment,
                            }
                        )
            return rows

        @classmethod
        def _flatten_session_length_distribution(cls, body) -> list[dict]:
            """Flatten the sessions/length histogram to one row per bucket."""
            payload = cls._series_payload(body)
            if isinstance(payload, list):
                return payload
            if not isinstance(payload, dict):
                return []
            series = payload.get("series") or []
            x_values = payload.get("xValues") or []
            if not series:
                return []
            first_series = series[0]
            return [
                {"bucket": bucket, "count": cls._coerce_int(first_series[d_idx])}
                for d_idx, bucket in enumerate(x_values)
                if d_idx < len(first_series)
            ]

        @classmethod
        def _flatten_sessions_per_user(cls, body) -> list[dict]:
            """Flatten the sessions/peruser time series to one row per date."""
            payload = cls._series_payload(body)
            if isinstance(payload, list):
                return payload
            if not isinstance(payload, dict):
                return []
            series = payload.get("series") or []
            x_values = payload.get("xValues") or []
            if not series:
                return []
            first_series = series[0]
            return [
                {"date": date, "avg_sessions": cls._coerce_float(first_series[d_idx])}
                for d_idx, date in enumerate(x_values)
                if d_idx < len(first_series)
            ]

        @classmethod
        def _flatten_session_length(cls, body) -> list[dict]:
            payload = cls._series_payload(body)
            if isinstance(payload, list):
                return payload
            if not isinstance(payload, dict):
                return []

            series = payload.get("series") or []
            x_values = payload.get("xValues") or []
            if not series:
                return []

            first_series = series[0]
            rows: list[dict] = []
            for d_idx, date in enumerate(x_values):
                if d_idx < len(first_series):
                    rows.append(
                        {"date": date, "length": cls._coerce_float(first_series[d_idx])}
                    )
            return rows

        @staticmethod
        def _segment_label(meta: list, idx: int) -> str:
            """Resolve a segment label from ``seriesMeta``.

            ``seriesMeta`` entries are either group-by labels (strings) or
            ``{"segmentIndex": n}`` dicts for the default (un-grouped) case.
            """
            if idx < len(meta):
                entry = meta[idx]
                if isinstance(entry, str):
                    return entry
            return "Totals"

        # ----- session_length_distribution (Dashboard REST, snapshot) ---------

        def _read_session_length_distribution(
            self, table_options: dict[str, str]
        ) -> tuple[Iterator[dict], dict]:
            """Snapshot of session length histogram over the most recent window.

            The Dashboard `/api/2/sessions/length` endpoint aggregates over the
            requested date range and returns one count per pre-defined bucket
            (e.g. "0s-60s", "60s-300s").  There is no per-day breakdown, so this
            is modelled as a snapshot keyed on ``bucket``.  ``window_days``
            controls the lookback period (default 30 days).
            """
            window_days = self._positive_int_option(table_options, "window_days", 30)
            init_dt = datetime.strptime(self._init_date, "%Y-%m-%d")
            start_dt = init_dt - timedelta(days=window_days)
            params = {
                "start": start_dt.strftime("%Y%m%d"),
                "end": init_dt.strftime("%Y%m%d"),
            }
            resp = self._request_with_retry("/api/2/sessions/length", params=params)
            if resp.status_code != 200:
                raise RuntimeError(
                    f"Amplitude sessions/length error: {resp.status_code} {resp.text[:500]}"
                )
            records = self._flatten_session_length_distribution(resp.json())
            return iter(records), {}

        # ----- sessions_per_user (Dashboard REST, cdc) ------------------------

        def _read_sessions_per_user(
            self, start_offset: dict, table_options: dict[str, str]
        ) -> tuple[Iterator[dict], dict]:
            return self._read_dashboard_series(
                "/api/2/sessions/peruser",
                start_offset,
                table_options,
                flatten=self._flatten_sessions_per_user,
            )

        # ----- cohorts (Behavioral Cohorts API, snapshot) ---------------------

        def _read_cohorts(self) -> tuple[Iterator[dict], dict]:
            resp = self._request_with_retry("/api/3/cohorts")
            if resp.status_code != 200:
                raise RuntimeError(
                    f"Amplitude cohorts error: {resp.status_code} {resp.text[:500]}"
                )
            records = self._unwrap_list(resp.json(), "cohorts")
            for record in records:
                # ``definition`` is an opaque nested blob; serialise to a JSON
                # string to match the StringType column.
                definition = record.get("definition")
                if isinstance(definition, (dict, list)):
                    record["definition"] = json.dumps(definition)
            return iter(records), {}

        # ----- annotations (Chart Annotations API, snapshot) ------------------

        def _read_annotations(self) -> tuple[Iterator[dict], dict]:
            resp = self._request_with_retry("/api/3/annotations")
            if resp.status_code != 200:
                raise RuntimeError(
                    f"Amplitude annotations error: {resp.status_code} {resp.text[:500]}"
                )
            records = self._unwrap_list(resp.json(), "data")
            return iter(records), {}

        # ----- taxonomy_events (Taxonomy API, snapshot) -----------------------

        def _read_taxonomy_events(self) -> tuple[Iterator[dict], dict]:
            resp = self._request_with_retry("/api/2/taxonomy/event")
            if resp.status_code != 200:
                raise RuntimeError(
                    f"Amplitude taxonomy/event error: {resp.status_code} {resp.text[:500]}"
                )
            raw = self._unwrap_list(resp.json(), "data")
            records = [self._flatten_taxonomy_event(r) for r in raw]
            return iter(records), {}

        @staticmethod
        def _flatten_taxonomy_event(record: dict) -> dict:
            """Flatten the nested ``category`` struct and normalise nulls."""
            category = record.get("category") or {}
            return {
                "event_type": record.get("event_type"),
                "category_name": category.get("name") if isinstance(category, dict) else None,
                "description": record.get("description"),
                "display_name": record.get("display_name"),
                "is_active": record.get("is_active"),
                "is_hidden_from_dropdowns": record.get("is_hidden_from_dropdowns"),
                "is_hidden_from_persona_results": record.get("is_hidden_from_persona_results"),
                "is_hidden_from_pathfinder": record.get("is_hidden_from_pathfinder"),
                "is_hidden_from_timeline": record.get("is_hidden_from_timeline"),
                "tags": record.get("tags") or [],
                "owner": record.get("owner"),
            }

        # ----- taxonomy_user_properties (Taxonomy API, snapshot) -------------

        def _read_taxonomy_user_properties(self) -> tuple[Iterator[dict], dict]:
            resp = self._request_with_retry("/api/2/taxonomy/user-property")
            if resp.status_code != 200:
                raise RuntimeError(
                    f"Amplitude taxonomy/user-property error: {resp.status_code} {resp.text[:500]}"
                )
            records = self._unwrap_list(resp.json(), "data")
            return iter(records), {}

        @staticmethod
        def _unwrap_list(body, key: str) -> list[dict]:
            """Extract a record list from a wrapped or bare-list response."""
            if isinstance(body, list):
                return body
            if isinstance(body, dict):
                value = body.get(key)
                if isinstance(value, list):
                    return value
            return []


    ########################################################
    # src/databricks/labs/community_connector/sparkpds/lakeflow_datasource.py
    ########################################################

    LakeflowConnectImpl = AmplitudeLakeflowConnect
    # Constant option or column names
    METADATA_TABLE = "_community_table_metadata"
    NAMESPACES_TABLE = "_community_namespaces"
    TABLES_TABLE = "_community_tables"
    VIRTUAL_TABLES = (METADATA_TABLE, NAMESPACES_TABLE, TABLES_TABLE)
    TABLE_NAME = "tableName"
    TABLE_NAME_LIST = "tableNameList"
    TABLE_CONFIGS = "tableConfigs"
    IS_DELETE_FLOW = "isDeleteFlow"
    NAMESPACE_PREFIX = "namespacePrefix"
    NAMESPACE = "namespace"


    def _decode_list_of_str_option(option_name: str, value: str | None) -> list[str] | None:
        """Decode and validate a JSON-encoded ``list[str]`` Spark option.

        Returns ``None`` if the option is absent; otherwise the parsed list.
        Raises ``ValueError`` with the offending value if the JSON is malformed
        or the decoded value is not a list of strings.
        """
        if value is None:
            return None
        try:
            decoded = json.loads(value)
        except json.JSONDecodeError as e:
            raise ValueError(
                f"option '{option_name}' must be a JSON-encoded list[str]; "
                f"got non-JSON value: {value!r}"
            ) from e
        if not isinstance(decoded, list) or not all(isinstance(s, str) for s in decoded):
            raise ValueError(
                f"option '{option_name}' must be a JSON-encoded list[str]; "
                f"got: {decoded!r}"
            )
        return decoded


    def _decode_dict_option(option_name: str, value: str | None) -> dict:
        """Decode and validate a JSON-encoded ``dict`` Spark option."""
        if value is None:
            return {}
        try:
            decoded = json.loads(value)
        except json.JSONDecodeError as e:
            raise ValueError(
                f"option '{option_name}' must be a JSON-encoded dict; "
                f"got non-JSON value: {value!r}"
            ) from e
        if not isinstance(decoded, dict):
            raise ValueError(
                f"option '{option_name}' must be a JSON-encoded dict; got: {decoded!r}"
            )
        return decoded


    def _parse_or_passthrough_records(records, schema: StructType):
        """Convert row records while passing PyArrow RecordBatches directly to Spark."""
        iterator = iter(records)
        try:
            first = next(iterator)
        except StopIteration:
            return iter(())

        first_type = type(first)
        if first_type.__name__ == "RecordBatch" and first_type.__module__.startswith("pyarrow."):
            return chain((first,), iterator)

        return chain(
            (parse_value(first, schema),),
            map(lambda value: parse_value(value, schema), iterator),
        )


    # PySpark's DataSource API requires camelCase method names and inherits
    # semantics from the parent class, so per-method docstrings are redundant.
    # pylint: disable=invalid-name,missing-function-docstring
    class LakeflowStreamReader(SimpleDataSourceStreamReader, SupportsTriggerAvailableNow):
        """
        Implements a data source stream reader for Lakeflow Connect.
        Currently, only the simpleStreamReader is implemented, which uses a
        more generic protocol suitable for most data sources that support
        incremental loading.
        """

        def __init__(
            self,
            options: dict[str, str],
            schema: StructType,
            lakeflow_connect: LakeflowConnect,
        ):
            self.options = options
            self.lakeflow_connect = lakeflow_connect
            self.schema = schema

        def initialOffset(self):
            return {}

        def read(self, start: dict) -> (Iterator[tuple], dict):
            is_delete_flow = self.options.get(IS_DELETE_FLOW) == "true"
            # Strip delete flow options before passing to connector
            table_options = {
                k: v for k, v in self.options.items() if k != IS_DELETE_FLOW
            }

            if is_delete_flow:
                records, offset = self.lakeflow_connect.read_table_deletes(
                    self.options[TABLE_NAME], start, table_options
                )
            else:
                records, offset = self.lakeflow_connect.read_table(
                    self.options[TABLE_NAME], start, table_options
                )
            rows = _parse_or_passthrough_records(records, self.schema)
            return rows, offset

        def readBetweenOffsets(self, start: dict, end: dict) -> Iterator[tuple]:
            # TODO: This does not ensure the records returned are identical across repeated calls.
            # For append-only tables, the data source must guarantee that reading from the same
            # start offset will always yield the same set of records.
            # For tables ingested as incremental CDC, it is only necessary that no new changes
            # are missed in the returned records.
            return self.read(start)[0]

        def prepareForTriggerAvailableNow(self) -> None:
            # No need to do anything special here. Everything is handled in the __init__ method.
            pass


    class LakeflowPartitionedStreamReader(DataSourceStreamReader, SupportsTriggerAvailableNow):
        """Proxy that bridges SupportsPartitionedStream to PySpark's DataSourceStreamReader.

        Used when a connector implements the SupportsPartitionedStream mixin to
        support partitioned streaming reads across Spark executors.
        """

        def __init__(
            self,
            options: dict[str, str],
            schema: StructType,
            lakeflow_connect: LakeflowConnect,
        ):
            self.options = options
            self.schema = schema
            self.lakeflow_connect = lakeflow_connect
            self.table_name = options[TABLE_NAME]
            self.table_options = {k: v for k, v in options.items() if k != IS_DELETE_FLOW}

        def initialOffset(self):
            return {}

        def getDefaultReadLimit(self):
            # Admission control is the connector's responsibility (e.g. via
            # window_days, max_records_per_batch), not the engine's.  Always
            # ask the engine for ReadAllAvailable.
            return ReadAllAvailable()

        def latestOffset(self, start: dict, limit) -> dict:
            # We declared ReadAllAvailable via getDefaultReadLimit; the engine
            # must respect it.  Anything else means admission-control expectations
            # we do not support — fail loudly rather than silently ignore.
            if not isinstance(limit, ReadAllAvailable):
                raise ValueError(
                    f"LakeflowPartitionedStreamReader only supports ReadAllAvailable; "
                    f"got {type(limit).__name__}. Micro-batch sizing must be controlled "
                    f"by the connector implementation (table_options), not the engine."
                )
            return self.lakeflow_connect.latest_offset(
                self.table_name, self.table_options, start
            )

        def partitions(self, start: dict, end: dict):
            partition_descs = self.lakeflow_connect.get_partitions(
                self.table_name, self.table_options, start, end
            )
            return [InputPartition(json.dumps(p)) for p in partition_descs]

        def read(self, partition: InputPartition):
            partition_desc = json.loads(partition.value)
            records = self.lakeflow_connect.read_partition(
                self.table_name, partition_desc, self.table_options
            )
            return _parse_or_passthrough_records(records, self.schema)

        def prepareForTriggerAvailableNow(self) -> None:
            # No need to do anything special here. Everything is handled in the __init__ method.
            pass


    class LakeflowBatchReader(DataSourceReader):
        def __init__(
            self,
            options: dict[str, str],
            schema: StructType,
            lakeflow_connect: LakeflowConnect,
        ):
            self.options = options
            self.schema = schema
            self.lakeflow_connect = lakeflow_connect
            self.table_name = options[TABLE_NAME]
            self._supports_partition = isinstance(lakeflow_connect, SupportsPartition)

        def partitions(self):
            if self._supports_partition and self.table_name not in VIRTUAL_TABLES:
                try:
                    partition_descs = self.lakeflow_connect.get_partitions(
                        self.table_name, self.options
                    )
                    return [InputPartition(json.dumps(p)) for p in partition_descs]
                except Exception:
                    self._supports_partition = False
            return [InputPartition(None)]

        def read(self, partition):
            if self.table_name == METADATA_TABLE:
                records = self._read_table_metadata()
            elif self.table_name == NAMESPACES_TABLE:
                records = self._read_namespaces()
            elif self.table_name == TABLES_TABLE:
                records = self._read_tables()
            elif self._supports_partition and partition.value is not None:
                partition_desc = json.loads(partition.value)
                records = self.lakeflow_connect.read_partition(
                    self.table_name, partition_desc, self.options
                )
            else:
                records, _ = self.lakeflow_connect.read_table(self.table_name, None, self.options)
            return _parse_or_passthrough_records(records, self.schema)

        def _read_table_metadata(self):
            table_names = _decode_list_of_str_option(
                TABLE_NAME_LIST, self.options.get(TABLE_NAME_LIST)
            ) or []
            table_configs = _decode_dict_option(
                TABLE_CONFIGS, self.options.get(TABLE_CONFIGS)
            )
            all_records = []
            # Preserve caller-supplied table order — caller controls it.
            for table in table_names:
                metadata = self.lakeflow_connect.read_table_metadata(
                    table, table_configs.get(table, {})
                )
                all_records.append({TABLE_NAME: table, **metadata})
            return all_records

        def _read_namespaces(self):
            # Connectors without SupportsNamespaces are flat — no rows.
            if not isinstance(self.lakeflow_connect, SupportsNamespaces):
                return []
            prefix = _decode_list_of_str_option(
                NAMESPACE_PREFIX, self.options.get(NAMESPACE_PREFIX)
            )
            namespaces = self.lakeflow_connect.list_namespaces(prefix)
            # Sort framework-side for deterministic output regardless of
            # connector iteration order.
            return [{"namespace": ns} for ns in sorted(namespaces)]

        def _read_tables(self):
            namespace_supplied = NAMESPACE in self.options
            if isinstance(self.lakeflow_connect, SupportsNamespaces):
                if not namespace_supplied:
                    raise ValueError(
                        f"option '{NAMESPACE}' is required when reading "
                        f"'{TABLES_TABLE}' against a connector that implements "
                        f"SupportsNamespaces. Pass a JSON-encoded list[str] "
                        f"(use '[]' for root-level tables; walk the tree via "
                        f"'{NAMESPACES_TABLE}' to enumerate every namespace)."
                    )
                namespace = _decode_list_of_str_option(
                    NAMESPACE, self.options[NAMESPACE]
                )
                tables = self.lakeflow_connect.list_tables_in_namespace(namespace)
                return [
                    {"namespace": namespace, TABLE_NAME: tn}
                    for tn in sorted(tables)
                ]
            # Flat connector path. Reject a stray `namespace` option — the
            # caller probably mistook this connector for namespace-aware and
            # silently ignoring the option would mask the bug.
            if namespace_supplied:
                raise ValueError(
                    f"option '{NAMESPACE}' was supplied but the connector does "
                    f"not implement SupportsNamespaces. Either omit the option "
                    f"or use a namespace-aware connector."
                )
            return [
                {"namespace": [], TABLE_NAME: tn}
                for tn in sorted(self.lakeflow_connect.list_tables())
            ]


    class LakeflowSource(DataSource):
        """
        PySpark DataSource base for Lakeflow Connect.

        Two ways the connector implementation is bound:

        - Per-source subclass (wheel / multi-file deployment): subclass and set
          ``_lakeflow_connect_cls``::

              class GmailDataSource(LakeflowSource):
                  _lakeflow_connect_cls = GmailLakeflowConnect

              spark.dataSource.register(GmailDataSource)

        - Merged single-file deployment (SDP): ``_lakeflow_connect_cls`` is left
          ``None`` and the connector is taken from the module-level
          ``LakeflowConnectImpl`` placeholder, which the merge script substitutes
          with the actual implementation class.
        """

        # Per-source subclasses set this. Left ``None`` on the base so the merged
        # single-file path falls back to the ``LakeflowConnectImpl`` placeholder.
        _lakeflow_connect_cls = None

        # Spark format name. Defaults to "lakeflow_connect" because Unity Catalog
        # connection-option injection looks for that exact string. A per-source
        # subclass may override this with its source name once it no longer relies
        # on UC injection (see the commented override in each source's __init__.py).
        _format_name = "lakeflow_connect"

        def __init__(self, options):
            self.options = options
            table = options.get(TABLE_NAME)
            # Catch typos against the framework's reserved virtual-table namespace
            # early — falling through to the connector with an unknown
            # `_community_*` name yields a confusing per-connector error.
            if table and table.startswith("_community_") and table not in VIRTUAL_TABLES:
                raise ValueError(
                    f"unknown framework virtual table '{table}'. Valid framework "
                    f"virtual tables are: {', '.join(VIRTUAL_TABLES)}. "
                    f"For a regular source table, use a name that does not start "
                    f"with '_community_'."
                )
            # Per-source subclasses bind the implementation via _lakeflow_connect_cls.
            # The merged single-file path leaves it None and relies on the
            # LakeflowConnectImpl placeholder (substituted by the merge script).
            connect_cls = type(self)._lakeflow_connect_cls or LakeflowConnectImpl
            self.lakeflow_connect = connect_cls(options)  # pylint: disable=abstract-class-instantiated

        @classmethod
        def name(cls):
            return cls._format_name

        def schema(self):
            table = self.options[TABLE_NAME]
            if table == METADATA_TABLE:
                return StructType(
                    [
                        StructField(TABLE_NAME, StringType(), False),
                        StructField("primary_keys", ArrayType(StringType()), True),
                        StructField("cursor_field", StringType(), True),
                        StructField("ingestion_type", StringType(), True),
                    ]
                )
            if table == NAMESPACES_TABLE:
                return StructType(
                    [
                        StructField("namespace", ArrayType(StringType()), False),
                    ]
                )
            if table == TABLES_TABLE:
                return StructType(
                    [
                        StructField("namespace", ArrayType(StringType()), False),
                        StructField(TABLE_NAME, StringType(), False),
                    ]
                )
            return self.lakeflow_connect.get_table_schema(table, self.options)

        def reader(self, schema: StructType):
            return LakeflowBatchReader(self.options, schema, self.lakeflow_connect)

        def streamReader(self, schema: StructType):
            # Use the partitioned DataSourceStreamReader when the connector
            # implements SupportsPartitionedStream and the table opts in.
            # Otherwise, delegate to super() which raises PySparkNotImplementedError,
            # causing Spark to fall back to simpleStreamReader().
            if isinstance(self.lakeflow_connect, SupportsPartitionedStream):
                table = self.options[TABLE_NAME]
                if self.lakeflow_connect.is_partitioned(table):
                    return LakeflowPartitionedStreamReader(self.options, schema, self.lakeflow_connect)
            return super().streamReader(schema)

        def simpleStreamReader(self, schema: StructType):
            return LakeflowStreamReader(self.options, schema, self.lakeflow_connect)


    spark.dataSource.register(LakeflowSource)
