# ==============================================================================
# Merged Lakeflow Source: mailchimp
# ==============================================================================
# This file is auto-generated by tools/scripts/merge_python_source.py
# Do not edit manually. Make changes to the source files instead.
# ==============================================================================

from abc import ABC, abstractmethod
from datetime import datetime, timedelta, timezone
from decimal import Decimal
from itertools import chain
from typing import (
    Any,
    Dict,
    Iterator,
    List,
    Optional,
    Sequence,
    Tuple,
)
import json
import re
import time

from pyspark.sql import Row
from pyspark.sql.datasource import (
    DataSource,
    DataSourceReader,
    DataSourceStreamReader,
    InputPartition,
    SimpleDataSourceStreamReader,
)
from pyspark.sql.streaming.datasource import ReadAllAvailable, SupportsTriggerAvailableNow
from pyspark.sql.types import (
    ArrayType,
    BinaryType,
    BooleanType,
    DataType,
    DateType,
    DecimalType,
    DoubleType,
    FloatType,
    IntegerType,
    LongType,
    MapType,
    StringType,
    StructField,
    StructType,
    TimestampType,
    VariantType,
    VariantVal,
)
import base64
import requests


def register_lakeflow_source(spark):
    """Register the Lakeflow Python source with Spark."""

    ########################################################
    # src/databricks/labs/community_connector/libs/utils.py
    ########################################################

    def _parse_struct(value: Any, field_type: StructType) -> Row:
        """Parse a dictionary into a PySpark Row based on StructType schema."""
        if not isinstance(value, dict):
            raise ValueError(f"Expected a dictionary for StructType, got {type(value)}")
        # Spark Python -> Arrow conversion require missing StructType fields to be assigned None.
        if value == {}:
            raise ValueError(
                "field in StructType cannot be an empty dict. "
                "Please assign None as the default value instead."
            )
        field_dict = {}
        for field in field_type.fields:
            if field.name in value:
                field_dict[field.name] = parse_value(value.get(field.name), field.dataType)
            elif field.nullable:
                field_dict[field.name] = None
            else:
                raise ValueError(f"Field {field.name} is not nullable but not found in the input")
        return Row(**field_dict)


    def _parse_array(value: Any, field_type: ArrayType) -> list:
        """Parse a list into a PySpark array based on ArrayType schema."""
        if not isinstance(value, list):
            if field_type.containsNull:
                return [parse_value(value, field_type.elementType)]
            raise ValueError(f"Expected a list for ArrayType, got {type(value)}")
        return [parse_value(v, field_type.elementType) for v in value]


    def _parse_map(value: Any, field_type: MapType) -> dict:
        """Parse a dictionary into a PySpark map based on MapType schema."""
        if not isinstance(value, dict):
            raise ValueError(f"Expected a dictionary for MapType, got {type(value)}")
        return {
            parse_value(k, field_type.keyType): parse_value(v, field_type.valueType)
            for k, v in value.items()
        }


    def _parse_string(value: Any) -> str:
        """Convert value to string."""
        return str(value)


    def _parse_integer(value: Any) -> int:
        """Convert value to integer."""
        if isinstance(value, str) and value.strip():
            return int(float(value)) if "." in value else int(value)
        if isinstance(value, (int, float)):
            return int(value)
        raise ValueError(f"Cannot convert {value} to integer")


    def _parse_float(value: Any) -> float:
        """Convert value to float."""
        return float(value)


    def _parse_decimal(value: Any) -> Decimal:
        """Convert value to Decimal."""
        return Decimal(value) if isinstance(value, str) and value.strip() else Decimal(str(value))


    def _parse_boolean(value: Any) -> bool:
        """Convert value to boolean."""
        if isinstance(value, str):
            lowered = value.lower()
            if lowered in ("true", "t", "yes", "y", "1"):
                return True
            if lowered in ("false", "f", "no", "n", "0"):
                return False
        return bool(value)


    def _parse_date(value: Any) -> datetime.date:
        """Convert value to date."""
        if isinstance(value, str):
            for fmt in ("%Y-%m-%d", "%m/%d/%Y", "%d-%m-%Y", "%Y/%m/%d"):
                try:
                    return datetime.strptime(value, fmt).date()
                except ValueError:
                    continue
            return datetime.fromisoformat(value).date()
        if isinstance(value, datetime):
            return value.date()
        raise ValueError(f"Cannot convert {value} to date")


    def _parse_timestamp(value: Any) -> datetime:
        """Convert value to timestamp."""
        if isinstance(value, str):
            ts_value = value.replace("Z", "+00:00") if value.endswith("Z") else value
            try:
                return datetime.fromisoformat(ts_value)
            except ValueError:
                for fmt in ("%Y-%m-%d %H:%M:%S", "%Y/%m/%d %H:%M:%S"):
                    try:
                        return datetime.strptime(ts_value, fmt)
                    except ValueError:
                        continue
        elif isinstance(value, (int, float)):
            return datetime.fromtimestamp(value)
        elif isinstance(value, datetime):
            return value
        raise ValueError(f"Cannot convert {value} to timestamp")


    def _decode_string_to_bytes(value: str) -> bytes:
        """Try to decode a string as base64, then hex, then UTF-8."""
        try:
            return base64.b64decode(value)
        except Exception:
            pass
        try:
            return bytes.fromhex(value)
        except Exception:
            pass
        return value.encode("utf-8")


    def _parse_binary(value: Any) -> bytes:
        """Convert value to bytes. Tries base64, then hex, then UTF-8 for strings."""
        if isinstance(value, bytes):
            return value
        if isinstance(value, bytearray):
            return bytes(value)
        if isinstance(value, str):
            return _decode_string_to_bytes(value)
        if isinstance(value, list):
            return bytes(value)
        return str(value).encode("utf-8")


    # Mapping of primitive types to their parser functions
    _PRIMITIVE_PARSERS = {
        StringType: _parse_string,
        IntegerType: _parse_integer,
        LongType: _parse_integer,
        FloatType: _parse_float,
        DoubleType: _parse_float,
        DecimalType: _parse_decimal,
        BooleanType: _parse_boolean,
        DateType: _parse_date,
        TimestampType: _parse_timestamp,
        BinaryType: _parse_binary,
    }


    def parse_value(value: Any, field_type: DataType) -> Any:  # pylint: disable=too-many-return-statements
        """
        Converts a JSON value into a PySpark-compatible data type based on the provided field type.
        """
        if value is None:
            return None

        # Handle complex types
        if isinstance(field_type, StructType):
            return _parse_struct(value, field_type)
        if isinstance(field_type, ArrayType):
            return _parse_array(value, field_type)
        if isinstance(field_type, MapType):
            return _parse_map(value, field_type)

        # Handle VariantType
        if isinstance(field_type, VariantType):
            return VariantVal.parseJson(value) if isinstance(value, str) else value

        # Handle primitive types via type-based lookup
        try:
            field_type_class = type(field_type)
            if field_type_class in _PRIMITIVE_PARSERS:
                return _PRIMITIVE_PARSERS[field_type_class](value)

            # Check for custom UDT handling
            if hasattr(field_type, "fromJson"):
                return field_type.fromJson(value)

            raise TypeError(f"Unsupported field type: {field_type}")
        except (ValueError, TypeError) as e:
            raise ValueError(f"Error converting '{value}' ({type(value)}) to {field_type}: {str(e)}")


    ########################################################
    # src/databricks/labs/community_connector/interface/lakeflow_connect.py
    ########################################################

    class LakeflowConnect(ABC):
        """Base interface that each source connector must implement.

        Subclass this and implement all abstract methods to create a connector that
        integrates with the community connector library and ingestion pipeline.
        """

        def __init__(self, options: dict[str, str]) -> None:
            """
            Initialize the source connector with parameters needed to connect to the source.
            Args:
                options: A dictionary of parameters like authentication tokens, table names,
                    and other configurations.
            """
            self.options = options

        @abstractmethod
        def list_tables(self) -> list[str]:
            """
            List names of all the tables supported by the source connector.
            The list could either be a static list or retrieved from the source via API.
            Returns:
                A list of table names.
            """

        @abstractmethod
        def get_table_schema(
            self, table_name: str, table_options: dict[str, str]
        ) -> StructType:
            """
            Fetch the schema of a table.
            Args:
                table_name: The name of the table to fetch the schema for.
                table_options: A dictionary of options for accessing the table. For example,
                    the source API may require extra parameters needed to fetch the schema.
                    If there are no additional options required, you can ignore this
                    parameter, and no options will be provided during execution.
                    Only add parameters to table_options if they are essential for accessing
                    or retrieving the data (such as specifying table namespaces).
            Returns:
                A StructType object representing the schema of the table.
            """

        @abstractmethod
        def read_table_metadata(
            self, table_name: str, table_options: dict[str, str]
        ) -> dict:
            """
            Fetch the metadata of a table.
            Args:
                table_name: The name of the table to fetch the metadata for.
                table_options: A dictionary of options for accessing the table. For example,
                    the source API may require extra parameters needed to fetch the metadata.
                    If there are no additional options required, you can ignore this
                    parameter, and no options will be provided during execution.
                    Only add parameters to table_options if they are essential for accessing
                    or retrieving the data (such as specifying table namespaces).
            Returns:
                A dictionary containing the metadata of the table. It should include the
                following keys:
                    - primary_keys: List of string names of the primary key columns of
                        the table.
                    - cursor_field: The name of the field to use as a cursor for
                        incremental loading.
                    - ingestion_type: The type of ingestion to use for the table. It
                        should be one of the following values:
                        - "snapshot": For snapshot loading.
                        - "cdc": Capture incremental changes (no delete support).
                        - "cdc_with_deletes": Capture incremental changes with delete
                            support. Requires implementing read_table_deletes().
                        - "append": Incremental append.
            """

        @abstractmethod
        def read_table(
            self, table_name: str, start_offset: dict, table_options: dict[str, str]
        ) -> tuple[Iterator[dict], dict]:
            """
            Read the records of a table and return an iterator of records and an offset.

            The framework calls this method repeatedly to paginate through data.
            start_offset is None only on the very first call of the very first run
            of a connector. On subsequent runs the framework resumes from the last
            checkpointed offset, so start_offset will already be populated. Each
            call returns (records, end_offset). The framework passes end_offset as
            start_offset to the next call. Pagination stops when the returned
            offset equals start_offset (i.e., no more data).

            For tables that cannot be incrementally read, return None as the offset to
            read the entire table in one batch. Non-checkpointable synthetic offsets can
            be used to split the data into multiple batches.

            Args:
                table_name: The name of the table to read.
                start_offset: The offset to start reading from. None only on the
                    first call of the first run; on subsequent runs it carries the
                    checkpointed offset from the previous run.
                table_options: A dictionary of options for accessing the table. For example,
                    the source API may require extra parameters needed to read the table.
                    If there are no additional options required, you can ignore this
                    parameter, and no options will be provided during execution.
                    Only add parameters to table_options if they are essential for accessing
                    or retrieving the data (such as specifying table namespaces).
            Returns:
                A two-element tuple of (records, offset).
                records: An iterator of records as JSON-compatible dicts, or
                    ``pyarrow.RecordBatch`` objects for the Spark direct-Arrow path.
                    Do NOT convert row values according to get_table_schema(); the
                    framework handles row conversion.
                offset: A dict representing the position after this batch.
            """

        def read_table_deletes(
            self, table_name: str, start_offset: dict, table_options: dict[str, str]
        ) -> tuple[Iterator[dict], dict]:
            """
            Read deleted records from a table for CDC delete synchronization.
            This method is called when ingestion_type is "cdc_with_deletes" to fetch
            records that have been deleted from the source system.

            This method follows the same pagination and offset protocol as read_table:
            the framework calls it repeatedly, passing the previous end_offset as
            start_offset, until the returned offset equals start_offset.

            Override this method if any of your tables use ingestion_type
            "cdc_with_deletes". The default implementation raises NotImplementedError.

            The returned records should have at minimum the primary key fields and
            cursor field populated. Other fields can be null.

            Args:
                table_name: The name of the table to read deleted records from.
                start_offset: The offset to start reading from (same format as read_table).
                table_options: A dictionary of options for accessing the table.
            Returns:
                A two-element tuple of (records, offset).
                records: An iterator of deleted records (must include primary keys and cursor).
                offset: A dict (same format as read_table).
            """
            raise NotImplementedError(
                "read_table_deletes() must be implemented when ingestion_type is 'cdc_with_deletes'"
            )


    ########################################################
    # src/databricks/labs/community_connector/interface/supports_partition.py
    ########################################################

    class SupportsPartition(ABC):
        """Mixin for connectors that support partitioned reads across Spark executors.

        Must be used together with LakeflowConnect. Implement this when your
        connector can split work into partitions that Spark distributes to workers,
        instead of reading all data in one partition batch.

        Usage::

            class MyConnector(LakeflowConnect, SupportsPartition):
                ...
        """

        @abstractmethod
        def get_partitions(
            self,
            table_name: str,
            table_options: dict[str, str],
        ) -> Sequence[dict]:
            """Return partition descriptors for reading data.

            Each returned dict is passed to :meth:`read_partition` on an executor.

            Args:
                table_name: The name of the table.
                table_options: A dictionary of options for accessing the table.
            Returns:
                A sequence of partition descriptor dicts. Each dict must be
                JSON-serialisable (primitive types only).
            """

        @abstractmethod
        def read_partition(
            self, table_name: str, partition: dict, table_options: dict[str, str]
        ) -> Iterator[dict]:
            """Read records for a single partition.

            This method runs on Spark executors and must be self-contained.

            Args:
                table_name: The name of the table.
                partition: One of the partition dicts returned by
                    :meth:`get_partitions`.
                table_options: A dictionary of options for accessing the table.
            Returns:
                An iterator of JSON-compatible record dictionaries or PyArrow
                RecordBatch objects for Spark's direct-Arrow reader path.
            """


    class SupportsPartitionedStream(SupportsPartition):
        """Mixin for connectors that support partitioned streaming reads.

        Extends :class:`SupportsPartition` with offset awareness for streaming
        micro-batches. A connector implementing this mixin automatically supports
        both partitioned batch reads (via the inherited interface) and partitioned
        streaming reads.

        Usage::

            class MyConnector(LakeflowConnect, SupportsPartitionedStream):
                ...
        """

        def is_partitioned(self, table_name: str) -> bool:
            """Return whether the given table supports partitioned streaming.

            The default returns True. Override to return False for tables that
            should fall back to simpleStreamReader.

            Args:
                table_name: The name of the table.
                table_options: A dictionary of options for accessing the table.
            """
            return True

        @abstractmethod
        def latest_offset(
            self,
            table_name: str,
            table_options: dict[str, str],
            start_offset: dict | None = None,
        ) -> dict:
            """Return the most recent offset available for the table.

            Called by Spark on every micro-batch to discover new data.

            Micro-batch sizing (by row count, time window, etc.) is entirely the
            connector's responsibility — use table_options (e.g. ``window_days``,
            ``max_records_per_batch``) to control it.  The framework always
            requests "all available" and does not pass an admission-control
            hint here.

            Args:
                table_name: The name of the table.
                table_options: A dictionary of options for accessing the table.
                start_offset: The current committed offset.  ``{}`` on the very
                    first call (from ``initialOffset``), then the last returned
                    end_offset on each subsequent call.
            Returns:
                A dict whose keys and values are primitive types (str, int, bool).
            """

        @abstractmethod
        def get_partitions(
            self,
            table_name: str,
            table_options: dict[str, str],
            start_offset: dict | None = None,
            end_offset: dict | None = None,
        ) -> Sequence[dict]:
            """Return partition descriptors for reading data.

            Each returned dict is passed to :meth:`read_partition` on an executor.

            For batch reads, ``start_offset`` and ``end_offset`` are both None —
            return partitions covering the entire table.

            For streaming micro-batches, they delimit the offset range — return
            partitions covering that range, or an empty sequence when
            ``start_offset == end_offset``.

            Args:
                table_name: The name of the table.
                table_options: A dictionary of options for accessing the table.
                start_offset: The start offset (exclusive), or None for batch.
                end_offset: The end offset (inclusive), or None for batch.
            Returns:
                A sequence of partition descriptor dicts. Each dict must be
                JSON-serialisable (primitive types only).
            """


    ########################################################
    # src/databricks/labs/community_connector/interface/supports_namespaces.py
    ########################################################

    class SupportsNamespaces(ABC):
        """Mixin for connectors whose tables live under hierarchical namespaces.

        A namespace is a path of zero or more string segments (e.g. ``["org",
        "repo"]`` for GitHub, ``["tenant", "project"]`` for Azure DevOps).
        Connectors with a flat catalog do not need this mixin — the framework
        falls back to :meth:`LakeflowConnect.list_tables` and reports each table
        with an empty namespace.

        Output ordering on the ``_community_namespaces`` and ``_community_tables``
        Spark virtual tables is normalized by the framework via ``sorted(...)``,
        so connector implementations of :meth:`list_namespaces` and
        :meth:`list_tables_in_namespace` are free to return their results in
        any order (including from a :class:`set` or generator).

        Must be used together with :class:`LakeflowConnect`.

        Usage::

            class MyConnector(LakeflowConnect, SupportsNamespaces):
                ...
        """

        @abstractmethod
        def list_namespaces(
            self,
            prefix: list[str] | None = None,
        ) -> list[list[str]]:
            """Return the immediate child namespaces under ``prefix``.

            This method returns one level of *namespace* children only — it
            never returns tables. A namespace can hold tables and child
            namespaces independently; callers must always call
            :meth:`list_tables_in_namespace` for every namespace they care
            about, regardless of whether :meth:`list_namespaces` returned
            children for it. An empty return value just means there are no
            further child namespaces under ``prefix``.

            Walk the full tree by recursing on each returned child.

            Args:
                prefix: A namespace path under which to list children. ``None`` or
                    an empty list lists the root-level namespaces.
            Returns:
                A list of full namespace paths (each path includes the prefix).
            """

        @abstractmethod
        def list_tables_in_namespace(
            self,
            namespace: list[str],
        ) -> list[str]:
            """Return the table names that live directly under ``namespace``.

            Callers that want every table across the whole catalog walk the
            namespace tree via :meth:`list_namespaces` and call this method
            once per leaf — there is no "list everything" shortcut.

            Args:
                namespace: The namespace path. An empty list ``[]`` selects
                    root-level tables (those that live outside any namespace).
            Returns:
                A list of table names. The full ``(namespace, table_name)``
                row exposed on ``_community_tables`` is reconstructed by the
                framework from the namespace the caller already supplied, so
                the connector does not need to echo it back.
            """


    ########################################################
    # src/databricks/labs/community_connector/sources/mailchimp/mailchimp_schemas.py
    ########################################################

    RETRIABLE_STATUS_CODES = {429, 500, 503}
    MAX_RETRIES = 5
    INITIAL_BACKOFF = 1.0  # seconds; doubled after each retry

    # Default table-option values.
    DEFAULT_MAX_RECORDS_PER_BATCH = 200
    DEFAULT_WINDOW_SECONDS = 86400  # 1 day
    DEFAULT_PAGE_COUNT = 1000  # Mailchimp max page size

    # Fields whose dynamic key set is serialized to a JSON string on read.
    JSON_STRING_FIELDS = {
        "campaigns": [],
        "reports": [],
        "lists": [],
        "members": ["merge_fields", "interests"],
    }


    # --------------------------------------------------------------------------
    # Reusable nested structs
    # --------------------------------------------------------------------------

    _RECIPIENTS = StructType(
        [
            StructField("list_id", StringType(), True),
            StructField("list_is_active", BooleanType(), True),
            StructField("list_name", StringType(), True),
            StructField("segment_text", StringType(), True),
            StructField("recipient_count", LongType(), True),
        ]
    )

    _SETTINGS = StructType(
        [
            StructField("subject_line", StringType(), True),
            StructField("preview_text", StringType(), True),
            StructField("title", StringType(), True),
            StructField("from_name", StringType(), True),
            StructField("reply_to", StringType(), True),
            StructField("use_conversation", BooleanType(), True),
            StructField("to_name", StringType(), True),
            StructField("folder_id", StringType(), True),
            StructField("authenticate", BooleanType(), True),
            StructField("auto_footer", BooleanType(), True),
            StructField("inline_css", BooleanType(), True),
            StructField("auto_tweet", BooleanType(), True),
            StructField("fb_comments", BooleanType(), True),
            StructField("template_id", LongType(), True),
            StructField("drag_and_drop", BooleanType(), True),
        ]
    )

    _TRACKING = StructType(
        [
            StructField("opens", BooleanType(), True),
            StructField("html_clicks", BooleanType(), True),
            StructField("text_clicks", BooleanType(), True),
            StructField("goal_tracking", BooleanType(), True),
            StructField("ecomm360", BooleanType(), True),
            StructField("google_analytics", StringType(), True),
            StructField("clicktale", StringType(), True),
        ]
    )

    _REPORT_SUMMARY = StructType(
        [
            StructField("opens", LongType(), True),
            StructField("unique_opens", LongType(), True),
            StructField("open_rate", DoubleType(), True),
            StructField("clicks", LongType(), True),
            StructField("subscriber_clicks", LongType(), True),
            StructField("click_rate", DoubleType(), True),
            StructField(
                "ecommerce",
                StructType(
                    [
                        StructField("total_orders", LongType(), True),
                        StructField("total_spent", DoubleType(), True),
                        StructField("total_revenue", DoubleType(), True),
                    ]
                ),
                True,
            ),
        ]
    )

    _DELIVERY_STATUS = StructType(
        [
            StructField("enabled", BooleanType(), True),
            StructField("can_cancel", BooleanType(), True),
            StructField("status", StringType(), True),
            StructField("emails_sent", LongType(), True),
            StructField("emails_canceled", LongType(), True),
        ]
    )

    # --- report-specific nested structs ---

    _BOUNCES = StructType(
        [
            StructField("hard_bounces", LongType(), True),
            StructField("soft_bounces", LongType(), True),
            StructField("syntax_errors", LongType(), True),
        ]
    )

    _FORWARDS = StructType(
        [
            StructField("forwards_count", LongType(), True),
            StructField("forwards_opens", LongType(), True),
        ]
    )

    _OPENS = StructType(
        [
            StructField("opens_total", LongType(), True),
            StructField("unique_opens", LongType(), True),
            StructField("open_rate", DoubleType(), True),
            StructField("last_open", StringType(), True),
        ]
    )

    _CLICKS = StructType(
        [
            StructField("clicks_total", LongType(), True),
            StructField("unique_clicks", LongType(), True),
            StructField("unique_subscriber_clicks", LongType(), True),
            StructField("click_rate", DoubleType(), True),
            StructField("last_click", StringType(), True),
        ]
    )

    _FACEBOOK_LIKES = StructType(
        [
            StructField("recipient_likes", LongType(), True),
            StructField("unique_likes", LongType(), True),
            StructField("facebook_likes", LongType(), True),
        ]
    )

    _LIST_STATS = StructType(
        [
            StructField("sub_rate", DoubleType(), True),
            StructField("unsub_rate", DoubleType(), True),
            StructField("open_rate", DoubleType(), True),
            StructField("click_rate", DoubleType(), True),
        ]
    )

    _ECOMMERCE = StructType(
        [
            StructField("total_orders", LongType(), True),
            StructField("total_spent", DoubleType(), True),
            StructField("total_revenue", DoubleType(), True),
        ]
    )

    # --- list-specific nested structs ---

    _CONTACT = StructType(
        [
            StructField("company", StringType(), True),
            StructField("address1", StringType(), True),
            StructField("address2", StringType(), True),
            StructField("city", StringType(), True),
            StructField("state", StringType(), True),
            StructField("zip", StringType(), True),
            StructField("country", StringType(), True),
            StructField("phone", StringType(), True),
        ]
    )

    _CAMPAIGN_DEFAULTS = StructType(
        [
            StructField("from_name", StringType(), True),
            StructField("from_email", StringType(), True),
            StructField("subject", StringType(), True),
            StructField("language", StringType(), True),
        ]
    )

    _LIST_STATS_FULL = StructType(
        [
            StructField("member_count", LongType(), True),
            StructField("unsubscribe_count", LongType(), True),
            StructField("cleaned_count", LongType(), True),
            StructField("member_count_since_send", LongType(), True),
            StructField("unsubscribe_count_since_send", LongType(), True),
            StructField("cleaned_count_since_send", LongType(), True),
            StructField("campaign_count", LongType(), True),
            StructField("campaign_last_sent", StringType(), True),
            StructField("merge_field_count", LongType(), True),
            StructField("avg_sub_rate", DoubleType(), True),
            StructField("avg_unsub_rate", DoubleType(), True),
            StructField("target_sub_rate", DoubleType(), True),
            StructField("open_rate", DoubleType(), True),
            StructField("click_rate", DoubleType(), True),
            StructField("last_sub_date", StringType(), True),
            StructField("last_unsub_date", StringType(), True),
        ]
    )

    # --- member-specific nested structs ---

    _MEMBER_STATS = StructType(
        [
            StructField("avg_open_rate", DoubleType(), True),
            StructField("avg_click_rate", DoubleType(), True),
            StructField(
                "ecommerce_data",
                StructType(
                    [
                        StructField("total_revenue", DoubleType(), True),
                        StructField("number_of_orders", LongType(), True),
                        StructField("currency_code", StringType(), True),
                    ]
                ),
                True,
            ),
        ]
    )

    _LOCATION = StructType(
        [
            StructField("latitude", DoubleType(), True),
            StructField("longitude", DoubleType(), True),
            StructField("gmtoff", LongType(), True),
            StructField("dstoff", LongType(), True),
            StructField("country_code", StringType(), True),
            StructField("timezone", StringType(), True),
        ]
    )

    _TAGS = ArrayType(
        StructType(
            [
                StructField("id", LongType(), True),
                StructField("name", StringType(), True),
            ]
        )
    )


    # --------------------------------------------------------------------------
    # Top-level table schemas
    # --------------------------------------------------------------------------

    CAMPAIGNS_SCHEMA = StructType(
        [
            StructField("id", StringType(), False),
            StructField("web_id", LongType(), True),
            StructField("type", StringType(), True),
            StructField("create_time", StringType(), True),
            StructField("send_time", StringType(), True),
            StructField("status", StringType(), True),
            StructField("emails_sent", LongType(), True),
            StructField("archive_url", StringType(), True),
            StructField("content_type", StringType(), True),
            StructField("recipients", _RECIPIENTS, True),
            StructField("settings", _SETTINGS, True),
            StructField("tracking", _TRACKING, True),
            StructField("report_summary", _REPORT_SUMMARY, True),
            StructField("delivery_status", _DELIVERY_STATUS, True),
        ]
    )

    REPORTS_SCHEMA = StructType(
        [
            StructField("id", StringType(), False),
            StructField("campaign_title", StringType(), True),
            StructField("type", StringType(), True),
            StructField("list_id", StringType(), True),
            StructField("list_is_active", BooleanType(), True),
            StructField("list_name", StringType(), True),
            StructField("subject_line", StringType(), True),
            StructField("preview_text", StringType(), True),
            StructField("emails_sent", LongType(), True),
            StructField("abuse_reports", LongType(), True),
            StructField("unsubscribed", LongType(), True),
            StructField("send_time", StringType(), True),
            StructField("bounces", _BOUNCES, True),
            StructField("forwards", _FORWARDS, True),
            StructField("opens", _OPENS, True),
            StructField("clicks", _CLICKS, True),
            StructField("facebook_likes", _FACEBOOK_LIKES, True),
            StructField("list_stats", _LIST_STATS, True),
            StructField("ecommerce", _ECOMMERCE, True),
            StructField("delivery_status", _DELIVERY_STATUS, True),
        ]
    )

    LISTS_SCHEMA = StructType(
        [
            StructField("id", StringType(), False),
            StructField("web_id", LongType(), True),
            StructField("name", StringType(), True),
            StructField("contact", _CONTACT, True),
            StructField("permission_reminder", StringType(), True),
            StructField("use_archive_bar", BooleanType(), True),
            StructField("campaign_defaults", _CAMPAIGN_DEFAULTS, True),
            StructField("notify_on_subscribe", StringType(), True),
            StructField("notify_on_unsubscribe", StringType(), True),
            StructField("date_created", StringType(), True),
            StructField("list_rating", LongType(), True),
            StructField("email_type_option", BooleanType(), True),
            StructField("subscribe_url_short", StringType(), True),
            StructField("subscribe_url_long", StringType(), True),
            StructField("beamer_address", StringType(), True),
            StructField("visibility", StringType(), True),
            StructField("double_optin", BooleanType(), True),
            StructField("marketing_permissions", BooleanType(), True),
            StructField("stats", _LIST_STATS_FULL, True),
        ]
    )

    MEMBERS_SCHEMA = StructType(
        [
            StructField("id", StringType(), False),
            StructField("email_address", StringType(), True),
            StructField("unique_email_id", StringType(), True),
            StructField("contact_id", StringType(), True),
            StructField("full_name", StringType(), True),
            StructField("web_id", LongType(), True),
            StructField("email_type", StringType(), True),
            StructField("status", StringType(), True),
            # Dynamic key set per audience -> raw JSON string (see module docstring).
            StructField("merge_fields", StringType(), True),
            StructField("interests", StringType(), True),
            StructField("stats", _MEMBER_STATS, True),
            StructField("ip_signup", StringType(), True),
            StructField("timestamp_signup", StringType(), True),
            StructField("ip_opt", StringType(), True),
            StructField("timestamp_opt", StringType(), True),
            StructField("member_rating", LongType(), True),
            StructField("last_changed", StringType(), True),
            StructField("language", StringType(), True),
            StructField("vip", BooleanType(), True),
            StructField("email_client", StringType(), True),
            StructField("location", _LOCATION, True),
            StructField("tags_count", LongType(), True),
            StructField("tags", _TAGS, True),
            StructField("list_id", StringType(), False),
        ]
    )

    TABLE_SCHEMAS = {
        "campaigns": CAMPAIGNS_SCHEMA,
        "reports": REPORTS_SCHEMA,
        "lists": LISTS_SCHEMA,
        "members": MEMBERS_SCHEMA,
    }


    # --------------------------------------------------------------------------
    # Per-table configuration driving reads / metadata
    # --------------------------------------------------------------------------
    #
    # resource_key : key wrapping the record array in the list response envelope.
    # path         : list endpoint path (relative to base_url). ``members`` is
    #                nested and templated per list_id at read time.
    # cursor_field : incremental cursor column.
    # since_param  : query param for the window lower bound (exclusive / >; the
    #                connector applies a small lookback so the boundary row is kept).
    # before_param : query param for the window upper bound (<).
    # primary_keys : effective PK for the unioned output table.
    # supports_sort: whether the list endpoint honours sort_field/sort_dir. Only
    #                campaigns and members do; reports/lists do not.
    TABLE_CONFIG = {
        "campaigns": {
            "resource_key": "campaigns",
            "path": "/campaigns",
            "cursor_field": "create_time",
            "since_param": "since_create_time",
            "before_param": "before_create_time",
            "primary_keys": ["id"],
            "supports_sort": True,
            "nested": False,
        },
        "reports": {
            "resource_key": "reports",
            "path": "/reports",
            "cursor_field": "send_time",
            "since_param": "since_send_time",
            "before_param": "before_send_time",
            "primary_keys": ["id"],
            "supports_sort": False,
            "nested": False,
        },
        "lists": {
            "resource_key": "lists",
            "path": "/lists",
            "cursor_field": "date_created",
            "since_param": "since_date_created",
            "before_param": "before_date_created",
            "primary_keys": ["id"],
            "supports_sort": False,
            "nested": False,
        },
        "members": {
            "resource_key": "members",
            "path": "/lists/{list_id}/members",
            "cursor_field": "last_changed",
            "since_param": "since_last_changed",
            "before_param": "before_last_changed",
            "primary_keys": ["list_id", "id"],
            "supports_sort": True,
            "nested": True,
        },
    }


    ########################################################
    # src/databricks/labs/community_connector/sources/mailchimp/mailchimp.py
    ########################################################

    _USERNAME = "anystring"  # Mailchimp ignores the Basic-auth username.

    # Mailchimp's ``since_*`` filters are EXCLUSIVE (strictly greater than), so a
    # query seeded with the oldest cursor drops that boundary row. Subtract a small
    # lookback from the queried ``since`` so the boundary is included; CDC upsert
    # dedupes any re-fetched overlap. Overridable per table via ``lookback_seconds``.
    DEFAULT_LOOKBACK_SECONDS = 1


    class MailchimpLakeflowConnect(LakeflowConnect):
        """LakeflowConnect implementation for the Mailchimp Marketing API."""

        def __init__(self, options: dict) -> None:
            super().__init__(options)
            api_key = options.get("api_key")
            if not api_key:
                raise ValueError("Mailchimp connector requires an 'api_key' option.")
            self._api_key = api_key

            # Derive the data center from the key suffix (e.g. "...-us21" -> "us21").
            # Fall back to the documented 'server_prefix' option for legacy keys
            # with no suffix.
            dc: Optional[str] = None
            if "-" in api_key:
                dc = api_key.rsplit("-", 1)[1] or None
            if not dc:
                dc = options.get("server_prefix")
            if not dc:
                raise ValueError(
                    "Could not determine the Mailchimp data center. The API key has "
                    "no '-<dc>' suffix; supply a 'server_prefix' option, e.g. 'us21'."
                )
            # Validate the data center so it cannot inject a different host/path
            # into the base URL (it is only ever a short region code like 'us21').
            if not re.fullmatch(r"[a-z]{2}\d+", dc):
                raise ValueError(
                    f"Invalid Mailchimp data center '{dc}'; expected a region code "
                    "like 'us21'."
                )
            self._base_url = f"https://{dc}.api.mailchimp.com/3.0"

            # Freeze the window upper bound at init time so a single
            # Trigger.AvailableNow run terminates instead of chasing new data.
            # Mailchimp timestamps are ISO 8601 with a "+00:00" offset.
            self._init_ts = datetime.now(timezone.utc).isoformat()

        # ---- picklable auth helpers -----------------------------------------

        def _auth(self) -> Tuple[str, str]:
            """Build the HTTP Basic auth tuple per request (kept off ``self``)."""
            return (_USERNAME, self._api_key)

        def _request_with_retry(self, path: str, params: Optional[dict] = None):
            """GET ``path`` with exponential backoff on 429/500/503.

            429 is Mailchimp's rate-limit signal (max 10 concurrent connections
            per key); 500/503 are transient server errors. Transient transport
            errors (``ConnectionError``/``Timeout``) are retried on the same
            backoff so an executor-side read survives a blip; the last exception
            is re-raised if every attempt fails.
            """
            url = f"{self._base_url}{path}"
            backoff = INITIAL_BACKOFF
            resp = None
            for attempt in range(MAX_RETRIES):
                try:
                    resp = requests.get(
                        url, params=params or {}, auth=self._auth(), timeout=60
                    )
                except (requests.ConnectionError, requests.Timeout):
                    if attempt < MAX_RETRIES - 1:
                        time.sleep(backoff)
                        backoff *= 2
                        continue
                    raise
                if resp.status_code not in RETRIABLE_STATUS_CODES:
                    return resp
                if attempt < MAX_RETRIES - 1:
                    time.sleep(backoff)
                    backoff *= 2
            return resp

        # ---- interface methods ----------------------------------------------

        def list_tables(self) -> list[str]:
            """The four static top-level tables this connector supports."""
            return ["campaigns", "reports", "lists", "members"]

        def get_table_schema(
            self, table_name: str, table_options: Dict[str, str]
        ) -> StructType:
            self._validate_table(table_name)
            return TABLE_SCHEMAS[table_name]

        def read_table_metadata(
            self, table_name: str, table_options: Dict[str, str]
        ) -> dict:
            self._validate_table(table_name)
            cfg = TABLE_CONFIG[table_name]
            return {
                "primary_keys": list(cfg["primary_keys"]),
                "cursor_field": cfg["cursor_field"],
                "ingestion_type": "cdc",
            }

        def read_table(
            self, table_name: str, start_offset: dict, table_options: Dict[str, str]
        ) -> Tuple[Iterator[dict], dict]:
            self._validate_table(table_name)
            table_options = table_options or {}
            cfg = TABLE_CONFIG[table_name]
            if cfg["nested"]:
                return self._read_members_window(start_offset, table_options)
            return self._read_window(table_name, start_offset, table_options)

        # ---- validation ------------------------------------------------------

        def _validate_table(self, table_name: str) -> None:
            if table_name not in TABLE_CONFIG:
                raise ValueError(
                    f"Table '{table_name}' is not supported. "
                    f"Supported tables: {self.list_tables()}"
                )

        # ---- pagination ------------------------------------------------------

        def _fetch_page(
            self, path: str, resource_key: str, params: dict
        ) -> Tuple[List[dict], int]:
            """One list GET. Returns (records, total_items)."""
            resp = self._request_with_retry(path, params)
            if resp.status_code != 200:
                # Truncate the body so a verbose error can't dump large/sensitive
                # payloads into pipeline logs. Mailchimp errors are short RFC 7807
                # problem-details, so the head is enough to diagnose.
                detail = (resp.text or "")[:500]
                raise RuntimeError(
                    f"Mailchimp API error for {path}: {resp.status_code} {detail}"
                )
            body = resp.json()
            records = body.get(resource_key) or []
            total = int(body.get("total_items", 0) or 0)
            return records, total

        def _paginate(
            self,
            path: str,
            resource_key: str,
            base_params: dict,
            max_records: Optional[int] = None,
        ) -> Tuple[List[dict], bool]:
            """Page through a list endpoint with offset/count.

            Stops on a short page (fewer than ``count`` rows), when
            ``offset >= total_items``, or when ``max_records`` is reached.
            Short-page detection is the primary terminator so the loop ends even
            when the source does not populate ``total_items``.

            Returns ``(records, exhausted)`` where ``exhausted`` is True when the
            endpoint was drained for the current window (short page / total
            reached) and False when the loop bailed on the ``max_records`` cap.
            The caller uses that flag to decide whether it is safe to advance the
            cursor to ``window_end`` (drained) or must resume mid-window.
            """
            count = int(base_params.get("count", DEFAULT_PAGE_COUNT))
            records: List[dict] = []
            offset = 0
            exhausted = True
            while True:
                params = dict(base_params)
                params["count"] = count
                params["offset"] = offset
                batch, total = self._fetch_page(path, resource_key, params)
                records.extend(batch)

                if len(batch) < count:
                    break
                offset += count
                if 0 < total <= offset:
                    break
                if max_records is not None and len(records) >= max_records:
                    # Bailed on the cap with a full last page: more rows may remain
                    # in this window.
                    exhausted = False
                    break
            return records, exhausted

        # ---- incremental window reads ---------------------------------------

        def _resolve_since(
            self, table_name: str, start_offset: dict, table_options: dict, cfg: dict
        ) -> Optional[str]:
            """Resolve the window lower bound.

            Order: prior offset cursor -> user-supplied ``start_timestamp`` option
            -> auto-discover the oldest cursor value from the source.
            """
            since = start_offset.get("cursor") if start_offset else None
            if not since:
                since = table_options.get("start_timestamp")
            if not since:
                since = self._peek_oldest_cursor(table_name, cfg)
            return since

        def _peek_oldest_cursor(self, table_name: str, cfg: dict) -> Optional[str]:
            """Discover the oldest cursor value with a lightweight probe.

            For endpoints that honour sort (campaigns, members) request a single
            ascending record. For the rest (reports, lists), which are small in
            cardinality, fetch the first full page and take the minimum cursor.
            """
            cursor_field = cfg["cursor_field"]
            if cfg["nested"]:
                # members: probe EVERY audience and take the global minimum cursor.
                # All members share one cursor window, so seeding ``since`` from the
                # first audience's oldest member would permanently skip any member
                # in another audience with an older ``last_changed`` (the exclusive
                # ``since_*`` filter excludes it on every subsequent window).
                lists, _ = self._paginate("/lists", "lists", {"count": DEFAULT_PAGE_COUNT})
                oldest: Optional[str] = None
                for lst in lists:
                    list_id = lst.get("id")
                    if not list_id:
                        continue
                    cursor = self._peek_from_path(
                        cfg["path"].format(list_id=list_id),
                        cfg["resource_key"],
                        cursor_field,
                        supports_sort=cfg["supports_sort"],
                    )
                    if cursor and (oldest is None or self._to_dt(cursor) < self._to_dt(oldest)):
                        oldest = cursor
                return oldest
            return self._peek_from_path(
                cfg["path"], cfg["resource_key"], cursor_field, cfg["supports_sort"]
            )

        def _peek_from_path(
            self, path: str, resource_key: str, cursor_field: str, supports_sort: bool
        ) -> Optional[str]:
            if supports_sort:
                params = {
                    "count": 1,
                    "offset": 0,
                    "sort_field": cursor_field,
                    "sort_dir": "ASC",
                }
                batch, _ = self._fetch_page(path, resource_key, params)
                if batch:
                    return batch[0].get(cursor_field)
                return None
            # No sort support: drain all pages and take the global min cursor.
            # ``_paginate`` enumerates every page when ``max_records`` is None, so a
            # global-oldest row on a later page is not missed. This probe runs only
            # on first-run discovery, so the full enumeration is a one-time cost.
            batch, _ = self._paginate(path, resource_key, {"count": DEFAULT_PAGE_COUNT})
            cursors = [r.get(cursor_field) for r in batch if r.get(cursor_field)]
            return min(cursors) if cursors else None

        @staticmethod
        def _to_dt(ts: str) -> datetime:
            """Parse an ISO 8601 cursor to an aware UTC datetime.

            Mailchimp emits ``+00:00`` offsets, but a user-supplied
            ``start_timestamp`` (or a re-fetched cursor) may use a ``Z`` suffix.
            Comparing those as raw strings is wrong (``'...Z'`` sorts after
            ``'...+00:00'`` lexically even for the same instant), so every cursor
            comparison and arithmetic goes through this parser instead.
            """
            normalized = ts.replace("Z", "+00:00") if ts.endswith("Z") else ts
            dt = datetime.fromisoformat(normalized)
            if dt.tzinfo is None:
                dt = dt.replace(tzinfo=timezone.utc)
            return dt

        def _window_end(self, since: str, window_seconds: int) -> str:
            """Compute the window upper bound, capped at ``_init_ts``."""
            end_dt = self._to_dt(since) + timedelta(seconds=window_seconds)
            return min(end_dt, self._to_dt(self._init_ts)).isoformat()

        def _apply_lookback(self, since: str, lookback_seconds: int) -> str:
            """Subtract a lookback from an ISO cursor for the (exclusive) API filter.

            Mailchimp's ``since_*`` filter is strictly greater-than, so querying at
            exactly the boundary cursor drops that row. Shifting ``since`` back by a
            few seconds includes it; CDC upsert dedupes the re-fetched overlap. The
            stored offset keeps the raw cursor — only the queried value is shifted.
            """
            if lookback_seconds <= 0:
                return since
            return (self._to_dt(since) - timedelta(seconds=lookback_seconds)).isoformat()

        def _read_window(
            self, table_name: str, start_offset: dict, table_options: dict
        ) -> Tuple[Iterator[dict], dict]:
            """Sliding-window incremental read for a single (non-nested) resource."""
            cfg = TABLE_CONFIG[table_name]
            cursor_field = cfg["cursor_field"]

            since = self._resolve_since(table_name, start_offset, table_options, cfg)
            if not since:
                raise ValueError(
                    f"Cannot determine a starting cursor for '{table_name}'. "
                    f"Provide 'start_timestamp' in table_options."
                )
            # Already caught up to init time — nothing new this run.
            if self._to_dt(since) >= self._to_dt(self._init_ts):
                return iter([]), start_offset if start_offset else {}

            window_seconds = int(
                table_options.get("window_seconds", DEFAULT_WINDOW_SECONDS)
            )
            max_records = int(
                table_options.get("max_records_per_batch", DEFAULT_MAX_RECORDS_PER_BATCH)
            )
            lookback_seconds = int(
                table_options.get("lookback_seconds", DEFAULT_LOOKBACK_SECONDS)
            )
            window_end = self._window_end(since, window_seconds)

            base_params = {
                "count": DEFAULT_PAGE_COUNT,
                # since_* is exclusive: shift back so the boundary row is included.
                cfg["since_param"]: self._apply_lookback(since, lookback_seconds),
                cfg["before_param"]: window_end,
            }
            # The ``max_records`` mid-window cap is only safe on SORTED endpoints,
            # where rows arrive in ascending cursor order and the max cursor seen is
            # a valid resume point. UNSORTED endpoints (reports, lists) return the
            # window in server-default order, so a partial fetch cannot resume
            # without risking dropped rows; drain the whole window instead (these
            # tables are low-cardinality and the window bounds the volume).
            if cfg["supports_sort"]:
                base_params["sort_field"] = cursor_field
                base_params["sort_dir"] = "ASC"
                page_cap: Optional[int] = max_records
            else:
                page_cap = None

            records, window_drained = self._paginate(
                cfg["path"], cfg["resource_key"], base_params, page_cap
            )

            # Same-second cursor cluster larger than the cap: every capped row shares
            # one cursor value, so the resume point (`_max_cursor`) would equal
            # `since` and the next call re-fetches the same first page forever —
            # dropping everything past it. When the cap trips but the resume cursor
            # can't advance past the window start, re-drain the whole window uncapped;
            # ``window_seconds`` bounds the volume so peak memory stays bounded.
            # (Only reachable on sorted endpoints; the unsorted path never sets a cap.)
            if not window_drained and page_cap is not None:
                resume = self._max_cursor(records, cursor_field, window_end)
                if self._to_dt(resume) <= self._to_dt(since):
                    records, window_drained = self._paginate(
                        cfg["path"], cfg["resource_key"], base_params, None
                    )

            if window_drained:
                # Endpoint fully drained for this window: advance cleanly to the end.
                end_offset = {"cursor": window_end}
            else:
                # Cap hit mid-window on a sorted endpoint: resume from the max cursor
                # seen (everything below it is already fetched). CDC upsert tolerates
                # the re-fetch of the window head on the next call.
                end_offset = {"cursor": self._max_cursor(records, cursor_field, window_end)}

            if start_offset and start_offset == end_offset:
                return iter([]), start_offset

            return iter(self._project(records, table_name)), end_offset

        def _read_members_window(
            self, start_offset: dict, table_options: dict
        ) -> Tuple[Iterator[dict], dict]:
            """Sliding-window incremental read for the nested ``members`` table.

            The whole members population is treated under one cursor window. We
            enumerate every audience, apply the ``since``/``before`` window per
            list, and yield the members **lazily, one audience at a time**, then
            advance the cursor to the window end. Yielding lazily bounds peak
            memory to a single audience's members instead of the union of every
            audience. The window is drained completely (no client-side truncation)
            so no record with a cursor below ``window_end`` is skipped on the next
            call; ``max_records_per_batch`` is therefore best-effort here (windows
            are the sizing knob). Keep ``window_seconds`` small on large accounts.
            """
            cfg = TABLE_CONFIG["members"]
            cursor_field = cfg["cursor_field"]

            since = self._resolve_since("members", start_offset, table_options, cfg)
            if not since:
                raise ValueError(
                    "Cannot determine a starting cursor for 'members'. "
                    "Provide 'start_timestamp' in table_options."
                )
            if self._to_dt(since) >= self._to_dt(self._init_ts):
                return iter([]), start_offset if start_offset else {}

            window_seconds = int(
                table_options.get("window_seconds", DEFAULT_WINDOW_SECONDS)
            )
            lookback_seconds = int(
                table_options.get("lookback_seconds", DEFAULT_LOOKBACK_SECONDS)
            )
            window_end = self._window_end(since, window_seconds)
            api_since = self._apply_lookback(since, lookback_seconds)

            # Enumerate every audience, then fan out members per list within the
            # same window.
            lists, _ = self._paginate("/lists", "lists", {"count": DEFAULT_PAGE_COUNT})

            # Window is drained by construction — advance the cursor to its end.
            end_offset = {"cursor": window_end}
            if start_offset and start_offset == end_offset:
                return iter([]), start_offset

            def _iter_members() -> Iterator[dict]:
                """Fan out per audience, yielding lazily to bound peak memory."""
                for lst in lists:
                    list_id = lst.get("id")
                    if not list_id:
                        continue
                    base_params = {
                        "count": DEFAULT_PAGE_COUNT,
                        # since_* is exclusive: shift back to include the boundary.
                        cfg["since_param"]: api_since,
                        cfg["before_param"]: window_end,
                        "sort_field": cursor_field,
                        "sort_dir": "ASC",
                    }
                    path = cfg["path"].format(list_id=list_id)
                    members, _ = self._paginate(path, cfg["resource_key"], base_params)
                    for m in members:
                        # Preserve provenance even if the payload omits list_id.
                        if not m.get("list_id"):
                            m["list_id"] = list_id
                    yield from self._project(members, "members")

            return _iter_members(), end_offset

        # ---- record shaping --------------------------------------------------

        @staticmethod
        def _max_cursor(records: List[dict], cursor_field: str, fallback: str) -> str:
            values = [r.get(cursor_field) for r in records if r.get(cursor_field)]
            return max(values) if values else fallback

        @staticmethod
        def _project(records: List[dict], table_name: str) -> List[dict]:
            """Serialize dynamic-key fields to JSON strings.

            This is the one place the connector reshapes a value: ``merge_fields``
            and ``interests`` have per-audience key sets that cannot map to a fixed
            StructType, so they are stored as raw-JSON string columns (see
            ``mailchimp_schemas``). All other fields are returned as parsed by the
            API for the framework to coerce.
            """
            json_fields = JSON_STRING_FIELDS.get(table_name, [])
            if not json_fields:
                return records
            for rec in records:
                for fld in json_fields:
                    if fld in rec and rec[fld] is not None and not isinstance(rec[fld], str):
                        rec[fld] = json.dumps(rec[fld], ensure_ascii=False)
            return records


    ########################################################
    # src/databricks/labs/community_connector/sparkpds/lakeflow_datasource.py
    ########################################################

    LakeflowConnectImpl = MailchimpLakeflowConnect
    # Constant option or column names
    METADATA_TABLE = "_community_table_metadata"
    NAMESPACES_TABLE = "_community_namespaces"
    TABLES_TABLE = "_community_tables"
    VIRTUAL_TABLES = (METADATA_TABLE, NAMESPACES_TABLE, TABLES_TABLE)
    TABLE_NAME = "tableName"
    TABLE_NAME_LIST = "tableNameList"
    TABLE_CONFIGS = "tableConfigs"
    IS_DELETE_FLOW = "isDeleteFlow"
    NAMESPACE_PREFIX = "namespacePrefix"
    NAMESPACE = "namespace"


    def _decode_list_of_str_option(option_name: str, value: str | None) -> list[str] | None:
        """Decode and validate a JSON-encoded ``list[str]`` Spark option.

        Returns ``None`` if the option is absent; otherwise the parsed list.
        Raises ``ValueError`` with the offending value if the JSON is malformed
        or the decoded value is not a list of strings.
        """
        if value is None:
            return None
        try:
            decoded = json.loads(value)
        except json.JSONDecodeError as e:
            raise ValueError(
                f"option '{option_name}' must be a JSON-encoded list[str]; "
                f"got non-JSON value: {value!r}"
            ) from e
        if not isinstance(decoded, list) or not all(isinstance(s, str) for s in decoded):
            raise ValueError(
                f"option '{option_name}' must be a JSON-encoded list[str]; "
                f"got: {decoded!r}"
            )
        return decoded


    def _decode_dict_option(option_name: str, value: str | None) -> dict:
        """Decode and validate a JSON-encoded ``dict`` Spark option."""
        if value is None:
            return {}
        try:
            decoded = json.loads(value)
        except json.JSONDecodeError as e:
            raise ValueError(
                f"option '{option_name}' must be a JSON-encoded dict; "
                f"got non-JSON value: {value!r}"
            ) from e
        if not isinstance(decoded, dict):
            raise ValueError(
                f"option '{option_name}' must be a JSON-encoded dict; got: {decoded!r}"
            )
        return decoded


    def _parse_or_passthrough_records(records, schema: StructType):
        """Convert row records while passing PyArrow RecordBatches directly to Spark."""
        iterator = iter(records)
        try:
            first = next(iterator)
        except StopIteration:
            return iter(())

        first_type = type(first)
        if first_type.__name__ == "RecordBatch" and first_type.__module__.startswith("pyarrow."):
            return chain((first,), iterator)

        return chain(
            (parse_value(first, schema),),
            map(lambda value: parse_value(value, schema), iterator),
        )


    # PySpark's DataSource API requires camelCase method names and inherits
    # semantics from the parent class, so per-method docstrings are redundant.
    # pylint: disable=invalid-name,missing-function-docstring
    class LakeflowStreamReader(SimpleDataSourceStreamReader, SupportsTriggerAvailableNow):
        """
        Implements a data source stream reader for Lakeflow Connect.
        Currently, only the simpleStreamReader is implemented, which uses a
        more generic protocol suitable for most data sources that support
        incremental loading.
        """

        def __init__(
            self,
            options: dict[str, str],
            schema: StructType,
            lakeflow_connect: LakeflowConnect,
        ):
            self.options = options
            self.lakeflow_connect = lakeflow_connect
            self.schema = schema

        def initialOffset(self):
            return {}

        def read(self, start: dict) -> (Iterator[tuple], dict):
            is_delete_flow = self.options.get(IS_DELETE_FLOW) == "true"
            # Strip delete flow options before passing to connector
            table_options = {
                k: v for k, v in self.options.items() if k != IS_DELETE_FLOW
            }

            if is_delete_flow:
                records, offset = self.lakeflow_connect.read_table_deletes(
                    self.options[TABLE_NAME], start, table_options
                )
            else:
                records, offset = self.lakeflow_connect.read_table(
                    self.options[TABLE_NAME], start, table_options
                )
            rows = _parse_or_passthrough_records(records, self.schema)
            return rows, offset

        def readBetweenOffsets(self, start: dict, end: dict) -> Iterator[tuple]:
            # TODO: This does not ensure the records returned are identical across repeated calls.
            # For append-only tables, the data source must guarantee that reading from the same
            # start offset will always yield the same set of records.
            # For tables ingested as incremental CDC, it is only necessary that no new changes
            # are missed in the returned records.
            return self.read(start)[0]

        def prepareForTriggerAvailableNow(self) -> None:
            # No need to do anything special here. Everything is handled in the __init__ method.
            pass


    class LakeflowPartitionedStreamReader(DataSourceStreamReader, SupportsTriggerAvailableNow):
        """Proxy that bridges SupportsPartitionedStream to PySpark's DataSourceStreamReader.

        Used when a connector implements the SupportsPartitionedStream mixin to
        support partitioned streaming reads across Spark executors.
        """

        def __init__(
            self,
            options: dict[str, str],
            schema: StructType,
            lakeflow_connect: LakeflowConnect,
        ):
            self.options = options
            self.schema = schema
            self.lakeflow_connect = lakeflow_connect
            self.table_name = options[TABLE_NAME]
            self.table_options = {k: v for k, v in options.items() if k != IS_DELETE_FLOW}

        def initialOffset(self):
            return {}

        def getDefaultReadLimit(self):
            # Admission control is the connector's responsibility (e.g. via
            # window_days, max_records_per_batch), not the engine's.  Always
            # ask the engine for ReadAllAvailable.
            return ReadAllAvailable()

        def latestOffset(self, start: dict, limit) -> dict:
            # We declared ReadAllAvailable via getDefaultReadLimit; the engine
            # must respect it.  Anything else means admission-control expectations
            # we do not support — fail loudly rather than silently ignore.
            if not isinstance(limit, ReadAllAvailable):
                raise ValueError(
                    f"LakeflowPartitionedStreamReader only supports ReadAllAvailable; "
                    f"got {type(limit).__name__}. Micro-batch sizing must be controlled "
                    f"by the connector implementation (table_options), not the engine."
                )
            return self.lakeflow_connect.latest_offset(
                self.table_name, self.table_options, start
            )

        def partitions(self, start: dict, end: dict):
            partition_descs = self.lakeflow_connect.get_partitions(
                self.table_name, self.table_options, start, end
            )
            return [InputPartition(json.dumps(p)) for p in partition_descs]

        def read(self, partition: InputPartition):
            partition_desc = json.loads(partition.value)
            records = self.lakeflow_connect.read_partition(
                self.table_name, partition_desc, self.table_options
            )
            return _parse_or_passthrough_records(records, self.schema)

        def prepareForTriggerAvailableNow(self) -> None:
            # No need to do anything special here. Everything is handled in the __init__ method.
            pass


    class LakeflowBatchReader(DataSourceReader):
        def __init__(
            self,
            options: dict[str, str],
            schema: StructType,
            lakeflow_connect: LakeflowConnect,
        ):
            self.options = options
            self.schema = schema
            self.lakeflow_connect = lakeflow_connect
            self.table_name = options[TABLE_NAME]
            self._supports_partition = isinstance(lakeflow_connect, SupportsPartition)

        def partitions(self):
            if self._supports_partition and self.table_name not in VIRTUAL_TABLES:
                try:
                    partition_descs = self.lakeflow_connect.get_partitions(
                        self.table_name, self.options
                    )
                    return [InputPartition(json.dumps(p)) for p in partition_descs]
                except Exception:
                    self._supports_partition = False
            return [InputPartition(None)]

        def read(self, partition):
            if self.table_name == METADATA_TABLE:
                records = self._read_table_metadata()
            elif self.table_name == NAMESPACES_TABLE:
                records = self._read_namespaces()
            elif self.table_name == TABLES_TABLE:
                records = self._read_tables()
            elif self._supports_partition and partition.value is not None:
                partition_desc = json.loads(partition.value)
                records = self.lakeflow_connect.read_partition(
                    self.table_name, partition_desc, self.options
                )
            else:
                records, _ = self.lakeflow_connect.read_table(self.table_name, None, self.options)
            return _parse_or_passthrough_records(records, self.schema)

        def _read_table_metadata(self):
            table_names = _decode_list_of_str_option(
                TABLE_NAME_LIST, self.options.get(TABLE_NAME_LIST)
            ) or []
            table_configs = _decode_dict_option(
                TABLE_CONFIGS, self.options.get(TABLE_CONFIGS)
            )
            all_records = []
            # Preserve caller-supplied table order — caller controls it.
            for table in table_names:
                metadata = self.lakeflow_connect.read_table_metadata(
                    table, table_configs.get(table, {})
                )
                all_records.append({TABLE_NAME: table, **metadata})
            return all_records

        def _read_namespaces(self):
            # Connectors without SupportsNamespaces are flat — no rows.
            if not isinstance(self.lakeflow_connect, SupportsNamespaces):
                return []
            prefix = _decode_list_of_str_option(
                NAMESPACE_PREFIX, self.options.get(NAMESPACE_PREFIX)
            )
            namespaces = self.lakeflow_connect.list_namespaces(prefix)
            # Sort framework-side for deterministic output regardless of
            # connector iteration order.
            return [{"namespace": ns} for ns in sorted(namespaces)]

        def _read_tables(self):
            namespace_supplied = NAMESPACE in self.options
            if isinstance(self.lakeflow_connect, SupportsNamespaces):
                if not namespace_supplied:
                    raise ValueError(
                        f"option '{NAMESPACE}' is required when reading "
                        f"'{TABLES_TABLE}' against a connector that implements "
                        f"SupportsNamespaces. Pass a JSON-encoded list[str] "
                        f"(use '[]' for root-level tables; walk the tree via "
                        f"'{NAMESPACES_TABLE}' to enumerate every namespace)."
                    )
                namespace = _decode_list_of_str_option(
                    NAMESPACE, self.options[NAMESPACE]
                )
                tables = self.lakeflow_connect.list_tables_in_namespace(namespace)
                return [
                    {"namespace": namespace, TABLE_NAME: tn}
                    for tn in sorted(tables)
                ]
            # Flat connector path. Reject a stray `namespace` option — the
            # caller probably mistook this connector for namespace-aware and
            # silently ignoring the option would mask the bug.
            if namespace_supplied:
                raise ValueError(
                    f"option '{NAMESPACE}' was supplied but the connector does "
                    f"not implement SupportsNamespaces. Either omit the option "
                    f"or use a namespace-aware connector."
                )
            return [
                {"namespace": [], TABLE_NAME: tn}
                for tn in sorted(self.lakeflow_connect.list_tables())
            ]


    class LakeflowSource(DataSource):
        """
        PySpark DataSource base for Lakeflow Connect.

        Two ways the connector implementation is bound:

        - Per-source subclass (wheel / multi-file deployment): subclass and set
          ``_lakeflow_connect_cls``::

              class GmailDataSource(LakeflowSource):
                  _lakeflow_connect_cls = GmailLakeflowConnect

              spark.dataSource.register(GmailDataSource)

        - Merged single-file deployment (SDP): ``_lakeflow_connect_cls`` is left
          ``None`` and the connector is taken from the module-level
          ``LakeflowConnectImpl`` placeholder, which the merge script substitutes
          with the actual implementation class.
        """

        # Per-source subclasses set this. Left ``None`` on the base so the merged
        # single-file path falls back to the ``LakeflowConnectImpl`` placeholder.
        _lakeflow_connect_cls = None

        # Spark format name. Defaults to "lakeflow_connect" because Unity Catalog
        # connection-option injection looks for that exact string. A per-source
        # subclass may override this with its source name once it no longer relies
        # on UC injection (see the commented override in each source's __init__.py).
        _format_name = "lakeflow_connect"

        def __init__(self, options):
            self.options = options
            table = options.get(TABLE_NAME)
            # Catch typos against the framework's reserved virtual-table namespace
            # early — falling through to the connector with an unknown
            # `_community_*` name yields a confusing per-connector error.
            if table and table.startswith("_community_") and table not in VIRTUAL_TABLES:
                raise ValueError(
                    f"unknown framework virtual table '{table}'. Valid framework "
                    f"virtual tables are: {', '.join(VIRTUAL_TABLES)}. "
                    f"For a regular source table, use a name that does not start "
                    f"with '_community_'."
                )
            # Per-source subclasses bind the implementation via _lakeflow_connect_cls.
            # The merged single-file path leaves it None and relies on the
            # LakeflowConnectImpl placeholder (substituted by the merge script).
            connect_cls = type(self)._lakeflow_connect_cls or LakeflowConnectImpl
            self.lakeflow_connect = connect_cls(options)  # pylint: disable=abstract-class-instantiated

        @classmethod
        def name(cls):
            return cls._format_name

        def schema(self):
            table = self.options[TABLE_NAME]
            if table == METADATA_TABLE:
                return StructType(
                    [
                        StructField(TABLE_NAME, StringType(), False),
                        StructField("primary_keys", ArrayType(StringType()), True),
                        StructField("cursor_field", StringType(), True),
                        StructField("ingestion_type", StringType(), True),
                    ]
                )
            if table == NAMESPACES_TABLE:
                return StructType(
                    [
                        StructField("namespace", ArrayType(StringType()), False),
                    ]
                )
            if table == TABLES_TABLE:
                return StructType(
                    [
                        StructField("namespace", ArrayType(StringType()), False),
                        StructField(TABLE_NAME, StringType(), False),
                    ]
                )
            return self.lakeflow_connect.get_table_schema(table, self.options)

        def reader(self, schema: StructType):
            return LakeflowBatchReader(self.options, schema, self.lakeflow_connect)

        def streamReader(self, schema: StructType):
            # Use the partitioned DataSourceStreamReader when the connector
            # implements SupportsPartitionedStream and the table opts in.
            # Otherwise, delegate to super() which raises PySparkNotImplementedError,
            # causing Spark to fall back to simpleStreamReader().
            if isinstance(self.lakeflow_connect, SupportsPartitionedStream):
                table = self.options[TABLE_NAME]
                if self.lakeflow_connect.is_partitioned(table):
                    return LakeflowPartitionedStreamReader(self.options, schema, self.lakeflow_connect)
            return super().streamReader(schema)

        def simpleStreamReader(self, schema: StructType):
            return LakeflowStreamReader(self.options, schema, self.lakeflow_connect)


    spark.dataSource.register(LakeflowSource)
