# ==============================================================================
# Merged Lakeflow Source: youtube
# ==============================================================================
# This file is auto-generated by tools/scripts/merge_python_source.py
# Do not edit manually. Make changes to the source files instead.
# ==============================================================================

from abc import ABC, abstractmethod
from datetime import datetime
from decimal import Decimal
from itertools import chain
from typing import Any, Iterator, Sequence
import json
import time

from pyspark.sql import Row
from pyspark.sql.datasource import (
    DataSource,
    DataSourceReader,
    DataSourceStreamReader,
    InputPartition,
    SimpleDataSourceStreamReader,
)
from pyspark.sql.streaming.datasource import ReadAllAvailable, SupportsTriggerAvailableNow
from pyspark.sql.types import (
    ArrayType,
    BinaryType,
    BooleanType,
    DataType,
    DateType,
    DecimalType,
    DoubleType,
    FloatType,
    IntegerType,
    LongType,
    MapType,
    StringType,
    StructField,
    StructType,
    TimestampType,
    VariantType,
    VariantVal,
)
import base64
import requests


def register_lakeflow_source(spark):
    """Register the Lakeflow Python source with Spark."""

    ########################################################
    # src/databricks/labs/community_connector/libs/utils.py
    ########################################################

    def _parse_struct(value: Any, field_type: StructType) -> Row:
        """Parse a dictionary into a PySpark Row based on StructType schema."""
        if not isinstance(value, dict):
            raise ValueError(f"Expected a dictionary for StructType, got {type(value)}")
        # Spark Python -> Arrow conversion require missing StructType fields to be assigned None.
        if value == {}:
            raise ValueError(
                "field in StructType cannot be an empty dict. "
                "Please assign None as the default value instead."
            )
        field_dict = {}
        for field in field_type.fields:
            if field.name in value:
                field_dict[field.name] = parse_value(value.get(field.name), field.dataType)
            elif field.nullable:
                field_dict[field.name] = None
            else:
                raise ValueError(f"Field {field.name} is not nullable but not found in the input")
        return Row(**field_dict)


    def _parse_array(value: Any, field_type: ArrayType) -> list:
        """Parse a list into a PySpark array based on ArrayType schema."""
        if not isinstance(value, list):
            if field_type.containsNull:
                return [parse_value(value, field_type.elementType)]
            raise ValueError(f"Expected a list for ArrayType, got {type(value)}")
        return [parse_value(v, field_type.elementType) for v in value]


    def _parse_map(value: Any, field_type: MapType) -> dict:
        """Parse a dictionary into a PySpark map based on MapType schema."""
        if not isinstance(value, dict):
            raise ValueError(f"Expected a dictionary for MapType, got {type(value)}")
        return {
            parse_value(k, field_type.keyType): parse_value(v, field_type.valueType)
            for k, v in value.items()
        }


    def _parse_string(value: Any) -> str:
        """Convert value to string."""
        return str(value)


    def _parse_integer(value: Any) -> int:
        """Convert value to integer."""
        if isinstance(value, str) and value.strip():
            return int(float(value)) if "." in value else int(value)
        if isinstance(value, (int, float)):
            return int(value)
        raise ValueError(f"Cannot convert {value} to integer")


    def _parse_float(value: Any) -> float:
        """Convert value to float."""
        return float(value)


    def _parse_decimal(value: Any) -> Decimal:
        """Convert value to Decimal."""
        return Decimal(value) if isinstance(value, str) and value.strip() else Decimal(str(value))


    def _parse_boolean(value: Any) -> bool:
        """Convert value to boolean."""
        if isinstance(value, str):
            lowered = value.lower()
            if lowered in ("true", "t", "yes", "y", "1"):
                return True
            if lowered in ("false", "f", "no", "n", "0"):
                return False
        return bool(value)


    def _parse_date(value: Any) -> datetime.date:
        """Convert value to date."""
        if isinstance(value, str):
            for fmt in ("%Y-%m-%d", "%m/%d/%Y", "%d-%m-%Y", "%Y/%m/%d"):
                try:
                    return datetime.strptime(value, fmt).date()
                except ValueError:
                    continue
            return datetime.fromisoformat(value).date()
        if isinstance(value, datetime):
            return value.date()
        raise ValueError(f"Cannot convert {value} to date")


    def _parse_timestamp(value: Any) -> datetime:
        """Convert value to timestamp."""
        if isinstance(value, str):
            ts_value = value.replace("Z", "+00:00") if value.endswith("Z") else value
            try:
                return datetime.fromisoformat(ts_value)
            except ValueError:
                for fmt in ("%Y-%m-%d %H:%M:%S", "%Y/%m/%d %H:%M:%S"):
                    try:
                        return datetime.strptime(ts_value, fmt)
                    except ValueError:
                        continue
        elif isinstance(value, (int, float)):
            return datetime.fromtimestamp(value)
        elif isinstance(value, datetime):
            return value
        raise ValueError(f"Cannot convert {value} to timestamp")


    def _decode_string_to_bytes(value: str) -> bytes:
        """Try to decode a string as base64, then hex, then UTF-8."""
        try:
            return base64.b64decode(value)
        except Exception:
            pass
        try:
            return bytes.fromhex(value)
        except Exception:
            pass
        return value.encode("utf-8")


    def _parse_binary(value: Any) -> bytes:
        """Convert value to bytes. Tries base64, then hex, then UTF-8 for strings."""
        if isinstance(value, bytes):
            return value
        if isinstance(value, bytearray):
            return bytes(value)
        if isinstance(value, str):
            return _decode_string_to_bytes(value)
        if isinstance(value, list):
            return bytes(value)
        return str(value).encode("utf-8")


    # Mapping of primitive types to their parser functions
    _PRIMITIVE_PARSERS = {
        StringType: _parse_string,
        IntegerType: _parse_integer,
        LongType: _parse_integer,
        FloatType: _parse_float,
        DoubleType: _parse_float,
        DecimalType: _parse_decimal,
        BooleanType: _parse_boolean,
        DateType: _parse_date,
        TimestampType: _parse_timestamp,
        BinaryType: _parse_binary,
    }


    def parse_value(value: Any, field_type: DataType) -> Any:  # pylint: disable=too-many-return-statements
        """
        Converts a JSON value into a PySpark-compatible data type based on the provided field type.
        """
        if value is None:
            return None

        # Handle complex types
        if isinstance(field_type, StructType):
            return _parse_struct(value, field_type)
        if isinstance(field_type, ArrayType):
            return _parse_array(value, field_type)
        if isinstance(field_type, MapType):
            return _parse_map(value, field_type)

        # Handle VariantType
        if isinstance(field_type, VariantType):
            return VariantVal.parseJson(value) if isinstance(value, str) else value

        # Handle primitive types via type-based lookup
        try:
            field_type_class = type(field_type)
            if field_type_class in _PRIMITIVE_PARSERS:
                return _PRIMITIVE_PARSERS[field_type_class](value)

            # Check for custom UDT handling
            if hasattr(field_type, "fromJson"):
                return field_type.fromJson(value)

            raise TypeError(f"Unsupported field type: {field_type}")
        except (ValueError, TypeError) as e:
            raise ValueError(f"Error converting '{value}' ({type(value)}) to {field_type}: {str(e)}")


    ########################################################
    # src/databricks/labs/community_connector/interface/lakeflow_connect.py
    ########################################################

    class LakeflowConnect(ABC):
        """Base interface that each source connector must implement.

        Subclass this and implement all abstract methods to create a connector that
        integrates with the community connector library and ingestion pipeline.
        """

        def __init__(self, options: dict[str, str]) -> None:
            """
            Initialize the source connector with parameters needed to connect to the source.
            Args:
                options: A dictionary of parameters like authentication tokens, table names,
                    and other configurations.
            """
            self.options = options

        @abstractmethod
        def list_tables(self) -> list[str]:
            """
            List names of all the tables supported by the source connector.
            The list could either be a static list or retrieved from the source via API.
            Returns:
                A list of table names.
            """

        @abstractmethod
        def get_table_schema(
            self, table_name: str, table_options: dict[str, str]
        ) -> StructType:
            """
            Fetch the schema of a table.
            Args:
                table_name: The name of the table to fetch the schema for.
                table_options: A dictionary of options for accessing the table. For example,
                    the source API may require extra parameters needed to fetch the schema.
                    If there are no additional options required, you can ignore this
                    parameter, and no options will be provided during execution.
                    Only add parameters to table_options if they are essential for accessing
                    or retrieving the data (such as specifying table namespaces).
            Returns:
                A StructType object representing the schema of the table.
            """

        @abstractmethod
        def read_table_metadata(
            self, table_name: str, table_options: dict[str, str]
        ) -> dict:
            """
            Fetch the metadata of a table.
            Args:
                table_name: The name of the table to fetch the metadata for.
                table_options: A dictionary of options for accessing the table. For example,
                    the source API may require extra parameters needed to fetch the metadata.
                    If there are no additional options required, you can ignore this
                    parameter, and no options will be provided during execution.
                    Only add parameters to table_options if they are essential for accessing
                    or retrieving the data (such as specifying table namespaces).
            Returns:
                A dictionary containing the metadata of the table. It should include the
                following keys:
                    - primary_keys: List of string names of the primary key columns of
                        the table.
                    - cursor_field: The name of the field to use as a cursor for
                        incremental loading.
                    - ingestion_type: The type of ingestion to use for the table. It
                        should be one of the following values:
                        - "snapshot": For snapshot loading.
                        - "cdc": Capture incremental changes (no delete support).
                        - "cdc_with_deletes": Capture incremental changes with delete
                            support. Requires implementing read_table_deletes().
                        - "append": Incremental append.
            """

        @abstractmethod
        def read_table(
            self, table_name: str, start_offset: dict, table_options: dict[str, str]
        ) -> tuple[Iterator[dict], dict]:
            """
            Read the records of a table and return an iterator of records and an offset.

            The framework calls this method repeatedly to paginate through data.
            start_offset is None only on the very first call of the very first run
            of a connector. On subsequent runs the framework resumes from the last
            checkpointed offset, so start_offset will already be populated. Each
            call returns (records, end_offset). The framework passes end_offset as
            start_offset to the next call. Pagination stops when the returned
            offset equals start_offset (i.e., no more data).

            For tables that cannot be incrementally read, return None as the offset to
            read the entire table in one batch. Non-checkpointable synthetic offsets can
            be used to split the data into multiple batches.

            Args:
                table_name: The name of the table to read.
                start_offset: The offset to start reading from. None only on the
                    first call of the first run; on subsequent runs it carries the
                    checkpointed offset from the previous run.
                table_options: A dictionary of options for accessing the table. For example,
                    the source API may require extra parameters needed to read the table.
                    If there are no additional options required, you can ignore this
                    parameter, and no options will be provided during execution.
                    Only add parameters to table_options if they are essential for accessing
                    or retrieving the data (such as specifying table namespaces).
            Returns:
                A two-element tuple of (records, offset).
                records: An iterator of records as JSON-compatible dicts, or
                    ``pyarrow.RecordBatch`` objects for the Spark direct-Arrow path.
                    Do NOT convert row values according to get_table_schema(); the
                    framework handles row conversion.
                offset: A dict representing the position after this batch.
            """

        def read_table_deletes(
            self, table_name: str, start_offset: dict, table_options: dict[str, str]
        ) -> tuple[Iterator[dict], dict]:
            """
            Read deleted records from a table for CDC delete synchronization.
            This method is called when ingestion_type is "cdc_with_deletes" to fetch
            records that have been deleted from the source system.

            This method follows the same pagination and offset protocol as read_table:
            the framework calls it repeatedly, passing the previous end_offset as
            start_offset, until the returned offset equals start_offset.

            Override this method if any of your tables use ingestion_type
            "cdc_with_deletes". The default implementation raises NotImplementedError.

            The returned records should have at minimum the primary key fields and
            cursor field populated. Other fields can be null.

            Args:
                table_name: The name of the table to read deleted records from.
                start_offset: The offset to start reading from (same format as read_table).
                table_options: A dictionary of options for accessing the table.
            Returns:
                A two-element tuple of (records, offset).
                records: An iterator of deleted records (must include primary keys and cursor).
                offset: A dict (same format as read_table).
            """
            raise NotImplementedError(
                "read_table_deletes() must be implemented when ingestion_type is 'cdc_with_deletes'"
            )


    ########################################################
    # src/databricks/labs/community_connector/interface/supports_partition.py
    ########################################################

    class SupportsPartition(ABC):
        """Mixin for connectors that support partitioned reads across Spark executors.

        Must be used together with LakeflowConnect. Implement this when your
        connector can split work into partitions that Spark distributes to workers,
        instead of reading all data in one partition batch.

        Usage::

            class MyConnector(LakeflowConnect, SupportsPartition):
                ...
        """

        @abstractmethod
        def get_partitions(
            self,
            table_name: str,
            table_options: dict[str, str],
        ) -> Sequence[dict]:
            """Return partition descriptors for reading data.

            Each returned dict is passed to :meth:`read_partition` on an executor.

            Args:
                table_name: The name of the table.
                table_options: A dictionary of options for accessing the table.
            Returns:
                A sequence of partition descriptor dicts. Each dict must be
                JSON-serialisable (primitive types only).
            """

        @abstractmethod
        def read_partition(
            self, table_name: str, partition: dict, table_options: dict[str, str]
        ) -> Iterator[dict]:
            """Read records for a single partition.

            This method runs on Spark executors and must be self-contained.

            Args:
                table_name: The name of the table.
                partition: One of the partition dicts returned by
                    :meth:`get_partitions`.
                table_options: A dictionary of options for accessing the table.
            Returns:
                An iterator of JSON-compatible record dictionaries or PyArrow
                RecordBatch objects for Spark's direct-Arrow reader path.
            """


    class SupportsPartitionedStream(SupportsPartition):
        """Mixin for connectors that support partitioned streaming reads.

        Extends :class:`SupportsPartition` with offset awareness for streaming
        micro-batches. A connector implementing this mixin automatically supports
        both partitioned batch reads (via the inherited interface) and partitioned
        streaming reads.

        Usage::

            class MyConnector(LakeflowConnect, SupportsPartitionedStream):
                ...
        """

        def is_partitioned(self, table_name: str) -> bool:
            """Return whether the given table supports partitioned streaming.

            The default returns True. Override to return False for tables that
            should fall back to simpleStreamReader.

            Args:
                table_name: The name of the table.
                table_options: A dictionary of options for accessing the table.
            """
            return True

        @abstractmethod
        def latest_offset(
            self,
            table_name: str,
            table_options: dict[str, str],
            start_offset: dict | None = None,
        ) -> dict:
            """Return the most recent offset available for the table.

            Called by Spark on every micro-batch to discover new data.

            Micro-batch sizing (by row count, time window, etc.) is entirely the
            connector's responsibility — use table_options (e.g. ``window_days``,
            ``max_records_per_batch``) to control it.  The framework always
            requests "all available" and does not pass an admission-control
            hint here.

            Args:
                table_name: The name of the table.
                table_options: A dictionary of options for accessing the table.
                start_offset: The current committed offset.  ``{}`` on the very
                    first call (from ``initialOffset``), then the last returned
                    end_offset on each subsequent call.
            Returns:
                A dict whose keys and values are primitive types (str, int, bool).
            """

        @abstractmethod
        def get_partitions(
            self,
            table_name: str,
            table_options: dict[str, str],
            start_offset: dict | None = None,
            end_offset: dict | None = None,
        ) -> Sequence[dict]:
            """Return partition descriptors for reading data.

            Each returned dict is passed to :meth:`read_partition` on an executor.

            For batch reads, ``start_offset`` and ``end_offset`` are both None —
            return partitions covering the entire table.

            For streaming micro-batches, they delimit the offset range — return
            partitions covering that range, or an empty sequence when
            ``start_offset == end_offset``.

            Args:
                table_name: The name of the table.
                table_options: A dictionary of options for accessing the table.
                start_offset: The start offset (exclusive), or None for batch.
                end_offset: The end offset (inclusive), or None for batch.
            Returns:
                A sequence of partition descriptor dicts. Each dict must be
                JSON-serialisable (primitive types only).
            """


    ########################################################
    # src/databricks/labs/community_connector/interface/supports_namespaces.py
    ########################################################

    class SupportsNamespaces(ABC):
        """Mixin for connectors whose tables live under hierarchical namespaces.

        A namespace is a path of zero or more string segments (e.g. ``["org",
        "repo"]`` for GitHub, ``["tenant", "project"]`` for Azure DevOps).
        Connectors with a flat catalog do not need this mixin — the framework
        falls back to :meth:`LakeflowConnect.list_tables` and reports each table
        with an empty namespace.

        Output ordering on the ``_community_namespaces`` and ``_community_tables``
        Spark virtual tables is normalized by the framework via ``sorted(...)``,
        so connector implementations of :meth:`list_namespaces` and
        :meth:`list_tables_in_namespace` are free to return their results in
        any order (including from a :class:`set` or generator).

        Must be used together with :class:`LakeflowConnect`.

        Usage::

            class MyConnector(LakeflowConnect, SupportsNamespaces):
                ...
        """

        @abstractmethod
        def list_namespaces(
            self,
            prefix: list[str] | None = None,
        ) -> list[list[str]]:
            """Return the immediate child namespaces under ``prefix``.

            This method returns one level of *namespace* children only — it
            never returns tables. A namespace can hold tables and child
            namespaces independently; callers must always call
            :meth:`list_tables_in_namespace` for every namespace they care
            about, regardless of whether :meth:`list_namespaces` returned
            children for it. An empty return value just means there are no
            further child namespaces under ``prefix``.

            Walk the full tree by recursing on each returned child.

            Args:
                prefix: A namespace path under which to list children. ``None`` or
                    an empty list lists the root-level namespaces.
            Returns:
                A list of full namespace paths (each path includes the prefix).
            """

        @abstractmethod
        def list_tables_in_namespace(
            self,
            namespace: list[str],
        ) -> list[str]:
            """Return the table names that live directly under ``namespace``.

            Callers that want every table across the whole catalog walk the
            namespace tree via :meth:`list_namespaces` and call this method
            once per leaf — there is no "list everything" shortcut.

            Args:
                namespace: The namespace path. An empty list ``[]`` selects
                    root-level tables (those that live outside any namespace).
            Returns:
                A list of table names. The full ``(namespace, table_name)``
                row exposed on ``_community_tables`` is reconstructed by the
                framework from the namespace the caller already supplied, so
                the connector does not need to echo it back.
            """


    ########################################################
    # src/databricks/labs/community_connector/sources/youtube/youtube_schemas.py
    ########################################################

    SUPPORTED_TABLES = [
        "channels",
        "playlists",
        "playlist_items",
        "videos",
        "search",
        "activities",
        "comment_threads",
        "subscriptions",
        "video_categories",
    ]

    # ---------------------------------------------------------------------------
    # Tier 1 – Core content
    # ---------------------------------------------------------------------------

    # channels: GET /channels (snippet, statistics, contentDetails)
    CHANNELS_SCHEMA = StructType(
        [
            StructField("id", StringType(), nullable=False),
            StructField("snippet_title", StringType(), nullable=True),
            StructField("snippet_description", StringType(), nullable=True),
            StructField("snippet_publishedAt", StringType(), nullable=True),
            StructField("snippet_thumbnails_default_url", StringType(), nullable=True),
            StructField("snippet_defaultLanguage", StringType(), nullable=True),
            StructField("statistics_viewCount", StringType(), nullable=True),
            StructField("statistics_subscriberCount", StringType(), nullable=True),
            StructField("statistics_videoCount", StringType(), nullable=True),
            StructField("contentDetails_relatedPlaylists_uploads", StringType(), nullable=True),
        ]
    )

    # playlists: GET /playlists (snippet, contentDetails)
    PLAYLISTS_SCHEMA = StructType(
        [
            StructField("id", StringType(), nullable=False),
            StructField("snippet_publishedAt", StringType(), nullable=True),
            StructField("snippet_channelId", StringType(), nullable=True),
            StructField("snippet_title", StringType(), nullable=True),
            StructField("snippet_description", StringType(), nullable=True),
            StructField("snippet_thumbnails_default_url", StringType(), nullable=True),
            StructField("contentDetails_itemCount", StringType(), nullable=True),
        ]
    )

    # playlist_items: GET /playlistItems (snippet, contentDetails)
    PLAYLIST_ITEMS_SCHEMA = StructType(
        [
            StructField("id", StringType(), nullable=False),
            StructField("snippet_publishedAt", StringType(), nullable=True),
            StructField("snippet_channelId", StringType(), nullable=True),
            StructField("snippet_title", StringType(), nullable=True),
            StructField("snippet_description", StringType(), nullable=True),
            StructField("snippet_playlistId", StringType(), nullable=True),
            StructField("snippet_position", StringType(), nullable=True),
            StructField("snippet_resourceId_videoId", StringType(), nullable=True),
            StructField("contentDetails_videoId", StringType(), nullable=True),
        ]
    )

    # videos: GET /videos (snippet, statistics, contentDetails)
    VIDEOS_SCHEMA = StructType(
        [
            StructField("id", StringType(), nullable=False),
            StructField("snippet_publishedAt", StringType(), nullable=True),
            StructField("snippet_channelId", StringType(), nullable=True),
            StructField("snippet_title", StringType(), nullable=True),
            StructField("snippet_description", StringType(), nullable=True),
            StructField("snippet_thumbnails_default_url", StringType(), nullable=True),
            StructField("snippet_channelTitle", StringType(), nullable=True),
            StructField("snippet_categoryId", StringType(), nullable=True),
            StructField("snippet_liveBroadcastContent", StringType(), nullable=True),
            StructField("statistics_viewCount", StringType(), nullable=True),
            StructField("statistics_likeCount", StringType(), nullable=True),
            StructField("statistics_commentCount", StringType(), nullable=True),
            StructField("contentDetails_duration", StringType(), nullable=True),
            StructField("contentDetails_definition", StringType(), nullable=True),
        ]
    )

    # ---------------------------------------------------------------------------
    # Tier 2 – Discovery and engagement
    # ---------------------------------------------------------------------------

    # search: GET /search (returns id.videoId, id.channelId, id.playlistId + snippet)
    # search_query + result_index: stable PK per query (result_index is 0-based position in results)
    SEARCH_SCHEMA = StructType(
        [
            StructField("search_query", StringType(), nullable=False),
            StructField("result_index", StringType(), nullable=False),
            StructField("kind", StringType(), nullable=True),
            StructField("id_videoId", StringType(), nullable=True),
            StructField("id_channelId", StringType(), nullable=True),
            StructField("id_playlistId", StringType(), nullable=True),
            StructField("snippet_publishedAt", StringType(), nullable=True),
            StructField("snippet_channelId", StringType(), nullable=True),
            StructField("snippet_title", StringType(), nullable=True),
            StructField("snippet_description", StringType(), nullable=True),
            StructField("snippet_channelTitle", StringType(), nullable=True),
        ]
    )

    # activities: GET /activities (snippet, contentDetails)
    ACTIVITIES_SCHEMA = StructType(
        [
            StructField("id", StringType(), nullable=False),
            StructField("snippet_publishedAt", StringType(), nullable=True),
            StructField("snippet_channelId", StringType(), nullable=True),
            StructField("snippet_title", StringType(), nullable=True),
            StructField("snippet_type", StringType(), nullable=True),
            StructField("snippet_channelTitle", StringType(), nullable=True),
            StructField("contentDetails_upload_videoId", StringType(), nullable=True),
            StructField("contentDetails_like_videoId", StringType(), nullable=True),
        ]
    )

    # comment_threads: GET /commentThreads (snippet with topLevelComment)
    COMMENT_THREADS_SCHEMA = StructType(
        [
            StructField("id", StringType(), nullable=False),
            StructField("snippet_videoId", StringType(), nullable=True),
            StructField("snippet_topLevelComment_id", StringType(), nullable=True),
            StructField("snippet_topLevelComment_snippet_textDisplay", StringType(), nullable=True),
            StructField(
                "snippet_topLevelComment_snippet_authorDisplayName",
                StringType(),
                nullable=True,
            ),
            StructField("snippet_topLevelComment_snippet_publishedAt", StringType(), nullable=True),
            StructField("snippet_topLevelComment_snippet_likeCount", StringType(), nullable=True),
            StructField("snippet_canReply", StringType(), nullable=True),
            StructField("snippet_totalReplyCount", StringType(), nullable=True),
        ]
    )

    # subscriptions: GET /subscriptions (snippet)
    SUBSCRIPTIONS_SCHEMA = StructType(
        [
            StructField("id", StringType(), nullable=False),
            StructField("snippet_publishedAt", StringType(), nullable=True),
            StructField("snippet_title", StringType(), nullable=True),
            StructField("snippet_description", StringType(), nullable=True),
            StructField("snippet_resourceId_channelId", StringType(), nullable=True),
            StructField("snippet_thumbnails_default_url", StringType(), nullable=True),
        ]
    )

    # ---------------------------------------------------------------------------
    # Tier 3 – Reference
    # ---------------------------------------------------------------------------

    # video_categories: GET /videoCategories (snippet)
    VIDEO_CATEGORIES_SCHEMA = StructType(
        [
            StructField("id", StringType(), nullable=False),
            StructField("snippet_title", StringType(), nullable=True),
            StructField("snippet_assignable", StringType(), nullable=True),
            StructField("snippet_channelId", StringType(), nullable=True),
        ]
    )

    TABLE_SCHEMAS = {
        "channels": CHANNELS_SCHEMA,
        "playlists": PLAYLISTS_SCHEMA,
        "playlist_items": PLAYLIST_ITEMS_SCHEMA,
        "videos": VIDEOS_SCHEMA,
        "search": SEARCH_SCHEMA,
        "activities": ACTIVITIES_SCHEMA,
        "comment_threads": COMMENT_THREADS_SCHEMA,
        "subscriptions": SUBSCRIPTIONS_SCHEMA,
        "video_categories": VIDEO_CATEGORIES_SCHEMA,
    }

    # ---------------------------------------------------------------------------
    # Table metadata (primary_keys, ingestion_type)
    # ---------------------------------------------------------------------------
    TABLE_METADATA = {
        "channels": {
            "primary_keys": ["id"],
            "ingestion_type": "snapshot",
        },
        "playlists": {
            "primary_keys": ["id"],
            "ingestion_type": "snapshot",
        },
        "playlist_items": {
            "primary_keys": ["id"],
            "ingestion_type": "snapshot",
        },
        "videos": {
            "primary_keys": ["id"],
            "ingestion_type": "snapshot",
        },
        "search": {
            "primary_keys": ["search_query", "result_index"],
            "ingestion_type": "snapshot",
        },
        "activities": {
            "primary_keys": ["id"],
            "ingestion_type": "snapshot",
        },
        "comment_threads": {
            "primary_keys": ["id"],
            "ingestion_type": "snapshot",
        },
        "subscriptions": {
            "primary_keys": ["id"],
            "ingestion_type": "snapshot",
        },
        "video_categories": {
            "primary_keys": ["id"],
            "ingestion_type": "snapshot",
        },
    }


    ########################################################
    # src/databricks/labs/community_connector/sources/youtube/youtube.py
    ########################################################

    BASE_URL = "https://www.googleapis.com/youtube/v3"
    TOKEN_URL = "https://oauth2.googleapis.com/token"
    INITIAL_BACKOFF = 1.0
    MAX_RETRIES = 5
    RETRIABLE_STATUS_CODES = {429, 500, 503}
    MAX_RESULTS_DEFAULT = 50
    # commentThreads and comments support 1-100; other list endpoints support 1-50
    MAX_RESULTS_COMMENT_THREADS = 100


    def _max_results(
        table_options: dict[str, str],
        default: int = MAX_RESULTS_DEFAULT,
        cap: int = 50,
    ) -> int:
        """Parse max_results from table_options; clamp to [1, cap]. Used for pagination page size."""
        raw = table_options.get("max_results") or ""
        if not raw:
            return min(default, cap)
        try:
            n = int(raw.strip())
            return max(1, min(n, cap))
        except ValueError:
            return min(default, cap)


    def _parse_max_pages(
        table_options: dict[str, str], default: int = 100, cap: int = 1000
    ) -> int:
        """Parse max_pages from table_options; clamp to [1, cap]."""
        raw = (table_options.get("max_pages") or "").strip()
        if not raw:
            return default
        try:
            return max(1, min(int(raw), cap))
        except ValueError:
            return default


    def _chunked_ids(raw_ids: str, size: int = 50) -> list[list[str]]:
        """Split comma-separated IDs into de-duplicated fixed-size batches."""
        ids = [item.strip() for item in raw_ids.split(",") if item.strip()]
        unique_ids = list(dict.fromkeys(ids))
        return [unique_ids[i : i + size] for i in range(0, len(unique_ids), size)]


    def _retry_wait_seconds(resp: requests.Response, backoff: float) -> float:
        """Seconds to sleep before retry; honor Retry-After when present."""
        retry_after = resp.headers.get("Retry-After")
        if retry_after:
            try:
                return float(retry_after)
            except (TypeError, ValueError):
                pass
        return backoff


    def _youtube_error_fields(resp: requests.Response) -> tuple[str, str]:
        """Parse Google API error JSON into (reason, message)."""
        try:
            err = resp.json().get("error", {})
            errors = err.get("errors") or [{}]
            reason = (errors[0].get("reason") or "") if errors else ""
            message = err.get("message") or reason or resp.reason
            return str(reason), str(message)[:300]
        except Exception:
            return "", (resp.text or resp.reason or "unknown error")[:300]


    def _raise_for_youtube_api_error(
        resp: requests.Response,
        path: str,
        *,
        detail: str | None = None,
    ) -> None:
        """Raise ValueError with actionable text for common YouTube API failures."""
        if resp.ok:
            return
        reason, message = _youtube_error_fields(resp)
        status = resp.status_code

        if status == 401:
            raise ValueError(
                f"YouTube API {path} returned 401 Unauthorized. "
                "Verify API key or OAuth credentials. OAuth is required for mine=true "
                "and other private data. "
                f"Detail: {message}"
            )
        if status == 403:
            if reason == "quotaExceeded":
                raise ValueError(
                    f"YouTube API {path} returned 403: quota exceeded. "
                    "Reduce sync frequency (search costs 100 units per request) or "
                    "request a quota increase in Google Cloud Console. "
                    f"Detail: {message}"
                )
            if path == "commentThreads":
                ctx = f" ({detail})" if detail else ""
                raise ValueError(
                    f"comment_threads returned 403 Forbidden{ctx}. Comments may be disabled "
                    "for this video or channel, or access may be restricted. Prefer video_id "
                    "over channel_id; see README. "
                    f"API reason: {reason or message}"
                )
            raise ValueError(
                f"YouTube API {path} returned 403 Forbidden. "
                f"Reason: {reason or message}. "
                "Check credentials, API enablement, and table options (e.g. OAuth for mine=true)."
            )
        if status == 429:
            raise ValueError(
                f"YouTube API {path} returned 429 Too Many Requests after retries. "
                f"Detail: {message}"
            )
        raise ValueError(
            f"YouTube API {path} returned HTTP {status}. Detail: {message}"
        )


    def _get_nested(d: dict, path: str, default: str | None = None) -> str | None:
        """Get a nested key like 'snippet.title'; return as string or default."""
        if not d or not path:
            return default
        parts = path.split(".")
        cur: Any = d
        for p in parts:
            cur = cur.get(p) if isinstance(cur, dict) else None
            if cur is None:
                return default
        return str(cur) if cur is not None else default


    def _flatten_channel(item: dict) -> dict:
        """Flatten a channel resource to schema fields."""
        return {
            "id": item.get("id") or "",
            "snippet_title": _get_nested(item, "snippet.title"),
            "snippet_description": _get_nested(item, "snippet.description"),
            "snippet_publishedAt": _get_nested(item, "snippet.publishedAt"),
            "snippet_thumbnails_default_url": _get_nested(
                item, "snippet.thumbnails.default.url"
            ),
            "snippet_defaultLanguage": _get_nested(item, "snippet.defaultLanguage"),
            "statistics_viewCount": _get_nested(item, "statistics.viewCount"),
            "statistics_subscriberCount": _get_nested(item, "statistics.subscriberCount"),
            "statistics_videoCount": _get_nested(item, "statistics.videoCount"),
            "contentDetails_relatedPlaylists_uploads": _get_nested(
                item, "contentDetails.relatedPlaylists.uploads"
            ),
        }


    def _flatten_playlist(item: dict) -> dict:
        """Flatten a playlist resource to schema fields."""
        return {
            "id": item.get("id") or "",
            "snippet_publishedAt": _get_nested(item, "snippet.publishedAt"),
            "snippet_channelId": _get_nested(item, "snippet.channelId"),
            "snippet_title": _get_nested(item, "snippet.title"),
            "snippet_description": _get_nested(item, "snippet.description"),
            "snippet_thumbnails_default_url": _get_nested(
                item, "snippet.thumbnails.default.url"
            ),
            "contentDetails_itemCount": _get_nested(item, "contentDetails.itemCount"),
        }


    def _flatten_playlist_item(item: dict) -> dict:
        """Flatten a playlistItem resource to schema fields."""
        return {
            "id": item.get("id") or "",
            "snippet_publishedAt": _get_nested(item, "snippet.publishedAt"),
            "snippet_channelId": _get_nested(item, "snippet.channelId"),
            "snippet_title": _get_nested(item, "snippet.title"),
            "snippet_description": _get_nested(item, "snippet.description"),
            "snippet_playlistId": _get_nested(item, "snippet.playlistId"),
            "snippet_position": _get_nested(item, "snippet.position"),
            "snippet_resourceId_videoId": _get_nested(
                item, "snippet.resourceId.videoId"
            ),
            "contentDetails_videoId": _get_nested(item, "contentDetails.videoId"),
        }


    def _flatten_video(item: dict) -> dict:
        """Flatten a video resource to schema fields."""
        return {
            "id": item.get("id") or "",
            "snippet_publishedAt": _get_nested(item, "snippet.publishedAt"),
            "snippet_channelId": _get_nested(item, "snippet.channelId"),
            "snippet_title": _get_nested(item, "snippet.title"),
            "snippet_description": _get_nested(item, "snippet.description"),
            "snippet_thumbnails_default_url": _get_nested(
                item, "snippet.thumbnails.default.url"
            ),
            "snippet_channelTitle": _get_nested(item, "snippet.channelTitle"),
            "snippet_categoryId": _get_nested(item, "snippet.categoryId"),
            "snippet_liveBroadcastContent": _get_nested(
                item, "snippet.liveBroadcastContent"
            ),
            "statistics_viewCount": _get_nested(item, "statistics.viewCount"),
            "statistics_likeCount": _get_nested(item, "statistics.likeCount"),
            "statistics_commentCount": _get_nested(item, "statistics.commentCount"),
            "contentDetails_duration": _get_nested(item, "contentDetails.duration"),
            "contentDetails_definition": _get_nested(item, "contentDetails.definition"),
        }


    def _flatten_search_result(item: dict, result_index: str, search_query: str) -> dict:
        """Flatten a search result. PK is (search_query, result_index) with stable position index."""
        id_obj = item.get("id") or {}
        return {
            "search_query": search_query,
            "result_index": result_index,
            "kind": item.get("kind"),
            "id_videoId": id_obj.get("videoId") if isinstance(id_obj, dict) else None,
            "id_channelId": id_obj.get("channelId") if isinstance(id_obj, dict) else None,
            "id_playlistId": id_obj.get("playlistId") if isinstance(id_obj, dict) else None,
            "snippet_publishedAt": _get_nested(item, "snippet.publishedAt"),
            "snippet_channelId": _get_nested(item, "snippet.channelId"),
            "snippet_title": _get_nested(item, "snippet.title"),
            "snippet_description": _get_nested(item, "snippet.description"),
            "snippet_channelTitle": _get_nested(item, "snippet.channelTitle"),
        }


    def _flatten_activity(item: dict) -> dict:
        """Flatten an activity resource to schema fields."""
        content = item.get("contentDetails") or {}
        upload = content.get("upload") or {}
        like = content.get("like") or {}
        return {
            "id": item.get("id") or "",
            "snippet_publishedAt": _get_nested(item, "snippet.publishedAt"),
            "snippet_channelId": _get_nested(item, "snippet.channelId"),
            "snippet_title": _get_nested(item, "snippet.title"),
            "snippet_type": _get_nested(item, "snippet.type"),
            "snippet_channelTitle": _get_nested(item, "snippet.channelTitle"),
            "contentDetails_upload_videoId": (
                upload.get("videoId") if isinstance(upload, dict) else None
            ),
            "contentDetails_like_videoId": (
                like.get("resourceId", {}).get("videoId")
                if isinstance(like, dict) and isinstance(like.get("resourceId"), dict)
                else None
            ),
        }


    def _flatten_comment_thread(item: dict) -> dict:
        """Flatten a commentThread resource to schema fields."""
        snip = item.get("snippet") or {}
        top = snip.get("topLevelComment") or {}
        top_snip = (top.get("snippet") if isinstance(top, dict) else None) or {}
        return {
            "id": item.get("id") or "",
            "snippet_videoId": _get_nested(item, "snippet.videoId"),
            "snippet_topLevelComment_id": top.get("id") if isinstance(top, dict) else None,
            "snippet_topLevelComment_snippet_textDisplay": top_snip.get("textDisplay"),
            "snippet_topLevelComment_snippet_authorDisplayName": top_snip.get("authorDisplayName"),
            "snippet_topLevelComment_snippet_publishedAt": top_snip.get("publishedAt"),
            "snippet_topLevelComment_snippet_likeCount": (
                str(top_snip.get("likeCount")) if top_snip.get("likeCount") is not None else None
            ),
            "snippet_canReply": (
                str(snip.get("canReply")) if snip.get("canReply") is not None else None
            ),
            "snippet_totalReplyCount": (
                str(snip.get("totalReplyCount")) if snip.get("totalReplyCount") is not None else None
            ),
        }


    def _flatten_subscription(item: dict) -> dict:
        """Flatten a subscription resource to schema fields."""
        return {
            "id": item.get("id") or "",
            "snippet_publishedAt": _get_nested(item, "snippet.publishedAt"),
            "snippet_title": _get_nested(item, "snippet.title"),
            "snippet_description": _get_nested(item, "snippet.description"),
            "snippet_resourceId_channelId": _get_nested(
                item, "snippet.resourceId.channelId"
            ),
            "snippet_thumbnails_default_url": _get_nested(
                item, "snippet.thumbnails.default.url"
            ),
        }


    def _flatten_video_category(item: dict) -> dict:
        """Flatten a videoCategory resource to schema fields."""
        snip = item.get("snippet") or {}
        return {
            "id": item.get("id") or "",
            "snippet_title": _get_nested(item, "snippet.title"),
            "snippet_assignable": (
                str(snip.get("assignable")) if snip.get("assignable") is not None else None
            ),
            "snippet_channelId": _get_nested(item, "snippet.channelId"),
        }


    class YouTubeLakeflowConnect(LakeflowConnect):
        """LakeflowConnect implementation for YouTube Data API v3.

        Uses either api_key (for public data) or OAuth for private/mine data.
        OAuth supports a UC-injected access_token (preferred) or in-code refresh.
        """

        def __init__(self, options: dict[str, str]) -> None:
            super().__init__(options)
            self._api_key = (options.get("api_key") or "").strip()
            self._injected_access_token = (options.get("access_token") or "").strip() or None
            self._client_id = (options.get("client_id") or "").strip()
            self._client_secret = (options.get("client_secret") or "").strip()
            self._refresh_token = (options.get("refresh_token") or "").strip()
            has_refresh_oauth = bool(
                self._refresh_token and self._client_id and self._client_secret
            )
            has_injected_oauth = bool(self._injected_access_token)
            has_oauth = has_refresh_oauth or has_injected_oauth

            if self._api_key and has_oauth:
                raise ValueError(
                    "YouTube connector requires either 'api_key' or OAuth credentials "
                    "in options, not both"
                )
            if not self._api_key and not has_oauth:
                raise ValueError(
                    "YouTube connector requires either 'api_key' (public data) or an "
                    "OAuth credential: 'access_token' (the Unity Catalog COMMUNITY "
                    "connection's u2m / u2m_per_user OAuth flow injects it at query "
                    "time) or 'refresh_token' plus 'client_id' and 'client_secret' "
                    "(in-code refresh for older connections)."
                )
            if self._refresh_token and not (self._client_id and self._client_secret):
                raise ValueError(
                    "YouTube refresh-token auth requires 'client_id' and "
                    "'client_secret' alongside 'refresh_token' in options."
                )
            self._refreshed_token: str | None = None
            self._token_expires_at = 0.0
            self._session = requests.Session()

        def _get_access_token(self) -> str:
            """Return Bearer token: opaque UC token or refresh-exchange cache."""
            if self._injected_access_token:
                return self._injected_access_token
            if self._refreshed_token and time.time() < self._token_expires_at - 60:
                return self._refreshed_token
            resp = self._session.post(
                TOKEN_URL,
                data={
                    "client_id": self._client_id,
                    "client_secret": self._client_secret,
                    "refresh_token": self._refresh_token,
                    "grant_type": "refresh_token",
                },
                headers={"Content-Type": "application/x-www-form-urlencoded"},
                timeout=60,
            )
            if resp.status_code == 401:
                raise ValueError(
                    "YouTube OAuth returned 401. Check client_id, client_secret, "
                    "and refresh_token; re-run OAuth flow if needed."
                )
            if resp.status_code == 400:
                try:
                    if resp.json().get("error") == "invalid_grant":
                        raise ValueError(
                            "YouTube OAuth refresh failed (invalid_grant). The refresh token "
                            "may be revoked or expired. Re-run authenticate.py and update "
                            "the connection."
                        )
                except ValueError:
                    raise
                except Exception:
                    pass
            resp.raise_for_status()
            data = resp.json()
            self._refreshed_token = data["access_token"]
            self._token_expires_at = time.time() + data.get("expires_in", 3600)
            return self._refreshed_token

        def _request(self, path: str, params: dict[str, Any] | None = None) -> requests.Response:
            """Issue GET with auth and retry on 429/5xx; honor Retry-After when present."""
            params = dict(params or {})
            if self._api_key:
                params["key"] = self._api_key
            url = BASE_URL.rstrip("/") + "/" + path.lstrip("/") if path else BASE_URL
            headers = {}
            if not self._api_key:
                headers["Authorization"] = f"Bearer {self._get_access_token()}"
            backoff = INITIAL_BACKOFF
            for attempt in range(MAX_RETRIES):
                resp = self._session.get(url, params=params, headers=headers, timeout=60)
                if resp.status_code not in RETRIABLE_STATUS_CODES:
                    return resp
                if attempt < MAX_RETRIES - 1:
                    time.sleep(_retry_wait_seconds(resp, backoff))
                    backoff *= 2
            return resp

        def _ensure_ok(
            self, resp: requests.Response, path: str, *, detail: str | None = None
        ) -> None:
            """Raise ValueError with a clear message when the API response is an error."""
            _raise_for_youtube_api_error(resp, path, detail=detail)

        def _drain_paginated_list(
            self,
            path: str,
            base_params: dict[str, Any],
            flatten_fn,
            table_options: dict[str, str],
            *,
            max_results_cap: int = 50,
            max_results_default: int = MAX_RESULTS_DEFAULT,
            max_pages_default: int = 100,
            max_pages_cap: int = 1000,
            detail: str | None = None,
        ) -> list[dict]:
            """Fetch all API pages in one read_table call; pageToken stays internal."""
            max_pages = _parse_max_pages(table_options, max_pages_default, max_pages_cap)
            all_records: list[dict] = []
            page_token: str | None = None
            for _ in range(max_pages):
                params = dict(base_params)
                params["maxResults"] = _max_results(
                    table_options, default=max_results_default, cap=max_results_cap
                )
                if page_token:
                    params["pageToken"] = page_token
                resp = self._request(path, params=params)
                self._ensure_ok(resp, path, detail=detail)
                data = resp.json()
                items = data.get("items") or []
                all_records.extend(flatten_fn(i) for i in items)
                page_token = data.get("nextPageToken")
                if not page_token:
                    break
            return all_records

        def _validate_table(self, table_name: str) -> None:
            if table_name not in SUPPORTED_TABLES:
                raise ValueError(
                    f"Table '{table_name}' is not supported. Supported: {SUPPORTED_TABLES}"
                )

        def list_tables(self) -> list[str]:
            return list(SUPPORTED_TABLES)

        def get_table_schema(self, table_name: str, table_options: dict[str, str]) -> StructType:
            self._validate_table(table_name)
            return TABLE_SCHEMAS[table_name]

        def read_table_metadata(self, table_name: str, table_options: dict[str, str]) -> dict:
            self._validate_table(table_name)
            return dict(TABLE_METADATA[table_name])

        def read_table(
            self,
            table_name: str,
            start_offset: dict,
            table_options: dict[str, str],
        ) -> tuple[Iterator[dict], dict | None]:
            self._validate_table(table_name)
            readers = {
                "channels": self._read_channels,
                "playlists": self._read_playlists,
                "playlist_items": self._read_playlist_items,
                "videos": self._read_videos,
                "search": self._read_search,
                "activities": self._read_activities,
                "comment_threads": self._read_comment_threads,
                "subscriptions": self._read_subscriptions,
                "video_categories": self._read_video_categories,
            }
            return readers[table_name](start_offset or {}, table_options)

        def _read_channels(
            self, start_offset: dict, table_options: dict[str, str]
        ) -> tuple[Iterator[dict], dict | None]:
            params: dict[str, Any] = {"part": "snippet,statistics,contentDetails"}
            channel_ids = (table_options.get("channel_ids") or "").strip()
            if channel_ids:
                params["id"] = channel_ids
            elif table_options.get("for_username"):
                params["forUsername"] = table_options["for_username"]
            elif (table_options.get("mine") or "").lower() in ("true", "1", "yes"):
                params["mine"] = "true"
            else:
                raise ValueError("channels requires channel_ids, for_username, or mine=true")
            records = self._drain_paginated_list(
                "channels", params, _flatten_channel, table_options
            )
            return iter(records), None

        def _read_playlists(
            self, start_offset: dict, table_options: dict[str, str]
        ) -> tuple[Iterator[dict], dict | None]:
            params: dict[str, Any] = {"part": "snippet,contentDetails"}
            pl_ids = (table_options.get("playlist_ids") or "").strip()
            ch_id = (table_options.get("channel_id") or "").strip()
            if pl_ids:
                params["id"] = pl_ids
            elif ch_id:
                params["channelId"] = ch_id
            elif (table_options.get("mine") or "").lower() in ("true", "1", "yes"):
                params["mine"] = "true"
            else:
                raise ValueError("playlists requires playlist_ids, channel_id, or mine=true")
            records = self._drain_paginated_list(
                "playlists", params, _flatten_playlist, table_options
            )
            return iter(records), None

        def _read_playlist_items(
            self, start_offset: dict, table_options: dict[str, str]
        ) -> tuple[Iterator[dict], dict | None]:
            playlist_id = (table_options.get("playlist_id") or "").strip()
            if not playlist_id:
                raise ValueError("playlist_items requires playlist_id in table_options")
            params: dict[str, Any] = {
                "part": "snippet,contentDetails",
                "playlistId": playlist_id,
            }
            records = self._drain_paginated_list(
                "playlistItems", params, _flatten_playlist_item, table_options
            )
            return iter(records), None

        def _read_videos(
            self, start_offset: dict, table_options: dict[str, str]
        ) -> tuple[Iterator[dict], dict | None]:
            video_ids = (table_options.get("video_ids") or "").strip()
            use_chart = (table_options.get("chart") or "").lower() == "mostpopular"
            if video_ids:
                id_batches = _chunked_ids(video_ids, size=50)
                if not id_batches:
                    raise ValueError("videos requires non-empty video_ids")
                records: list[dict] = []
                for id_batch in id_batches:
                    params = {
                        "part": "snippet,statistics,contentDetails",
                        "id": ",".join(id_batch),
                    }
                    resp = self._request("videos", params=params)
                    self._ensure_ok(resp, "videos")
                    items = resp.json().get("items") or []
                    records.extend(_flatten_video(i) for i in items)
                return iter(records), None
            if use_chart:
                params: dict[str, Any] = {
                    "part": "snippet,statistics,contentDetails",
                    "chart": "mostPopular",
                }
                if table_options.get("region_code"):
                    params["regionCode"] = table_options["region_code"]
                if table_options.get("video_category_id"):
                    params["videoCategoryId"] = table_options["video_category_id"]
                records = self._drain_paginated_list(
                    "videos",
                    params,
                    _flatten_video,
                    table_options,
                    max_pages_default=20,
                    max_pages_cap=100,
                )
                return iter(records), None
            raise ValueError("videos requires video_ids or chart=mostPopular")

        def _read_search(
            self, start_offset: dict, table_options: dict[str, str]
        ) -> tuple[Iterator[dict], dict | None]:
            q = (table_options.get("q") or "").strip()
            if not q:
                raise ValueError("search requires q (query) in table_options")
            params: dict[str, Any] = {"part": "snippet", "q": q}
            if table_options.get("type"):
                params["type"] = table_options["type"]
            if table_options.get("channel_id"):
                params["channelId"] = table_options["channel_id"]
            if table_options.get("published_after"):
                params["publishedAfter"] = table_options["published_after"]
            if table_options.get("order"):
                params["order"] = table_options["order"]
            max_pages = _parse_max_pages(table_options, default=10, cap=100)
            all_records: list[dict] = []
            page_token: str | None = None
            position = 0
            for _ in range(max_pages):
                p = dict(params)
                p["maxResults"] = _max_results(table_options, cap=50)
                if page_token:
                    p["pageToken"] = page_token
                resp = self._request("search", params=p)
                self._ensure_ok(resp, "search")
                data = resp.json()
                for it in data.get("items") or []:
                    all_records.append(_flatten_search_result(it, str(position), q))
                    position += 1
                page_token = data.get("nextPageToken")
                if not page_token:
                    break
            return iter(all_records), None

        def _read_activities(
            self, start_offset: dict, table_options: dict[str, str]
        ) -> tuple[Iterator[dict], dict | None]:
            params: dict[str, Any] = {"part": "snippet,contentDetails"}
            ch_id = (table_options.get("channel_id") or "").strip()
            if ch_id:
                params["channelId"] = ch_id
            elif (table_options.get("mine") or "").lower() in ("true", "1", "yes"):
                params["mine"] = "true"
            else:
                raise ValueError("activities requires channel_id or mine=true")
            if table_options.get("published_after"):
                params["publishedAfter"] = table_options["published_after"]
            records = self._drain_paginated_list(
                "activities", params, _flatten_activity, table_options
            )
            return iter(records), None

        def _read_comment_threads(
            self, start_offset: dict, table_options: dict[str, str]
        ) -> tuple[Iterator[dict], dict | None]:
            video_id = (table_options.get("video_id") or "").strip()
            channel_id = (table_options.get("channel_id") or "").strip()
            if video_id:
                params: dict[str, Any] = {"part": "snippet", "videoId": video_id}
            elif channel_id:
                params = {"part": "snippet", "allThreadsRelatedToChannelId": channel_id}
            else:
                raise ValueError("comment_threads requires video_id or channel_id")
            ident = f"video_id={video_id}" if video_id else f"channel_id={channel_id}"
            records = self._drain_paginated_list(
                "commentThreads",
                params,
                _flatten_comment_thread,
                table_options,
                max_results_cap=100,
                max_results_default=MAX_RESULTS_COMMENT_THREADS,
                detail=ident,
            )
            return iter(records), None

        def _read_subscriptions(
            self, start_offset: dict, table_options: dict[str, str]
        ) -> tuple[Iterator[dict], dict | None]:
            params: dict[str, Any] = {"part": "snippet"}
            ch_id = (table_options.get("channel_id") or "").strip()
            if ch_id:
                params["channelId"] = ch_id
            elif (table_options.get("mine") or "").lower() in ("true", "1", "yes"):
                params["mine"] = "true"
            else:
                raise ValueError("subscriptions requires channel_id or mine=true")
            records = self._drain_paginated_list(
                "subscriptions", params, _flatten_subscription, table_options
            )
            return iter(records), None

        def _read_video_categories(
            self, start_offset: dict, table_options: dict[str, str]
        ) -> tuple[Iterator[dict], dict | None]:
            region_code = (table_options.get("region_code") or "").strip()
            if not region_code:
                raise ValueError(
                    "video_categories requires region_code in table_options "
                    "(ISO 3166-1 alpha-2, e.g. US)"
                )
            params: dict[str, Any] = {"part": "snippet", "regionCode": region_code}
            records = self._drain_paginated_list(
                "videoCategories",
                params,
                _flatten_video_category,
                table_options,
                max_pages_default=20,
                max_pages_cap=100,
            )
            return iter(records), None


    ########################################################
    # src/databricks/labs/community_connector/sparkpds/lakeflow_datasource.py
    ########################################################

    LakeflowConnectImpl = YouTubeLakeflowConnect
    # Constant option or column names
    METADATA_TABLE = "_community_table_metadata"
    NAMESPACES_TABLE = "_community_namespaces"
    TABLES_TABLE = "_community_tables"
    VIRTUAL_TABLES = (METADATA_TABLE, NAMESPACES_TABLE, TABLES_TABLE)
    TABLE_NAME = "tableName"
    TABLE_NAME_LIST = "tableNameList"
    TABLE_CONFIGS = "tableConfigs"
    IS_DELETE_FLOW = "isDeleteFlow"
    NAMESPACE_PREFIX = "namespacePrefix"
    NAMESPACE = "namespace"


    def _decode_list_of_str_option(option_name: str, value: str | None) -> list[str] | None:
        """Decode and validate a JSON-encoded ``list[str]`` Spark option.

        Returns ``None`` if the option is absent; otherwise the parsed list.
        Raises ``ValueError`` with the offending value if the JSON is malformed
        or the decoded value is not a list of strings.
        """
        if value is None:
            return None
        try:
            decoded = json.loads(value)
        except json.JSONDecodeError as e:
            raise ValueError(
                f"option '{option_name}' must be a JSON-encoded list[str]; "
                f"got non-JSON value: {value!r}"
            ) from e
        if not isinstance(decoded, list) or not all(isinstance(s, str) for s in decoded):
            raise ValueError(
                f"option '{option_name}' must be a JSON-encoded list[str]; "
                f"got: {decoded!r}"
            )
        return decoded


    def _decode_dict_option(option_name: str, value: str | None) -> dict:
        """Decode and validate a JSON-encoded ``dict`` Spark option."""
        if value is None:
            return {}
        try:
            decoded = json.loads(value)
        except json.JSONDecodeError as e:
            raise ValueError(
                f"option '{option_name}' must be a JSON-encoded dict; "
                f"got non-JSON value: {value!r}"
            ) from e
        if not isinstance(decoded, dict):
            raise ValueError(
                f"option '{option_name}' must be a JSON-encoded dict; got: {decoded!r}"
            )
        return decoded


    def _parse_or_passthrough_records(records, schema: StructType):
        """Convert row records while passing PyArrow RecordBatches directly to Spark."""
        iterator = iter(records)
        try:
            first = next(iterator)
        except StopIteration:
            return iter(())

        first_type = type(first)
        if first_type.__name__ == "RecordBatch" and first_type.__module__.startswith("pyarrow."):
            return chain((first,), iterator)

        return chain(
            (parse_value(first, schema),),
            map(lambda value: parse_value(value, schema), iterator),
        )


    # PySpark's DataSource API requires camelCase method names and inherits
    # semantics from the parent class, so per-method docstrings are redundant.
    # pylint: disable=invalid-name,missing-function-docstring
    class LakeflowStreamReader(SimpleDataSourceStreamReader, SupportsTriggerAvailableNow):
        """
        Implements a data source stream reader for Lakeflow Connect.
        Currently, only the simpleStreamReader is implemented, which uses a
        more generic protocol suitable for most data sources that support
        incremental loading.
        """

        def __init__(
            self,
            options: dict[str, str],
            schema: StructType,
            lakeflow_connect: LakeflowConnect,
        ):
            self.options = options
            self.lakeflow_connect = lakeflow_connect
            self.schema = schema

        def initialOffset(self):
            return {}

        def read(self, start: dict) -> (Iterator[tuple], dict):
            is_delete_flow = self.options.get(IS_DELETE_FLOW) == "true"
            # Strip delete flow options before passing to connector
            table_options = {
                k: v for k, v in self.options.items() if k != IS_DELETE_FLOW
            }

            if is_delete_flow:
                records, offset = self.lakeflow_connect.read_table_deletes(
                    self.options[TABLE_NAME], start, table_options
                )
            else:
                records, offset = self.lakeflow_connect.read_table(
                    self.options[TABLE_NAME], start, table_options
                )
            rows = _parse_or_passthrough_records(records, self.schema)
            return rows, offset

        def readBetweenOffsets(self, start: dict, end: dict) -> Iterator[tuple]:
            # TODO: This does not ensure the records returned are identical across repeated calls.
            # For append-only tables, the data source must guarantee that reading from the same
            # start offset will always yield the same set of records.
            # For tables ingested as incremental CDC, it is only necessary that no new changes
            # are missed in the returned records.
            return self.read(start)[0]

        def prepareForTriggerAvailableNow(self) -> None:
            # No need to do anything special here. Everything is handled in the __init__ method.
            pass


    class LakeflowPartitionedStreamReader(DataSourceStreamReader, SupportsTriggerAvailableNow):
        """Proxy that bridges SupportsPartitionedStream to PySpark's DataSourceStreamReader.

        Used when a connector implements the SupportsPartitionedStream mixin to
        support partitioned streaming reads across Spark executors.
        """

        def __init__(
            self,
            options: dict[str, str],
            schema: StructType,
            lakeflow_connect: LakeflowConnect,
        ):
            self.options = options
            self.schema = schema
            self.lakeflow_connect = lakeflow_connect
            self.table_name = options[TABLE_NAME]
            self.table_options = {k: v for k, v in options.items() if k != IS_DELETE_FLOW}

        def initialOffset(self):
            return {}

        def getDefaultReadLimit(self):
            # Admission control is the connector's responsibility (e.g. via
            # window_days, max_records_per_batch), not the engine's.  Always
            # ask the engine for ReadAllAvailable.
            return ReadAllAvailable()

        def latestOffset(self, start: dict, limit) -> dict:
            # We declared ReadAllAvailable via getDefaultReadLimit; the engine
            # must respect it.  Anything else means admission-control expectations
            # we do not support — fail loudly rather than silently ignore.
            if not isinstance(limit, ReadAllAvailable):
                raise ValueError(
                    f"LakeflowPartitionedStreamReader only supports ReadAllAvailable; "
                    f"got {type(limit).__name__}. Micro-batch sizing must be controlled "
                    f"by the connector implementation (table_options), not the engine."
                )
            return self.lakeflow_connect.latest_offset(
                self.table_name, self.table_options, start
            )

        def partitions(self, start: dict, end: dict):
            partition_descs = self.lakeflow_connect.get_partitions(
                self.table_name, self.table_options, start, end
            )
            return [InputPartition(json.dumps(p)) for p in partition_descs]

        def read(self, partition: InputPartition):
            partition_desc = json.loads(partition.value)
            records = self.lakeflow_connect.read_partition(
                self.table_name, partition_desc, self.table_options
            )
            return _parse_or_passthrough_records(records, self.schema)

        def prepareForTriggerAvailableNow(self) -> None:
            # No need to do anything special here. Everything is handled in the __init__ method.
            pass


    class LakeflowBatchReader(DataSourceReader):
        def __init__(
            self,
            options: dict[str, str],
            schema: StructType,
            lakeflow_connect: LakeflowConnect,
        ):
            self.options = options
            self.schema = schema
            self.lakeflow_connect = lakeflow_connect
            self.table_name = options[TABLE_NAME]
            self._supports_partition = isinstance(lakeflow_connect, SupportsPartition)

        def partitions(self):
            if self._supports_partition and self.table_name not in VIRTUAL_TABLES:
                try:
                    partition_descs = self.lakeflow_connect.get_partitions(
                        self.table_name, self.options
                    )
                    return [InputPartition(json.dumps(p)) for p in partition_descs]
                except Exception:
                    self._supports_partition = False
            return [InputPartition(None)]

        def read(self, partition):
            if self.table_name == METADATA_TABLE:
                records = self._read_table_metadata()
            elif self.table_name == NAMESPACES_TABLE:
                records = self._read_namespaces()
            elif self.table_name == TABLES_TABLE:
                records = self._read_tables()
            elif self._supports_partition and partition.value is not None:
                partition_desc = json.loads(partition.value)
                records = self.lakeflow_connect.read_partition(
                    self.table_name, partition_desc, self.options
                )
            else:
                records, _ = self.lakeflow_connect.read_table(self.table_name, None, self.options)
            return _parse_or_passthrough_records(records, self.schema)

        def _read_table_metadata(self):
            table_names = _decode_list_of_str_option(
                TABLE_NAME_LIST, self.options.get(TABLE_NAME_LIST)
            ) or []
            table_configs = _decode_dict_option(
                TABLE_CONFIGS, self.options.get(TABLE_CONFIGS)
            )
            all_records = []
            # Preserve caller-supplied table order — caller controls it.
            for table in table_names:
                metadata = self.lakeflow_connect.read_table_metadata(
                    table, table_configs.get(table, {})
                )
                all_records.append({TABLE_NAME: table, **metadata})
            return all_records

        def _read_namespaces(self):
            # Connectors without SupportsNamespaces are flat — no rows.
            if not isinstance(self.lakeflow_connect, SupportsNamespaces):
                return []
            prefix = _decode_list_of_str_option(
                NAMESPACE_PREFIX, self.options.get(NAMESPACE_PREFIX)
            )
            namespaces = self.lakeflow_connect.list_namespaces(prefix)
            # Sort framework-side for deterministic output regardless of
            # connector iteration order.
            return [{"namespace": ns} for ns in sorted(namespaces)]

        def _read_tables(self):
            namespace_supplied = NAMESPACE in self.options
            if isinstance(self.lakeflow_connect, SupportsNamespaces):
                if not namespace_supplied:
                    raise ValueError(
                        f"option '{NAMESPACE}' is required when reading "
                        f"'{TABLES_TABLE}' against a connector that implements "
                        f"SupportsNamespaces. Pass a JSON-encoded list[str] "
                        f"(use '[]' for root-level tables; walk the tree via "
                        f"'{NAMESPACES_TABLE}' to enumerate every namespace)."
                    )
                namespace = _decode_list_of_str_option(
                    NAMESPACE, self.options[NAMESPACE]
                )
                tables = self.lakeflow_connect.list_tables_in_namespace(namespace)
                return [
                    {"namespace": namespace, TABLE_NAME: tn}
                    for tn in sorted(tables)
                ]
            # Flat connector path. Reject a stray `namespace` option — the
            # caller probably mistook this connector for namespace-aware and
            # silently ignoring the option would mask the bug.
            if namespace_supplied:
                raise ValueError(
                    f"option '{NAMESPACE}' was supplied but the connector does "
                    f"not implement SupportsNamespaces. Either omit the option "
                    f"or use a namespace-aware connector."
                )
            return [
                {"namespace": [], TABLE_NAME: tn}
                for tn in sorted(self.lakeflow_connect.list_tables())
            ]


    class LakeflowSource(DataSource):
        """
        PySpark DataSource base for Lakeflow Connect.

        Two ways the connector implementation is bound:

        - Per-source subclass (wheel / multi-file deployment): subclass and set
          ``_lakeflow_connect_cls``::

              class GmailDataSource(LakeflowSource):
                  _lakeflow_connect_cls = GmailLakeflowConnect

              spark.dataSource.register(GmailDataSource)

        - Merged single-file deployment (SDP): ``_lakeflow_connect_cls`` is left
          ``None`` and the connector is taken from the module-level
          ``LakeflowConnectImpl`` placeholder, which the merge script substitutes
          with the actual implementation class.
        """

        # Per-source subclasses set this. Left ``None`` on the base so the merged
        # single-file path falls back to the ``LakeflowConnectImpl`` placeholder.
        _lakeflow_connect_cls = None

        # Spark format name. Defaults to "lakeflow_connect" because Unity Catalog
        # connection-option injection looks for that exact string. A per-source
        # subclass may override this with its source name once it no longer relies
        # on UC injection (see the commented override in each source's __init__.py).
        _format_name = "lakeflow_connect"

        def __init__(self, options):
            self.options = options
            table = options.get(TABLE_NAME)
            # Catch typos against the framework's reserved virtual-table namespace
            # early — falling through to the connector with an unknown
            # `_community_*` name yields a confusing per-connector error.
            if table and table.startswith("_community_") and table not in VIRTUAL_TABLES:
                raise ValueError(
                    f"unknown framework virtual table '{table}'. Valid framework "
                    f"virtual tables are: {', '.join(VIRTUAL_TABLES)}. "
                    f"For a regular source table, use a name that does not start "
                    f"with '_community_'."
                )
            # Per-source subclasses bind the implementation via _lakeflow_connect_cls.
            # The merged single-file path leaves it None and relies on the
            # LakeflowConnectImpl placeholder (substituted by the merge script).
            connect_cls = type(self)._lakeflow_connect_cls or LakeflowConnectImpl
            self.lakeflow_connect = connect_cls(options)  # pylint: disable=abstract-class-instantiated

        @classmethod
        def name(cls):
            return cls._format_name

        def schema(self):
            table = self.options[TABLE_NAME]
            if table == METADATA_TABLE:
                return StructType(
                    [
                        StructField(TABLE_NAME, StringType(), False),
                        StructField("primary_keys", ArrayType(StringType()), True),
                        StructField("cursor_field", StringType(), True),
                        StructField("ingestion_type", StringType(), True),
                    ]
                )
            if table == NAMESPACES_TABLE:
                return StructType(
                    [
                        StructField("namespace", ArrayType(StringType()), False),
                    ]
                )
            if table == TABLES_TABLE:
                return StructType(
                    [
                        StructField("namespace", ArrayType(StringType()), False),
                        StructField(TABLE_NAME, StringType(), False),
                    ]
                )
            return self.lakeflow_connect.get_table_schema(table, self.options)

        def reader(self, schema: StructType):
            return LakeflowBatchReader(self.options, schema, self.lakeflow_connect)

        def streamReader(self, schema: StructType):
            # Use the partitioned DataSourceStreamReader when the connector
            # implements SupportsPartitionedStream and the table opts in.
            # Otherwise, delegate to super() which raises PySparkNotImplementedError,
            # causing Spark to fall back to simpleStreamReader().
            if isinstance(self.lakeflow_connect, SupportsPartitionedStream):
                table = self.options[TABLE_NAME]
                if self.lakeflow_connect.is_partitioned(table):
                    return LakeflowPartitionedStreamReader(self.options, schema, self.lakeflow_connect)
            return super().streamReader(schema)

        def simpleStreamReader(self, schema: StructType):
            return LakeflowStreamReader(self.options, schema, self.lakeflow_connect)


    spark.dataSource.register(LakeflowSource)
