# ==============================================================================
# Merged Lakeflow Source: adme
# ==============================================================================
# This file is auto-generated by tools/scripts/merge_python_source.py
# Do not edit manually. Make changes to the source files instead.
# ==============================================================================

from abc import ABC, abstractmethod
from datetime import datetime, timedelta, timezone
from decimal import Decimal
from itertools import chain
from typing import Any, Iterator, Sequence
import json
import os
import re
import time

from pyspark.sql import Row
from pyspark.sql.datasource import (
    DataSource,
    DataSourceReader,
    DataSourceStreamReader,
    InputPartition,
    SimpleDataSourceStreamReader,
)
from pyspark.sql.streaming.datasource import ReadAllAvailable, SupportsTriggerAvailableNow
from pyspark.sql.types import (
    ArrayType,
    BinaryType,
    BooleanType,
    DataType,
    DateType,
    DecimalType,
    DoubleType,
    FloatType,
    IntegerType,
    LongType,
    MapType,
    StringType,
    StructField,
    StructType,
    TimestampType,
    VariantType,
    VariantVal,
)
import base64
import requests
import threading


def register_lakeflow_source(spark):
    """Register the Lakeflow Python source with Spark."""

    ########################################################
    # src/databricks/labs/community_connector/libs/utils.py
    ########################################################

    def _parse_struct(value: Any, field_type: StructType) -> Row:
        """Parse a dictionary into a PySpark Row based on StructType schema."""
        if not isinstance(value, dict):
            raise ValueError(f"Expected a dictionary for StructType, got {type(value)}")
        # Spark Python -> Arrow conversion require missing StructType fields to be assigned None.
        if value == {}:
            raise ValueError(
                "field in StructType cannot be an empty dict. "
                "Please assign None as the default value instead."
            )
        field_dict = {}
        for field in field_type.fields:
            if field.name in value:
                field_dict[field.name] = parse_value(value.get(field.name), field.dataType)
            elif field.nullable:
                field_dict[field.name] = None
            else:
                raise ValueError(f"Field {field.name} is not nullable but not found in the input")
        return Row(**field_dict)


    def _parse_array(value: Any, field_type: ArrayType) -> list:
        """Parse a list into a PySpark array based on ArrayType schema."""
        if not isinstance(value, list):
            if field_type.containsNull:
                return [parse_value(value, field_type.elementType)]
            raise ValueError(f"Expected a list for ArrayType, got {type(value)}")
        return [parse_value(v, field_type.elementType) for v in value]


    def _parse_map(value: Any, field_type: MapType) -> dict:
        """Parse a dictionary into a PySpark map based on MapType schema."""
        if not isinstance(value, dict):
            raise ValueError(f"Expected a dictionary for MapType, got {type(value)}")
        return {
            parse_value(k, field_type.keyType): parse_value(v, field_type.valueType)
            for k, v in value.items()
        }


    def _parse_string(value: Any) -> str:
        """Convert value to string."""
        return str(value)


    def _parse_integer(value: Any) -> int:
        """Convert value to integer."""
        if isinstance(value, str) and value.strip():
            return int(float(value)) if "." in value else int(value)
        if isinstance(value, (int, float)):
            return int(value)
        raise ValueError(f"Cannot convert {value} to integer")


    def _parse_float(value: Any) -> float:
        """Convert value to float."""
        return float(value)


    def _parse_decimal(value: Any) -> Decimal:
        """Convert value to Decimal."""
        return Decimal(value) if isinstance(value, str) and value.strip() else Decimal(str(value))


    def _parse_boolean(value: Any) -> bool:
        """Convert value to boolean."""
        if isinstance(value, str):
            lowered = value.lower()
            if lowered in ("true", "t", "yes", "y", "1"):
                return True
            if lowered in ("false", "f", "no", "n", "0"):
                return False
        return bool(value)


    def _parse_date(value: Any) -> datetime.date:
        """Convert value to date."""
        if isinstance(value, str):
            for fmt in ("%Y-%m-%d", "%m/%d/%Y", "%d-%m-%Y", "%Y/%m/%d"):
                try:
                    return datetime.strptime(value, fmt).date()
                except ValueError:
                    continue
            return datetime.fromisoformat(value).date()
        if isinstance(value, datetime):
            return value.date()
        raise ValueError(f"Cannot convert {value} to date")


    def _parse_timestamp(value: Any) -> datetime:
        """Convert value to timestamp."""
        if isinstance(value, str):
            ts_value = value.replace("Z", "+00:00") if value.endswith("Z") else value
            try:
                return datetime.fromisoformat(ts_value)
            except ValueError:
                for fmt in ("%Y-%m-%d %H:%M:%S", "%Y/%m/%d %H:%M:%S"):
                    try:
                        return datetime.strptime(ts_value, fmt)
                    except ValueError:
                        continue
        elif isinstance(value, (int, float)):
            return datetime.fromtimestamp(value)
        elif isinstance(value, datetime):
            return value
        raise ValueError(f"Cannot convert {value} to timestamp")


    def _decode_string_to_bytes(value: str) -> bytes:
        """Try to decode a string as base64, then hex, then UTF-8."""
        try:
            return base64.b64decode(value)
        except Exception:
            pass
        try:
            return bytes.fromhex(value)
        except Exception:
            pass
        return value.encode("utf-8")


    def _parse_binary(value: Any) -> bytes:
        """Convert value to bytes. Tries base64, then hex, then UTF-8 for strings."""
        if isinstance(value, bytes):
            return value
        if isinstance(value, bytearray):
            return bytes(value)
        if isinstance(value, str):
            return _decode_string_to_bytes(value)
        if isinstance(value, list):
            return bytes(value)
        return str(value).encode("utf-8")


    # Mapping of primitive types to their parser functions
    _PRIMITIVE_PARSERS = {
        StringType: _parse_string,
        IntegerType: _parse_integer,
        LongType: _parse_integer,
        FloatType: _parse_float,
        DoubleType: _parse_float,
        DecimalType: _parse_decimal,
        BooleanType: _parse_boolean,
        DateType: _parse_date,
        TimestampType: _parse_timestamp,
        BinaryType: _parse_binary,
    }


    def parse_value(value: Any, field_type: DataType) -> Any:  # pylint: disable=too-many-return-statements
        """
        Converts a JSON value into a PySpark-compatible data type based on the provided field type.
        """
        if value is None:
            return None

        # Handle complex types
        if isinstance(field_type, StructType):
            return _parse_struct(value, field_type)
        if isinstance(field_type, ArrayType):
            return _parse_array(value, field_type)
        if isinstance(field_type, MapType):
            return _parse_map(value, field_type)

        # Handle VariantType
        if isinstance(field_type, VariantType):
            return VariantVal.parseJson(value) if isinstance(value, str) else value

        # Handle primitive types via type-based lookup
        try:
            field_type_class = type(field_type)
            if field_type_class in _PRIMITIVE_PARSERS:
                return _PRIMITIVE_PARSERS[field_type_class](value)

            # Check for custom UDT handling
            if hasattr(field_type, "fromJson"):
                return field_type.fromJson(value)

            raise TypeError(f"Unsupported field type: {field_type}")
        except (ValueError, TypeError) as e:
            raise ValueError(f"Error converting '{value}' ({type(value)}) to {field_type}: {str(e)}")


    ########################################################
    # src/databricks/labs/community_connector/interface/lakeflow_connect.py
    ########################################################

    class LakeflowConnect(ABC):
        """Base interface that each source connector must implement.

        Subclass this and implement all abstract methods to create a connector that
        integrates with the community connector library and ingestion pipeline.
        """

        def __init__(self, options: dict[str, str]) -> None:
            """
            Initialize the source connector with parameters needed to connect to the source.
            Args:
                options: A dictionary of parameters like authentication tokens, table names,
                    and other configurations.
            """
            self.options = options

        @abstractmethod
        def list_tables(self) -> list[str]:
            """
            List names of all the tables supported by the source connector.
            The list could either be a static list or retrieved from the source via API.
            Returns:
                A list of table names.
            """

        @abstractmethod
        def get_table_schema(
            self, table_name: str, table_options: dict[str, str]
        ) -> StructType:
            """
            Fetch the schema of a table.
            Args:
                table_name: The name of the table to fetch the schema for.
                table_options: A dictionary of options for accessing the table. For example,
                    the source API may require extra parameters needed to fetch the schema.
                    If there are no additional options required, you can ignore this
                    parameter, and no options will be provided during execution.
                    Only add parameters to table_options if they are essential for accessing
                    or retrieving the data (such as specifying table namespaces).
            Returns:
                A StructType object representing the schema of the table.
            """

        @abstractmethod
        def read_table_metadata(
            self, table_name: str, table_options: dict[str, str]
        ) -> dict:
            """
            Fetch the metadata of a table.
            Args:
                table_name: The name of the table to fetch the metadata for.
                table_options: A dictionary of options for accessing the table. For example,
                    the source API may require extra parameters needed to fetch the metadata.
                    If there are no additional options required, you can ignore this
                    parameter, and no options will be provided during execution.
                    Only add parameters to table_options if they are essential for accessing
                    or retrieving the data (such as specifying table namespaces).
            Returns:
                A dictionary containing the metadata of the table. It should include the
                following keys:
                    - primary_keys: List of string names of the primary key columns of
                        the table.
                    - cursor_field: The name of the field to use as a cursor for
                        incremental loading.
                    - ingestion_type: The type of ingestion to use for the table. It
                        should be one of the following values:
                        - "snapshot": For snapshot loading.
                        - "cdc": Capture incremental changes (no delete support).
                        - "cdc_with_deletes": Capture incremental changes with delete
                            support. Requires implementing read_table_deletes().
                        - "append": Incremental append.
            """

        @abstractmethod
        def read_table(
            self, table_name: str, start_offset: dict, table_options: dict[str, str]
        ) -> tuple[Iterator[dict], dict]:
            """
            Read the records of a table and return an iterator of records and an offset.

            The framework calls this method repeatedly to paginate through data.
            start_offset is None only on the very first call of the very first run
            of a connector. On subsequent runs the framework resumes from the last
            checkpointed offset, so start_offset will already be populated. Each
            call returns (records, end_offset). The framework passes end_offset as
            start_offset to the next call. Pagination stops when the returned
            offset equals start_offset (i.e., no more data).

            For tables that cannot be incrementally read, return None as the offset to
            read the entire table in one batch. Non-checkpointable synthetic offsets can
            be used to split the data into multiple batches.

            Args:
                table_name: The name of the table to read.
                start_offset: The offset to start reading from. None only on the
                    first call of the first run; on subsequent runs it carries the
                    checkpointed offset from the previous run.
                table_options: A dictionary of options for accessing the table. For example,
                    the source API may require extra parameters needed to read the table.
                    If there are no additional options required, you can ignore this
                    parameter, and no options will be provided during execution.
                    Only add parameters to table_options if they are essential for accessing
                    or retrieving the data (such as specifying table namespaces).
            Returns:
                A two-element tuple of (records, offset).
                records: An iterator of records as JSON-compatible dicts, or
                    ``pyarrow.RecordBatch`` objects for the Spark direct-Arrow path.
                    Do NOT convert row values according to get_table_schema(); the
                    framework handles row conversion.
                offset: A dict representing the position after this batch.
            """

        def read_table_deletes(
            self, table_name: str, start_offset: dict, table_options: dict[str, str]
        ) -> tuple[Iterator[dict], dict]:
            """
            Read deleted records from a table for CDC delete synchronization.
            This method is called when ingestion_type is "cdc_with_deletes" to fetch
            records that have been deleted from the source system.

            This method follows the same pagination and offset protocol as read_table:
            the framework calls it repeatedly, passing the previous end_offset as
            start_offset, until the returned offset equals start_offset.

            Override this method if any of your tables use ingestion_type
            "cdc_with_deletes". The default implementation raises NotImplementedError.

            The returned records should have at minimum the primary key fields and
            cursor field populated. Other fields can be null.

            Args:
                table_name: The name of the table to read deleted records from.
                start_offset: The offset to start reading from (same format as read_table).
                table_options: A dictionary of options for accessing the table.
            Returns:
                A two-element tuple of (records, offset).
                records: An iterator of deleted records (must include primary keys and cursor).
                offset: A dict (same format as read_table).
            """
            raise NotImplementedError(
                "read_table_deletes() must be implemented when ingestion_type is 'cdc_with_deletes'"
            )


    ########################################################
    # src/databricks/labs/community_connector/interface/supports_partition.py
    ########################################################

    class SupportsPartition(ABC):
        """Mixin for connectors that support partitioned reads across Spark executors.

        Must be used together with LakeflowConnect. Implement this when your
        connector can split work into partitions that Spark distributes to workers,
        instead of reading all data in one partition batch.

        Usage::

            class MyConnector(LakeflowConnect, SupportsPartition):
                ...
        """

        @abstractmethod
        def get_partitions(
            self,
            table_name: str,
            table_options: dict[str, str],
        ) -> Sequence[dict]:
            """Return partition descriptors for reading data.

            Each returned dict is passed to :meth:`read_partition` on an executor.

            Args:
                table_name: The name of the table.
                table_options: A dictionary of options for accessing the table.
            Returns:
                A sequence of partition descriptor dicts. Each dict must be
                JSON-serialisable (primitive types only).
            """

        @abstractmethod
        def read_partition(
            self, table_name: str, partition: dict, table_options: dict[str, str]
        ) -> Iterator[dict]:
            """Read records for a single partition.

            This method runs on Spark executors and must be self-contained.

            Args:
                table_name: The name of the table.
                partition: One of the partition dicts returned by
                    :meth:`get_partitions`.
                table_options: A dictionary of options for accessing the table.
            Returns:
                An iterator of JSON-compatible record dictionaries or PyArrow
                RecordBatch objects for Spark's direct-Arrow reader path.
            """


    class SupportsPartitionedStream(SupportsPartition):
        """Mixin for connectors that support partitioned streaming reads.

        Extends :class:`SupportsPartition` with offset awareness for streaming
        micro-batches. A connector implementing this mixin automatically supports
        both partitioned batch reads (via the inherited interface) and partitioned
        streaming reads.

        Usage::

            class MyConnector(LakeflowConnect, SupportsPartitionedStream):
                ...
        """

        def is_partitioned(self, table_name: str) -> bool:
            """Return whether the given table supports partitioned streaming.

            The default returns True. Override to return False for tables that
            should fall back to simpleStreamReader.

            Args:
                table_name: The name of the table.
                table_options: A dictionary of options for accessing the table.
            """
            return True

        @abstractmethod
        def latest_offset(
            self,
            table_name: str,
            table_options: dict[str, str],
            start_offset: dict | None = None,
        ) -> dict:
            """Return the most recent offset available for the table.

            Called by Spark on every micro-batch to discover new data.

            Micro-batch sizing (by row count, time window, etc.) is entirely the
            connector's responsibility — use table_options (e.g. ``window_days``,
            ``max_records_per_batch``) to control it.  The framework always
            requests "all available" and does not pass an admission-control
            hint here.

            Args:
                table_name: The name of the table.
                table_options: A dictionary of options for accessing the table.
                start_offset: The current committed offset.  ``{}`` on the very
                    first call (from ``initialOffset``), then the last returned
                    end_offset on each subsequent call.
            Returns:
                A dict whose keys and values are primitive types (str, int, bool).
            """

        @abstractmethod
        def get_partitions(
            self,
            table_name: str,
            table_options: dict[str, str],
            start_offset: dict | None = None,
            end_offset: dict | None = None,
        ) -> Sequence[dict]:
            """Return partition descriptors for reading data.

            Each returned dict is passed to :meth:`read_partition` on an executor.

            For batch reads, ``start_offset`` and ``end_offset`` are both None —
            return partitions covering the entire table.

            For streaming micro-batches, they delimit the offset range — return
            partitions covering that range, or an empty sequence when
            ``start_offset == end_offset``.

            Args:
                table_name: The name of the table.
                table_options: A dictionary of options for accessing the table.
                start_offset: The start offset (exclusive), or None for batch.
                end_offset: The end offset (inclusive), or None for batch.
            Returns:
                A sequence of partition descriptor dicts. Each dict must be
                JSON-serialisable (primitive types only).
            """


    ########################################################
    # src/databricks/labs/community_connector/interface/supports_namespaces.py
    ########################################################

    class SupportsNamespaces(ABC):
        """Mixin for connectors whose tables live under hierarchical namespaces.

        A namespace is a path of zero or more string segments (e.g. ``["org",
        "repo"]`` for GitHub, ``["tenant", "project"]`` for Azure DevOps).
        Connectors with a flat catalog do not need this mixin — the framework
        falls back to :meth:`LakeflowConnect.list_tables` and reports each table
        with an empty namespace.

        Output ordering on the ``_community_namespaces`` and ``_community_tables``
        Spark virtual tables is normalized by the framework via ``sorted(...)``,
        so connector implementations of :meth:`list_namespaces` and
        :meth:`list_tables_in_namespace` are free to return their results in
        any order (including from a :class:`set` or generator).

        Must be used together with :class:`LakeflowConnect`.

        Usage::

            class MyConnector(LakeflowConnect, SupportsNamespaces):
                ...
        """

        @abstractmethod
        def list_namespaces(
            self,
            prefix: list[str] | None = None,
        ) -> list[list[str]]:
            """Return the immediate child namespaces under ``prefix``.

            This method returns one level of *namespace* children only — it
            never returns tables. A namespace can hold tables and child
            namespaces independently; callers must always call
            :meth:`list_tables_in_namespace` for every namespace they care
            about, regardless of whether :meth:`list_namespaces` returned
            children for it. An empty return value just means there are no
            further child namespaces under ``prefix``.

            Walk the full tree by recursing on each returned child.

            Args:
                prefix: A namespace path under which to list children. ``None`` or
                    an empty list lists the root-level namespaces.
            Returns:
                A list of full namespace paths (each path includes the prefix).
            """

        @abstractmethod
        def list_tables_in_namespace(
            self,
            namespace: list[str],
        ) -> list[str]:
            """Return the table names that live directly under ``namespace``.

            Callers that want every table across the whole catalog walk the
            namespace tree via :meth:`list_namespaces` and call this method
            once per leaf — there is no "list everything" shortcut.

            Args:
                namespace: The namespace path. An empty list ``[]`` selects
                    root-level tables (those that live outside any namespace).
            Returns:
                A list of table names. The full ``(namespace, table_name)``
                row exposed on ``_community_tables`` is reconstructed by the
                framework from the namespace the caller already supplied, so
                the connector does not need to echo it back.
            """


    ########################################################
    # src/databricks/labs/community_connector/sources/adme/adme_schemas.py
    ########################################################

    TABLE_TO_KIND_QUERY: dict[str, str] = {
        "Wellbore": "osdu:wks:master-data--Wellbore:*",
        "Reservoir": "osdu:wks:master-data--Reservoir:*",
        "Rock_and_Fluid": "osdu:wks:master-data--Sample:*",
    }

    TABLE_TO_KIND_CANONICAL: dict[str, str] = {
        "Wellbore": "osdu:wks:master-data--Wellbore:1.0.0",
        "Reservoir": "osdu:wks:master-data--Reservoir:1.2.0",
        "Rock_and_Fluid": "osdu:wks:master-data--Sample:2.1.0",
    }

    SUPPORTED_TABLES: list[str] = list(TABLE_TO_KIND_QUERY.keys())


    # ---------------------------------------------------------------------------
    # Common OSDU envelope fields shared by every record kind
    # ---------------------------------------------------------------------------
    def _envelope_fields() -> list[StructField]:
        return [
            StructField("id", StringType(), False),
            StructField("kind", StringType(), True),
            # ``version`` is microsecond-precision Unix epoch encoded as int64.
            StructField("version", LongType(), True),
            StructField("createTime", StringType(), True),
            StructField("createUser", StringType(), True),
            StructField("modifyTime", StringType(), True),
            StructField("modifyUser", StringType(), True),
            # acl/legal are small structured objects; flatten the most useful
            # arrays so they're queryable without a JSON parse.
            StructField("acl_owners", ArrayType(StringType()), True),
            StructField("acl_viewers", ArrayType(StringType()), True),
            StructField("legal_legaltags", ArrayType(StringType()), True),
            StructField("legal_status", StringType(), True),
            StructField(
                "legal_otherRelevantDataCountries", ArrayType(StringType()), True
            ),
            # Free-form OSDU bits we keep as JSON for fidelity without
            # committing to a specific Spark struct shape.
            StructField("tags_json", StringType(), True),
            StructField("meta_json", StringType(), True),
            # Full original ``data`` envelope as JSON — gives downstream
            # users an escape hatch for fields not lifted to typed columns.
            StructField("data_json", StringType(), True),
        ]


    # ---------------------------------------------------------------------------
    # Wellbore (osdu:wks:master-data--Wellbore:1.0.0)
    # ---------------------------------------------------------------------------
    WELLBORE_SCHEMA: StructType = StructType(
        _envelope_fields()
        + [
            StructField("FacilityID", StringType(), True),
            StructField("FacilityName", StringType(), True),
            StructField("FacilityTypeID", StringType(), True),
            StructField("WellID", StringType(), True),
            StructField("KickOffWellboreID", StringType(), True),
            StructField("StatusSummary", StringType(), True),
            StructField("TargetFormation", StringType(), True),
            StructField("FacilityNameAliases_json", StringType(), True),
            StructField("FacilityOperators_json", StringType(), True),
            StructField("VerticalMeasurements_json", StringType(), True),
            StructField("SpatialLocation_json", StringType(), True),
            StructField("GeoContexts_json", StringType(), True),
            StructField("DrillingReasons_json", StringType(), True),
            StructField("InitialCompletion_json", StringType(), True),
            StructField("ExtensionProperties_json", StringType(), True),
        ]
    )


    # ---------------------------------------------------------------------------
    # Reservoir (osdu:wks:master-data--Reservoir:1.2.0)
    # ---------------------------------------------------------------------------
    RESERVOIR_SCHEMA: StructType = StructType(
        _envelope_fields()
        + [
            StructField("ReservoirID", StringType(), True),
            StructField("ReservoirName", StringType(), True),
            StructField("ReservoirType", StringType(), True),
            StructField("ReservoirDescription", StringType(), True),
            StructField("FieldID", StringType(), True),
            StructField("BasinID", StringType(), True),
            StructField("FormationID", StringType(), True),
            StructField("FluidTypeID", StringType(), True),
            StructField("DepthTopMD", DoubleType(), True),
            StructField("DepthBaseMD", DoubleType(), True),
            StructField("DepthTopTVD", DoubleType(), True),
            StructField("DepthBaseTVD", DoubleType(), True),
            StructField("GrossThickness", DoubleType(), True),
            StructField("NetPayThickness", DoubleType(), True),
            StructField("PorosityAverage", DoubleType(), True),
            StructField("WaterSaturationAverage", DoubleType(), True),
            StructField("PermeabilityHorizontal", DoubleType(), True),
            StructField("PermeabilityVertical", DoubleType(), True),
            StructField("InitialReservoirPressure", DoubleType(), True),
            StructField("ReservoirTemperature", DoubleType(), True),
            StructField("GeoContexts_json", StringType(), True),
            StructField("NameAliases_json", StringType(), True),
            StructField("ExtensionProperties_json", StringType(), True),
        ]
    )


    # ---------------------------------------------------------------------------
    # Rock_and_Fluid (osdu:wks:master-data--Sample:2.1.0)
    # ---------------------------------------------------------------------------
    # The OSDU Sample kind keeps almost everything inside the
    # ``data.SampleAcquisition`` nested struct. Lift the most useful
    # scalars to typed columns; preserve the whole nested object as JSON
    # for fidelity.
    ROCK_AND_FLUID_SCHEMA: StructType = StructType(
        _envelope_fields()
        + [
            StructField("SampleAcquisitionJobID", StringType(), True),
            StructField("SampleAcquisitionTypeID", StringType(), True),
            StructField("SampleAcquisitionContainerID", StringType(), True),
            StructField("AcquisitionStartDate", StringType(), True),
            StructField("AcquisitionEndDate", StringType(), True),
            StructField("CollectionServiceCompanyID", StringType(), True),
            StructField("HandlingServiceCompanyID", StringType(), True),
            StructField("WellboreID", StringType(), True),
            StructField("ToolKind", StringType(), True),
            StructField("RunNumber", StringType(), True),
            StructField("TopDepth", DoubleType(), True),
            StructField("BaseDepth", DoubleType(), True),
            StructField("FormationPressure", DoubleType(), True),
            StructField("FormationTemperature", DoubleType(), True),
            StructField("SampleAcquisition_json", StringType(), True),
            StructField("ExtensionProperties_json", StringType(), True),
        ]
    )


    TABLE_SCHEMAS: dict[str, StructType] = {
        "Wellbore": WELLBORE_SCHEMA,
        "Reservoir": RESERVOIR_SCHEMA,
        "Rock_and_Fluid": ROCK_AND_FLUID_SCHEMA,
    }


    # ---------------------------------------------------------------------------
    # Per-table metadata
    # ---------------------------------------------------------------------------
    # All three tables have ``id`` as PK and use ``modifyTime`` for CDC.
    # Deletes happen at the OSDU Storage layer and are not reflected in the
    # Search index — so ``cdc`` (no deletes) is the correct ingestion type.
    TABLE_METADATA: dict[str, dict] = {
        "Wellbore": {
            "primary_keys": ["id"],
            "cursor_field": "modifyTime",
            "ingestion_type": "cdc",
        },
        "Reservoir": {
            "primary_keys": ["id"],
            "cursor_field": "modifyTime",
            "ingestion_type": "cdc",
        },
        "Rock_and_Fluid": {
            "primary_keys": ["id"],
            "cursor_field": "modifyTime",
            "ingestion_type": "cdc",
        },
    }


    ########################################################
    # src/databricks/labs/community_connector/sources/adme/adme.py
    ########################################################

    DEFAULT_PAGE_SIZE = 1000
    MAX_PAGE_SIZE = 1000

    DEFAULT_WINDOW_DAYS = 1
    DEFAULT_LOOKBACK_MINUTES = 5

    EPOCH_ISO = "1970-01-01T00:00:00.000Z"
    FIRST_RUN_SENTINEL_THRESHOLD = "2000-01-01T00:00:00.000Z"

    _DATA_PARTITION_ID_PATTERN = re.compile(r"[A-Za-z0-9]+(-[A-Za-z0-9]+)*")

    RETRIABLE_STATUS_CODES = {429, 500, 502, 503, 504}
    MAX_RETRIES = 5
    INITIAL_BACKOFF = 1.0

    _ERROR_BODY_LIMIT = 256


    def _redact_body(text: str) -> str:
        """Return text truncated and stripped of CR/LF for safe error messages."""
        if not text:
            return ""
        flattened = text.replace("\r", " ").replace("\n", " ")
        if len(flattened) <= _ERROR_BODY_LIMIT:
            return flattened
        return flattened[:_ERROR_BODY_LIMIT] + "...[truncated]"


    # ---------------------------------------------------------------------------
    # Auth
    # ---------------------------------------------------------------------------

    AUTH_MODE_SERVICE_PRINCIPAL = "service_principal"
    AUTH_MODE_MANAGED_IDENTITY = "managed_identity"
    AUTH_MODE_FEDERATED_IDENTITY = "federated_identity"
    AUTH_MODE_STATIC_TOKEN = "static_token"
    VALID_AUTH_MODES = {
        AUTH_MODE_SERVICE_PRINCIPAL,
        AUTH_MODE_MANAGED_IDENTITY,
        AUTH_MODE_FEDERATED_IDENTITY,
        AUTH_MODE_STATIC_TOKEN,
    }


    class _TokenCache:
        """In-memory bearer-token cache for the Azure AD client-credentials flow."""

        def __init__(
            self,
            tenant_id: str,
            client_id: str,
            client_secret: str,
            adme_api_client_id: str | None = None,
        ) -> None:
            self._tenant_id = tenant_id
            self._client_id = client_id
            self._client_secret = client_secret
            self._audience = adme_api_client_id or client_id
            self._lock = threading.Lock()
            self._token: str | None = None
            self._expires_at: float = 0.0

        @property
        def token_url(self) -> str:
            return (
                f"https://login.microsoftonline.com/{self._tenant_id}/oauth2/v2.0/token"
            )

        def get(self, force_refresh: bool = False) -> str:
            with self._lock:
                now = time.time()
                if (
                    not force_refresh
                    and self._token
                    and now < self._expires_at - 60
                ):
                    return self._token
                self._token, self._expires_at = self._fetch()
                return self._token

        def invalidate(self) -> None:
            with self._lock:
                self._token = None
                self._expires_at = 0.0

        def _fetch(self) -> tuple[str, float]:
            body = {
                "grant_type": "client_credentials",
                "client_id": self._client_id,
                "client_secret": self._client_secret,
                "scope": f"{self._audience}/.default",
            }
            resp = requests.post(
                self.token_url,
                data=body,
                headers={"Content-Type": "application/x-www-form-urlencoded"},
                timeout=30,
            )
            if resp.status_code != 200:
                raise RuntimeError(
                    f"ADME auth failed: {resp.status_code} {_redact_body(resp.text)}"
                )
            payload = resp.json()
            token = payload.get("access_token")
            if not token:
                redacted_keys = sorted(k for k in payload if k != "access_token")
                raise RuntimeError(
                    "ADME auth response missing access_token; "
                    f"keys present: {redacted_keys}"
                )
            expires_in = float(payload.get("expires_in", 3600))
            return token, time.time() + expires_in


    class _AzureIdentityTokenProvider:
        """Token provider backed by azure.identity credentials.

        Covers managed_identity and federated_identity modes.
        """

        def __init__(self, credential: Any, scope: str) -> None:
            self._credential = credential
            self._scope = scope
            self._lock = threading.Lock()
            self._token: str | None = None
            self._expires_at: float = 0.0

        def get(self, force_refresh: bool = False) -> str:
            with self._lock:
                now = time.time()
                if (
                    not force_refresh
                    and self._token
                    and now < self._expires_at - 60
                ):
                    return self._token
                tok = self._credential.get_token(self._scope)
                self._token = tok.token
                self._expires_at = float(tok.expires_on)
                return self._token

        def invalidate(self) -> None:
            with self._lock:
                self._token = None
                self._expires_at = 0.0


    class _StaticTokenProvider:
        """Pre-issued bearer token (CI / testing)."""

        def __init__(self, token: str) -> None:
            if not token or not token.strip():
                raise ValueError("static_token mode requires a non-empty access_token")
            self._token = token.strip()

        def get(self, force_refresh: bool = False) -> str:
            return self._token

        def invalidate(self) -> None:
            pass


    def _read_federated_token(token_inline: str | None, token_file: str | None) -> str:
        """Read federated assertion from inline value or token file."""
        if token_inline and token_inline.strip():
            return token_inline.strip()
        if token_file:
            path = os.path.expandvars(os.path.expanduser(token_file))
            with open(path, "r", encoding="utf-8") as f:
                return f.read().strip()
        raise ValueError(
            "federated_identity mode requires federated_token or federated_token_file"
        )


    def _build_token_provider(options: dict[str, str]) -> tuple[Any, str]:
        """Construct the auth provider implied by options['auth_mode'].

        Returns (provider, audience).
        """
        auth_mode = (options.get("auth_mode") or AUTH_MODE_SERVICE_PRINCIPAL).strip()
        if auth_mode not in VALID_AUTH_MODES:
            raise ValueError(
                f"unknown auth_mode {auth_mode!r}; expected one of "
                f"{sorted(VALID_AUTH_MODES)}"
            )

        tenant_id = options.get("tenant_id")
        client_id = options.get("client_id")
        adme_api_client_id = options.get("adme_api_client_id") or client_id

        if auth_mode == AUTH_MODE_SERVICE_PRINCIPAL:
            client_secret = options.get("client_secret")
            for name, value in [
                ("tenant_id", tenant_id),
                ("client_id", client_id),
                ("client_secret", client_secret),
            ]:
                if not value:
                    raise ValueError(
                        f"service_principal mode requires connection option {name!r}"
                    )
            return (
                _TokenCache(
                    tenant_id=tenant_id,
                    client_id=client_id,
                    client_secret=client_secret,
                    adme_api_client_id=adme_api_client_id,
                ),
                adme_api_client_id,
            )

        if auth_mode == AUTH_MODE_STATIC_TOKEN:
            token = options.get("access_token")
            return _StaticTokenProvider(token), adme_api_client_id

        try:
            from azure.identity import (
                ClientAssertionCredential,
                ManagedIdentityCredential,
            )
        except ImportError as e:
            raise RuntimeError(
                f"auth_mode={auth_mode} requires the azure-identity package; "
                "install with `pip install azure-identity>=1.15.0`"
            ) from e

        if not adme_api_client_id:
            raise ValueError(
                f"auth_mode={auth_mode} requires connection option 'adme_api_client_id' "
                "(OAuth2 audience for the ADME API) when 'client_id' is not set"
            )

        scope = f"{adme_api_client_id}/.default"

        if auth_mode == AUTH_MODE_MANAGED_IDENTITY:
            mi_client_id = options.get("managed_identity_client_id")
            if mi_client_id:
                credential = ManagedIdentityCredential(client_id=mi_client_id)
            else:
                credential = ManagedIdentityCredential()
            return _AzureIdentityTokenProvider(credential, scope), adme_api_client_id

        # federated_identity
        if not tenant_id:
            raise ValueError("federated_identity mode requires tenant_id")
        sp_client_id = options.get("client_id")
        if not sp_client_id:
            raise ValueError(
                "federated_identity mode requires client_id (the service principal id)"
            )
        token_inline = options.get("federated_token")
        token_file = options.get("federated_token_file")
        _read_federated_token(token_inline, token_file)

        def _get_assertion() -> str:
            return _read_federated_token(token_inline, token_file)

        credential = ClientAssertionCredential(
            tenant_id=tenant_id,
            client_id=sp_client_id,
            func=_get_assertion,
        )
        return _AzureIdentityTokenProvider(credential, scope), adme_api_client_id


    # ---------------------------------------------------------------------------
    # Connector
    # ---------------------------------------------------------------------------


    class ADMELakeflowConnect(LakeflowConnect, SupportsPartitionedStream):
        """LakeflowConnect implementation for Azure Data Manager for Energy.

        Required connection options:
            base_url             ADME instance base URL (alias: instance_url)
            data_partition_id    e.g. opendes

        Auth options (selected by auth_mode):
            auth_mode            service_principal | managed_identity |
                                 federated_identity | static_token
            tenant_id            Azure AD tenant ID
            client_id            SP / app registration client ID
            client_secret        SP secret (service_principal only)
            adme_api_client_id   Audience for the OAuth2 scope
            managed_identity_client_id   User-assigned MI client ID
            federated_token / federated_token_file   OIDC assertion source
            access_token         Pre-issued bearer token (static_token only)

        Optional:
            page_size            Search page size (default 1000, max 1000)

        Per-table options:
            window_days          Partition size in days (default 1)
            lookback_minutes     Lookback applied to start cursor (default 5)
            kind_query_<table>   Override OSDU kind query for a specific table
        """

        def __init__(self, options: dict[str, str]) -> None:
            super().__init__(options)

            instance_url = options.get("base_url") or options.get("instance_url")
            data_partition_id = options.get("data_partition_id")

            for name, value in [
                ("base_url (or instance_url)", instance_url),
                ("data_partition_id", data_partition_id),
            ]:
                if not value:
                    raise ValueError(
                        f"ADME connector requires connection option {name!r}"
                    )

            if not _DATA_PARTITION_ID_PATTERN.fullmatch(data_partition_id):
                raise ValueError(
                    "ADME connector option 'data_partition_id' must be "
                    "alphanumeric segments joined by single hyphens "
                    "(e.g. 'opendes', 'dp-int'); no leading/trailing hyphens, "
                    "no consecutive hyphens, no whitespace or control chars"
                )

            self._instance_url = instance_url.rstrip("/")
            self._data_partition_id = data_partition_id

            try:
                self._page_size = max(
                    1, min(MAX_PAGE_SIZE, int(options.get("page_size") or DEFAULT_PAGE_SIZE))
                )
            except (TypeError, ValueError):
                self._page_size = DEFAULT_PAGE_SIZE

            self._token_provider, self._adme_audience = _build_token_provider(options)
            self._session = requests.Session()

            self._init_time = (
                datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%S.000Z")
            )

        # ------------------------------------------------------------------
        # Schema / metadata
        # ------------------------------------------------------------------

        def list_tables(self) -> list[str]:
            return list(SUPPORTED_TABLES)

        def get_table_schema(
            self, table_name: str, table_options: dict[str, str]
        ) -> StructType:
            self._validate_table(table_name)
            return TABLE_SCHEMAS[table_name]

        def read_table_metadata(
            self, table_name: str, table_options: dict[str, str]
        ) -> dict:
            self._validate_table(table_name)
            return dict(TABLE_METADATA[table_name])

        # ------------------------------------------------------------------
        # SupportsPartitionedStream
        # ------------------------------------------------------------------

        def is_partitioned(self, table_name: str) -> bool:
            return table_name in SUPPORTED_TABLES

        def latest_offset(
            self,
            table_name: str,
            table_options: dict[str, str],
            start_offset: dict | None = None,
        ) -> dict:
            """Return the most recent offset (capped at init time)."""
            self._validate_table(table_name)
            return {"cursor": self._init_time}

        def get_partitions(
            self,
            table_name: str,
            table_options: dict[str, str],
            start_offset: dict | None = None,
            end_offset: dict | None = None,
        ) -> Sequence[dict]:
            """Split the (start, end] modifyTime range into windowed partitions."""
            self._validate_table(table_name)

            window_days = self._parse_int(
                table_options.get("window_days"), DEFAULT_WINDOW_DAYS, minimum=1
            )
            lookback_minutes = self._parse_int(
                table_options.get("lookback_minutes"),
                DEFAULT_LOOKBACK_MINUTES,
                minimum=0,
            )

            if start_offset is None and end_offset is None:
                start_iso = EPOCH_ISO
                end_iso = self._init_time
            else:
                start_iso = (start_offset or {}).get("cursor") or EPOCH_ISO
                end_iso = (end_offset or {}).get("cursor") or self._init_time

            # Compare on parsed datetimes so hand-edited or non-canonical
            # cursor strings (different precision, missing time component)
            # don't lex-order incorrectly against canonical EPOCH_ISO / init_time.
            start_dt = self._parse_iso(start_iso)
            end_dt = self._parse_iso(end_iso)
            if start_dt >= end_dt:
                return []

            # First-run optimization: single open-ended partition
            if start_dt <= self._parse_iso(FIRST_RUN_SENTINEL_THRESHOLD):
                return [{"since": EPOCH_ISO, "until": end_iso}]

            if lookback_minutes > 0:
                start_iso = self._subtract_minutes(start_iso, lookback_minutes)
                start_dt = self._parse_iso(start_iso)
                if start_dt >= end_dt:
                    return []

            partitions: list[dict] = []
            cursor = start_iso
            cursor_dt = start_dt
            while cursor_dt < end_dt:
                next_iso = self._add_days(cursor, window_days)
                next_dt = self._parse_iso(next_iso)
                if next_dt > end_dt:
                    next_iso = end_iso
                    next_dt = end_dt
                partitions.append({"since": cursor, "until": next_iso})
                cursor = next_iso
                cursor_dt = next_dt

            return partitions

        def read_partition(
            self,
            table_name: str,
            partition: dict,
            table_options: dict[str, str],
        ) -> Iterator[dict]:
            """Read one (since, until] window of records on an executor."""
            self._validate_table(table_name)

            since = partition["since"]
            until = partition["until"]
            kind_query = self._resolve_kind_query(table_name, table_options)

            lucene = self._build_lucene_range(since, until)
            yield from self._search_paginated(kind_query, lucene)

        # ------------------------------------------------------------------
        # LakeflowConnect.read_table — fallback for non-partitioned reads
        # ------------------------------------------------------------------

        def read_table(
            self,
            table_name: str,
            start_offset: dict,
            table_options: dict[str, str],
        ) -> tuple[Iterator[dict], dict]:
            """Single-driver fallback path."""
            self._validate_table(table_name)

            since = (start_offset or {}).get("cursor") or EPOCH_ISO
            if self._parse_iso(since) >= self._parse_iso(self._init_time):
                return iter([]), start_offset or {"cursor": self._init_time}

            kind_query = self._resolve_kind_query(table_name, table_options)
            lucene = self._build_lucene_range(since, self._init_time)

            records = list(self._search_paginated(kind_query, lucene))
            return iter(records), {"cursor": self._init_time}

        # ------------------------------------------------------------------
        # Helpers
        # ------------------------------------------------------------------

        def _validate_table(self, table_name: str) -> None:
            if table_name not in SUPPORTED_TABLES:
                raise ValueError(
                    f"Unsupported table {table_name!r}; "
                    f"supported: {SUPPORTED_TABLES}"
                )

        @staticmethod
        def _resolve_kind_query(table_name: str, table_options: dict[str, str]) -> str:
            """Return the OSDU kind query for a table, honouring per-table overrides.

            Checks table_options for kind_query_<table_name_lower> first (e.g.
            kind_query_rock_and_fluid), then falls back to TABLE_TO_KIND_QUERY.
            This allows operators to point a table at a different OSDU kind
            without code changes (e.g. RockSampleAnalysis instead of Sample).
            """
            override_key = f"kind_query_{table_name.lower()}"
            override = table_options.get(override_key)
            if override and override.strip():
                return override.strip()
            return TABLE_TO_KIND_QUERY[table_name]

        @staticmethod
        def _parse_int(value: Any, default: int, *, minimum: int = 0) -> int:
            try:
                parsed = int(value)
            except (TypeError, ValueError):
                return default
            return parsed if parsed >= minimum else default

        @staticmethod
        def _add_days(iso_ts: str, days: int) -> str:
            dt = ADMELakeflowConnect._parse_iso(iso_ts) + timedelta(days=days)
            return ADMELakeflowConnect._format_iso(dt)

        @staticmethod
        def _subtract_minutes(iso_ts: str, minutes: int) -> str:
            dt = ADMELakeflowConnect._parse_iso(iso_ts) - timedelta(minutes=minutes)
            return ADMELakeflowConnect._format_iso(dt)

        @staticmethod
        def _parse_iso(iso_ts: str) -> datetime:
            normalised = iso_ts.replace("Z", "+00:00")
            try:
                dt = datetime.fromisoformat(normalised)
            except ValueError as e:
                raise ValueError(f"Invalid ISO timestamp {iso_ts!r}") from e
            if dt.tzinfo is None:
                dt = dt.replace(tzinfo=timezone.utc)
            return dt.astimezone(timezone.utc)

        @staticmethod
        def _format_iso(dt: datetime) -> str:
            return dt.strftime("%Y-%m-%dT%H:%M:%S.") + f"{dt.microsecond // 1000:03d}Z"

        @staticmethod
        def _build_lucene_range(since: str, until: str) -> str:
            """Build the OSDU Lucene range filter on modifyTime.

            Uses exclusive lower bound (`{`) on non-first partitions so back-to-back
            windows are disjoint — a record on a boundary is returned by exactly
            one partition. First-run uses inclusive `[*` to catch everything from
            the epoch. The epoch check parses the cursor so a hand-edited
            checkpoint that's chronologically at-or-before epoch still hits the
            open-ended branch.
            """
            if ADMELakeflowConnect._parse_iso(since) <= ADMELakeflowConnect._parse_iso(EPOCH_ISO):
                return f'modifyTime:[* TO "{until}"]'
            return f'modifyTime:{{"{since}" TO "{until}"]'

        # ------------------------------------------------------------------
        # HTTP layer
        # ------------------------------------------------------------------

        def _common_headers(self) -> dict[str, str]:
            return {
                "Authorization": f"Bearer {self._token_provider.get()}",
                "data-partition-id": self._data_partition_id,
                "Content-Type": "application/json",
                "Accept": "application/json",
            }

        def _post_with_retry(
            self, url: str, body: dict[str, Any]
        ) -> requests.Response:
            """POST with retry on transient failures.

            Budget per logical request:
            - Up to one budget-isolated auth-refresh retry on 401 (does not
              consume the MAX_RETRIES slots).
            - Up to MAX_RETRIES retries on retriable 5xx/429 with exponential
              backoff honouring ``Retry-After``.
            - Up to MAX_RETRIES retries on transient network errors
              (ConnectionError / Timeout / SSLError), sharing the same budget.

            Worst-case round-trip count is therefore ``MAX_RETRIES + 1`` POSTs
            (initial attempt plus one 401-refresh follow-up, both then subject
            to the retriable-failure budget).
            """
            backoff = INITIAL_BACKOFF
            auth_retried = False
            attempts = 0
            resp: requests.Response | None = None
            last_exc: Exception | None = None
            while attempts < MAX_RETRIES:
                try:
                    resp = self._session.post(
                        url,
                        headers=self._common_headers(),
                        data=json.dumps(body),
                        timeout=60,
                    )
                except (
                    requests.ConnectionError,
                    requests.Timeout,
                    requests.exceptions.SSLError,
                ) as exc:
                    last_exc = exc
                    attempts += 1
                    if attempts >= MAX_RETRIES:
                        raise
                    time.sleep(backoff)
                    backoff *= 2
                    continue

                if resp.status_code == 401 and not auth_retried:
                    self._token_provider.invalidate()
                    auth_retried = True
                    continue
                if resp.status_code not in RETRIABLE_STATUS_CODES:
                    return resp

                attempts += 1
                if attempts < MAX_RETRIES:
                    retry_after = resp.headers.get("Retry-After")
                    try:
                        wait = float(retry_after) if retry_after else backoff
                    except (TypeError, ValueError):
                        wait = backoff
                    time.sleep(wait)
                    backoff *= 2

            if resp is None and last_exc is not None:
                raise last_exc
            return resp  # type: ignore[return-value]

        def _search_paginated(
            self, kind_query: str, lucene_query: str
        ) -> Iterator[dict]:
            """Yield flat records by paginating query_with_cursor."""
            url = f"{self._instance_url}/api/search/v2/query_with_cursor"
            cursor: str | None = None
            while True:
                body: dict[str, Any] = {
                    "kind": kind_query,
                    "query": lucene_query,
                    "limit": self._page_size,
                }
                if cursor:
                    body["cursor"] = cursor

                resp = self._post_with_retry(url, body)
                if resp.status_code != 200:
                    raise RuntimeError(
                        f"ADME search failed for kind={kind_query!r}: "
                        f"{resp.status_code} {_redact_body(resp.text)}"
                    )
                payload = resp.json()
                results = payload.get("results") or []
                for raw in results:
                    yield _flatten_record(raw)

                next_cursor = payload.get("cursor")
                if not next_cursor or not results:
                    return
                cursor = next_cursor


    # ---------------------------------------------------------------------------
    # Record flattening
    # ---------------------------------------------------------------------------


    def _flatten_record(raw: dict[str, Any]) -> dict[str, Any]:
        """Project an OSDU envelope into the flat shape declared by TABLE_SCHEMAS."""
        if not isinstance(raw, dict):
            return {}

        data = raw.get("data") if isinstance(raw.get("data"), dict) else {}
        acl = raw.get("acl") if isinstance(raw.get("acl"), dict) else {}
        legal = raw.get("legal") if isinstance(raw.get("legal"), dict) else {}

        base: dict[str, Any] = {
            "id": raw.get("id"),
            "kind": raw.get("kind"),
            "version": _coerce_long(raw.get("version")),
            "createTime": raw.get("createTime"),
            "createUser": raw.get("createUser"),
            "modifyTime": raw.get("modifyTime") or raw.get("createTime"),
            "modifyUser": raw.get("modifyUser"),
            "acl_owners": _as_string_list(acl.get("owners")),
            "acl_viewers": _as_string_list(acl.get("viewers")),
            "legal_legaltags": _as_string_list(legal.get("legaltags")),
            "legal_status": legal.get("status"),
            "legal_otherRelevantDataCountries": _as_string_list(
                legal.get("otherRelevantDataCountries")
            ),
            "tags_json": _json_or_none(raw.get("tags")),
            "meta_json": _json_or_none(raw.get("meta")),
            "data_json": _json_or_none(data),
        }

        kind = raw.get("kind") or ""

        if "master-data--Wellbore" in kind:
            base.update(_flatten_wellbore(data))
        elif "master-data--Reservoir" in kind:
            base.update(_flatten_reservoir(data))
        elif "master-data--Sample" in kind:
            base.update(_flatten_sample(data))

        return base


    def _flatten_wellbore(data: dict[str, Any]) -> dict[str, Any]:
        return {
            "FacilityID": data.get("FacilityID"),
            "FacilityName": data.get("FacilityName"),
            "FacilityTypeID": data.get("FacilityTypeID"),
            "WellID": data.get("WellID"),
            "KickOffWellboreID": data.get("KickOffWellboreID"),
            "StatusSummary": data.get("StatusSummary"),
            "TargetFormation": data.get("TargetFormation"),
            "FacilityNameAliases_json": _json_or_none(data.get("FacilityNameAliases")),
            "FacilityOperators_json": _json_or_none(data.get("FacilityOperators")),
            "VerticalMeasurements_json": _json_or_none(data.get("VerticalMeasurements")),
            "SpatialLocation_json": _json_or_none(data.get("SpatialLocation")),
            "GeoContexts_json": _json_or_none(data.get("GeoContexts")),
            "DrillingReasons_json": _json_or_none(data.get("DrillingReasons")),
            "InitialCompletion_json": _json_or_none(data.get("InitialCompletion")),
            "ExtensionProperties_json": _json_or_none(data.get("ExtensionProperties")),
        }


    def _flatten_reservoir(data: dict[str, Any]) -> dict[str, Any]:
        return {
            "ReservoirID": data.get("ReservoirID"),
            "ReservoirName": data.get("ReservoirName"),
            "ReservoirType": data.get("ReservoirType"),
            "ReservoirDescription": data.get("ReservoirDescription"),
            "FieldID": data.get("FieldID"),
            "BasinID": data.get("BasinID"),
            "FormationID": data.get("FormationID"),
            "FluidTypeID": data.get("FluidTypeID"),
            "DepthTopMD": _coerce_double(data.get("DepthTopMD")),
            "DepthBaseMD": _coerce_double(data.get("DepthBaseMD")),
            "DepthTopTVD": _coerce_double(data.get("DepthTopTVD")),
            "DepthBaseTVD": _coerce_double(data.get("DepthBaseTVD")),
            "GrossThickness": _coerce_double(data.get("GrossThickness")),
            "NetPayThickness": _coerce_double(data.get("NetPayThickness")),
            "PorosityAverage": _coerce_double(data.get("PorosityAverage")),
            "WaterSaturationAverage": _coerce_double(data.get("WaterSaturationAverage")),
            "PermeabilityHorizontal": _coerce_double(data.get("PermeabilityHorizontal")),
            "PermeabilityVertical": _coerce_double(data.get("PermeabilityVertical")),
            "InitialReservoirPressure": _coerce_double(data.get("InitialReservoirPressure")),
            "ReservoirTemperature": _coerce_double(data.get("ReservoirTemperature")),
            "GeoContexts_json": _json_or_none(data.get("GeoContexts")),
            "NameAliases_json": _json_or_none(data.get("NameAliases")),
            "ExtensionProperties_json": _json_or_none(data.get("ExtensionProperties")),
        }


    def _flatten_sample(data: dict[str, Any]) -> dict[str, Any]:
        sa = data.get("SampleAcquisition") or {}
        detail = sa.get("SampleAcquisitionDetail") or {}
        formation_cond = (
            detail.get("FormationCondition")
            if isinstance(detail.get("FormationCondition"), dict)
            else {}
        )
        return {
            "SampleAcquisitionJobID": sa.get("SampleAcquisitionJobID"),
            "SampleAcquisitionTypeID": sa.get("SampleAcquisitionTypeID"),
            "SampleAcquisitionContainerID": sa.get("SampleAcquisitionContainerID"),
            "AcquisitionStartDate": sa.get("AcquisitionStartDate"),
            "AcquisitionEndDate": sa.get("AcquisitionEndDate"),
            "CollectionServiceCompanyID": sa.get("CollectionServiceCompanyID"),
            "HandlingServiceCompanyID": sa.get("HandlingServiceCompanyID"),
            "WellboreID": detail.get("WellboreID"),
            "ToolKind": detail.get("ToolKind"),
            "RunNumber": _coerce_str(detail.get("RunNumber")),
            "TopDepth": _coerce_double(detail.get("TopDepth")),
            "BaseDepth": _coerce_double(detail.get("BaseDepth")),
            "FormationPressure": _coerce_double(formation_cond.get("Pressure")),
            "FormationTemperature": _coerce_double(formation_cond.get("Temperature")),
            "SampleAcquisition_json": _json_or_none(sa),
            "ExtensionProperties_json": _json_or_none(data.get("ExtensionProperties")),
        }


    def _as_string_list(value: Any) -> list[str] | None:
        if value is None:
            return None
        if isinstance(value, list):
            return [str(item) for item in value]
        return [str(value)]


    def _json_or_none(value: Any) -> str | None:
        if value is None:
            return None
        try:
            return json.dumps(value, ensure_ascii=False)
        except (TypeError, ValueError):
            return None


    def _coerce_long(value: Any) -> int | None:
        if value is None:
            return None
        try:
            return int(value)
        except (TypeError, ValueError):
            return None


    def _coerce_double(value: Any) -> float | None:
        if value is None:
            return None
        try:
            return float(value)
        except (TypeError, ValueError):
            return None


    def _coerce_str(value: Any) -> str | None:
        if value is None:
            return None
        return str(value)


    ########################################################
    # src/databricks/labs/community_connector/sparkpds/lakeflow_datasource.py
    ########################################################

    LakeflowConnectImpl = ADMELakeflowConnect
    # Constant option or column names
    METADATA_TABLE = "_community_table_metadata"
    NAMESPACES_TABLE = "_community_namespaces"
    TABLES_TABLE = "_community_tables"
    VIRTUAL_TABLES = (METADATA_TABLE, NAMESPACES_TABLE, TABLES_TABLE)
    TABLE_NAME = "tableName"
    TABLE_NAME_LIST = "tableNameList"
    TABLE_CONFIGS = "tableConfigs"
    IS_DELETE_FLOW = "isDeleteFlow"
    NAMESPACE_PREFIX = "namespacePrefix"
    NAMESPACE = "namespace"


    def _decode_list_of_str_option(option_name: str, value: str | None) -> list[str] | None:
        """Decode and validate a JSON-encoded ``list[str]`` Spark option.

        Returns ``None`` if the option is absent; otherwise the parsed list.
        Raises ``ValueError`` with the offending value if the JSON is malformed
        or the decoded value is not a list of strings.
        """
        if value is None:
            return None
        try:
            decoded = json.loads(value)
        except json.JSONDecodeError as e:
            raise ValueError(
                f"option '{option_name}' must be a JSON-encoded list[str]; "
                f"got non-JSON value: {value!r}"
            ) from e
        if not isinstance(decoded, list) or not all(isinstance(s, str) for s in decoded):
            raise ValueError(
                f"option '{option_name}' must be a JSON-encoded list[str]; "
                f"got: {decoded!r}"
            )
        return decoded


    def _decode_dict_option(option_name: str, value: str | None) -> dict:
        """Decode and validate a JSON-encoded ``dict`` Spark option."""
        if value is None:
            return {}
        try:
            decoded = json.loads(value)
        except json.JSONDecodeError as e:
            raise ValueError(
                f"option '{option_name}' must be a JSON-encoded dict; "
                f"got non-JSON value: {value!r}"
            ) from e
        if not isinstance(decoded, dict):
            raise ValueError(
                f"option '{option_name}' must be a JSON-encoded dict; got: {decoded!r}"
            )
        return decoded


    def _parse_or_passthrough_records(records, schema: StructType):
        """Convert row records while passing PyArrow RecordBatches directly to Spark."""
        iterator = iter(records)
        try:
            first = next(iterator)
        except StopIteration:
            return iter(())

        first_type = type(first)
        if first_type.__name__ == "RecordBatch" and first_type.__module__.startswith("pyarrow."):
            return chain((first,), iterator)

        return chain(
            (parse_value(first, schema),),
            map(lambda value: parse_value(value, schema), iterator),
        )


    # PySpark's DataSource API requires camelCase method names and inherits
    # semantics from the parent class, so per-method docstrings are redundant.
    # pylint: disable=invalid-name,missing-function-docstring
    class LakeflowStreamReader(SimpleDataSourceStreamReader, SupportsTriggerAvailableNow):
        """
        Implements a data source stream reader for Lakeflow Connect.
        Currently, only the simpleStreamReader is implemented, which uses a
        more generic protocol suitable for most data sources that support
        incremental loading.
        """

        def __init__(
            self,
            options: dict[str, str],
            schema: StructType,
            lakeflow_connect: LakeflowConnect,
        ):
            self.options = options
            self.lakeflow_connect = lakeflow_connect
            self.schema = schema

        def initialOffset(self):
            return {}

        def read(self, start: dict) -> (Iterator[tuple], dict):
            is_delete_flow = self.options.get(IS_DELETE_FLOW) == "true"
            # Strip delete flow options before passing to connector
            table_options = {
                k: v for k, v in self.options.items() if k != IS_DELETE_FLOW
            }

            if is_delete_flow:
                records, offset = self.lakeflow_connect.read_table_deletes(
                    self.options[TABLE_NAME], start, table_options
                )
            else:
                records, offset = self.lakeflow_connect.read_table(
                    self.options[TABLE_NAME], start, table_options
                )
            rows = _parse_or_passthrough_records(records, self.schema)
            return rows, offset

        def readBetweenOffsets(self, start: dict, end: dict) -> Iterator[tuple]:
            # TODO: This does not ensure the records returned are identical across repeated calls.
            # For append-only tables, the data source must guarantee that reading from the same
            # start offset will always yield the same set of records.
            # For tables ingested as incremental CDC, it is only necessary that no new changes
            # are missed in the returned records.
            return self.read(start)[0]

        def prepareForTriggerAvailableNow(self) -> None:
            # No need to do anything special here. Everything is handled in the __init__ method.
            pass


    class LakeflowPartitionedStreamReader(DataSourceStreamReader, SupportsTriggerAvailableNow):
        """Proxy that bridges SupportsPartitionedStream to PySpark's DataSourceStreamReader.

        Used when a connector implements the SupportsPartitionedStream mixin to
        support partitioned streaming reads across Spark executors.
        """

        def __init__(
            self,
            options: dict[str, str],
            schema: StructType,
            lakeflow_connect: LakeflowConnect,
        ):
            self.options = options
            self.schema = schema
            self.lakeflow_connect = lakeflow_connect
            self.table_name = options[TABLE_NAME]
            self.table_options = {k: v for k, v in options.items() if k != IS_DELETE_FLOW}

        def initialOffset(self):
            return {}

        def getDefaultReadLimit(self):
            # Admission control is the connector's responsibility (e.g. via
            # window_days, max_records_per_batch), not the engine's.  Always
            # ask the engine for ReadAllAvailable.
            return ReadAllAvailable()

        def latestOffset(self, start: dict, limit) -> dict:
            # We declared ReadAllAvailable via getDefaultReadLimit; the engine
            # must respect it.  Anything else means admission-control expectations
            # we do not support — fail loudly rather than silently ignore.
            if not isinstance(limit, ReadAllAvailable):
                raise ValueError(
                    f"LakeflowPartitionedStreamReader only supports ReadAllAvailable; "
                    f"got {type(limit).__name__}. Micro-batch sizing must be controlled "
                    f"by the connector implementation (table_options), not the engine."
                )
            return self.lakeflow_connect.latest_offset(
                self.table_name, self.table_options, start
            )

        def partitions(self, start: dict, end: dict):
            partition_descs = self.lakeflow_connect.get_partitions(
                self.table_name, self.table_options, start, end
            )
            return [InputPartition(json.dumps(p)) for p in partition_descs]

        def read(self, partition: InputPartition):
            partition_desc = json.loads(partition.value)
            records = self.lakeflow_connect.read_partition(
                self.table_name, partition_desc, self.table_options
            )
            return _parse_or_passthrough_records(records, self.schema)

        def prepareForTriggerAvailableNow(self) -> None:
            # No need to do anything special here. Everything is handled in the __init__ method.
            pass


    class LakeflowBatchReader(DataSourceReader):
        def __init__(
            self,
            options: dict[str, str],
            schema: StructType,
            lakeflow_connect: LakeflowConnect,
        ):
            self.options = options
            self.schema = schema
            self.lakeflow_connect = lakeflow_connect
            self.table_name = options[TABLE_NAME]
            self._supports_partition = isinstance(lakeflow_connect, SupportsPartition)

        def partitions(self):
            if self._supports_partition and self.table_name not in VIRTUAL_TABLES:
                try:
                    partition_descs = self.lakeflow_connect.get_partitions(
                        self.table_name, self.options
                    )
                    return [InputPartition(json.dumps(p)) for p in partition_descs]
                except Exception:
                    self._supports_partition = False
            return [InputPartition(None)]

        def read(self, partition):
            if self.table_name == METADATA_TABLE:
                records = self._read_table_metadata()
            elif self.table_name == NAMESPACES_TABLE:
                records = self._read_namespaces()
            elif self.table_name == TABLES_TABLE:
                records = self._read_tables()
            elif self._supports_partition and partition.value is not None:
                partition_desc = json.loads(partition.value)
                records = self.lakeflow_connect.read_partition(
                    self.table_name, partition_desc, self.options
                )
            else:
                records, _ = self.lakeflow_connect.read_table(self.table_name, None, self.options)
            return _parse_or_passthrough_records(records, self.schema)

        def _read_table_metadata(self):
            table_names = _decode_list_of_str_option(
                TABLE_NAME_LIST, self.options.get(TABLE_NAME_LIST)
            ) or []
            table_configs = _decode_dict_option(
                TABLE_CONFIGS, self.options.get(TABLE_CONFIGS)
            )
            all_records = []
            # Preserve caller-supplied table order — caller controls it.
            for table in table_names:
                metadata = self.lakeflow_connect.read_table_metadata(
                    table, table_configs.get(table, {})
                )
                all_records.append({TABLE_NAME: table, **metadata})
            return all_records

        def _read_namespaces(self):
            # Connectors without SupportsNamespaces are flat — no rows.
            if not isinstance(self.lakeflow_connect, SupportsNamespaces):
                return []
            prefix = _decode_list_of_str_option(
                NAMESPACE_PREFIX, self.options.get(NAMESPACE_PREFIX)
            )
            namespaces = self.lakeflow_connect.list_namespaces(prefix)
            # Sort framework-side for deterministic output regardless of
            # connector iteration order.
            return [{"namespace": ns} for ns in sorted(namespaces)]

        def _read_tables(self):
            namespace_supplied = NAMESPACE in self.options
            if isinstance(self.lakeflow_connect, SupportsNamespaces):
                if not namespace_supplied:
                    raise ValueError(
                        f"option '{NAMESPACE}' is required when reading "
                        f"'{TABLES_TABLE}' against a connector that implements "
                        f"SupportsNamespaces. Pass a JSON-encoded list[str] "
                        f"(use '[]' for root-level tables; walk the tree via "
                        f"'{NAMESPACES_TABLE}' to enumerate every namespace)."
                    )
                namespace = _decode_list_of_str_option(
                    NAMESPACE, self.options[NAMESPACE]
                )
                tables = self.lakeflow_connect.list_tables_in_namespace(namespace)
                return [
                    {"namespace": namespace, TABLE_NAME: tn}
                    for tn in sorted(tables)
                ]
            # Flat connector path. Reject a stray `namespace` option — the
            # caller probably mistook this connector for namespace-aware and
            # silently ignoring the option would mask the bug.
            if namespace_supplied:
                raise ValueError(
                    f"option '{NAMESPACE}' was supplied but the connector does "
                    f"not implement SupportsNamespaces. Either omit the option "
                    f"or use a namespace-aware connector."
                )
            return [
                {"namespace": [], TABLE_NAME: tn}
                for tn in sorted(self.lakeflow_connect.list_tables())
            ]


    class LakeflowSource(DataSource):
        """
        PySpark DataSource base for Lakeflow Connect.

        Two ways the connector implementation is bound:

        - Per-source subclass (wheel / multi-file deployment): subclass and set
          ``_lakeflow_connect_cls``::

              class GmailDataSource(LakeflowSource):
                  _lakeflow_connect_cls = GmailLakeflowConnect

              spark.dataSource.register(GmailDataSource)

        - Merged single-file deployment (SDP): ``_lakeflow_connect_cls`` is left
          ``None`` and the connector is taken from the module-level
          ``LakeflowConnectImpl`` placeholder, which the merge script substitutes
          with the actual implementation class.
        """

        # Per-source subclasses set this. Left ``None`` on the base so the merged
        # single-file path falls back to the ``LakeflowConnectImpl`` placeholder.
        _lakeflow_connect_cls = None

        # Spark format name. Defaults to "lakeflow_connect" because Unity Catalog
        # connection-option injection looks for that exact string. A per-source
        # subclass may override this with its source name once it no longer relies
        # on UC injection (see the commented override in each source's __init__.py).
        _format_name = "lakeflow_connect"

        def __init__(self, options):
            self.options = options
            table = options.get(TABLE_NAME)
            # Catch typos against the framework's reserved virtual-table namespace
            # early — falling through to the connector with an unknown
            # `_community_*` name yields a confusing per-connector error.
            if table and table.startswith("_community_") and table not in VIRTUAL_TABLES:
                raise ValueError(
                    f"unknown framework virtual table '{table}'. Valid framework "
                    f"virtual tables are: {', '.join(VIRTUAL_TABLES)}. "
                    f"For a regular source table, use a name that does not start "
                    f"with '_community_'."
                )
            # Per-source subclasses bind the implementation via _lakeflow_connect_cls.
            # The merged single-file path leaves it None and relies on the
            # LakeflowConnectImpl placeholder (substituted by the merge script).
            connect_cls = type(self)._lakeflow_connect_cls or LakeflowConnectImpl
            self.lakeflow_connect = connect_cls(options)  # pylint: disable=abstract-class-instantiated

        @classmethod
        def name(cls):
            return cls._format_name

        def schema(self):
            table = self.options[TABLE_NAME]
            if table == METADATA_TABLE:
                return StructType(
                    [
                        StructField(TABLE_NAME, StringType(), False),
                        StructField("primary_keys", ArrayType(StringType()), True),
                        StructField("cursor_field", StringType(), True),
                        StructField("ingestion_type", StringType(), True),
                    ]
                )
            if table == NAMESPACES_TABLE:
                return StructType(
                    [
                        StructField("namespace", ArrayType(StringType()), False),
                    ]
                )
            if table == TABLES_TABLE:
                return StructType(
                    [
                        StructField("namespace", ArrayType(StringType()), False),
                        StructField(TABLE_NAME, StringType(), False),
                    ]
                )
            return self.lakeflow_connect.get_table_schema(table, self.options)

        def reader(self, schema: StructType):
            return LakeflowBatchReader(self.options, schema, self.lakeflow_connect)

        def streamReader(self, schema: StructType):
            # Use the partitioned DataSourceStreamReader when the connector
            # implements SupportsPartitionedStream and the table opts in.
            # Otherwise, delegate to super() which raises PySparkNotImplementedError,
            # causing Spark to fall back to simpleStreamReader().
            if isinstance(self.lakeflow_connect, SupportsPartitionedStream):
                table = self.options[TABLE_NAME]
                if self.lakeflow_connect.is_partitioned(table):
                    return LakeflowPartitionedStreamReader(self.options, schema, self.lakeflow_connect)
            return super().streamReader(schema)

        def simpleStreamReader(self, schema: StructType):
            return LakeflowStreamReader(self.options, schema, self.lakeflow_connect)


    spark.dataSource.register(LakeflowSource)
